_syscalls.c
int errno
Referenced by _sbrk, raise, kill.
void* __dso_handle __attribute__((weak))
Referenced by kill.
void __initialize_args(int *p_argc, char ***p_argv)
Referenced by kill.
int raise(int sig __attribute__((unused)))
References errno, kill.
int kill(pid_t pid, int sig)
Referenced by raise.
int kill(pid_t pid __attribute__((unused)), int sig __attribute__((unused)))
References errno, __attribute__, __initialize_args, SEMIHOSTING_SYS_GET_CMDLINE, ADP_Stopped_ApplicationExit, ADP_Stopped_RunTimeError, SEMIHOSTING_SYS_OPEN, SEMIHOSTING_SYS_ERRNO, SEMIHOSTING_SYS_READ, SEMIHOSTING_SYS_FLEN, SEMIHOSTING_SYS_SEEK, SEMIHOSTING_SYS_WRITE, SEMIHOSTING_SYS_CLOSE, SEMIHOSTING_SYS_REMOVE, SEMIHOSTING_SYS_TIME, SEMIHOSTING_SYS_CLOCK, SEMIHOSTING_SYS_ISTTY, SEMIHOSTING_SYS_SYSTEM, SEMIHOSTING_SYS_RENAME.