Trace.h
void trace_initialize(void)
ssize_t trace_write(const char *buf, size_t nbyte)
Referenced by __attribute__.
int trace_printf(const char *format,...)
Referenced by main, __attribute__.
int trace_puts(const char *s)
Referenced by main, __attribute__, __gnu_cxx::__verbose_terminate_handler, __cxa_pure_virtual.
int trace_putchar(int c)
Referenced by __attribute__.
void trace_dump_args(int argc, char *argv[])
Referenced by __attribute__.
void __attribute__((always_inline)) trace_initialize(void)
References trace_write.
Referenced by __attribute__.
ssize_t size_t nbyte __attribute__((unused)))
References __attribute__, trace_printf, trace_puts, trace_putchar, trace_dump_args.