Timer
typedef uint32_t Timer::ticks_t
constexpr ticks_t Timer::FREQUENCY_HZ
Referenced by main.
volatile Timer::ticks_t Timer::ms_delayCount
Timer::Timer()=default
void Timer::start(void)
References SysTick_Config, SystemCoreClock, sleep.
Referenced by main.
void Timer::sleep(ticks_t ticks)
Referenced by start, main.
static void Timer::tick(void)
Referenced by SysTick_Handler.