cmsis_armcc.h
__NOP
No Operation.
No Operation does nothing. This instruction can be used for code alignment purposes.
__WFI
Wait For Interrupt.
Wait For Interrupt is a hint instruction that suspends execution until one of a number of events occurs.
__WFE
Wait For Event.
Wait For Event is a hint instruction that permits the processor to enter a low-power state until one of a number of events occurs.
__SEV
Send Event.
Send Event is a hint instruction. It causes an event to be signaled to the CPU.
__ISB
Instruction Synchronization Barrier.
Instruction Synchronization Barrier flushes the pipeline in the processor, so that all instructions following the ISB are fetched from cache or memory, after the instruction has been completed.
__DSB
Data Synchronization Barrier.
Acts as a special kind of Data Memory Barrier. It completes when all explicit memory accesses before this instruction complete.
__DMB
Data Memory Barrier.
Ensures the apparent order of the explicit memory operations before and after the instruction, without ensuring their completion.
__REV
Reverse byte order (32 bit)
Reverses the byte order in integer value. value Value to reverse Reversed value
__ROR
Rotate Right in unsigned value (32 bit)
Rotate Right (immediate) provides the value of the contents of a register rotated by a variable number of bits. value Value to rotate value Number of Bits to rotate Rotated value
__BKPT
Breakpoint.
Causes the processor to enter Debug state. Debug tools can use this to investigate system state when the instruction at a particular address is reached. value is ignored by the processor. If required, a debugger can use it to store additional information about the breakpoint.
__CLZ
Count leading zeros.
Counts the number of leading zeros of a data value. value Value to count the leading zeros number of leading zeros in value
__STATIC_INLINE uint32_t __get_CONTROL(void)
Get Control Register.
Returns the content of the Control Register. Control Register value
Referenced by __attribute__.
__STATIC_INLINE void __set_CONTROL(uint32_t control)
Set Control Register.
Writes the given value to the Control Register. control Control Register value to set
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_IPSR(void)
Get IPSR Register.
Returns the content of the IPSR Register. IPSR Register value
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_APSR(void)
Get APSR Register.
Returns the content of the APSR Register. APSR Register value
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_xPSR(void)
Get xPSR Register.
Returns the content of the xPSR Register. xPSR Register value
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_PSP(void)
Get Process Stack Pointer.
Returns the current value of the Process Stack Pointer (PSP). PSP Register value
Referenced by __attribute__.
__STATIC_INLINE void __set_PSP(uint32_t topOfProcStack)
Set Process Stack Pointer.
Assigns the given value to the Process Stack Pointer (PSP). topOfProcStack Process Stack Pointer value to set
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_MSP(void)
Get Main Stack Pointer.
Returns the current value of the Main Stack Pointer (MSP). MSP Register value
Referenced by __attribute__.
__STATIC_INLINE void __set_MSP(uint32_t topOfMainStack)
Set Main Stack Pointer.
Assigns the given value to the Main Stack Pointer (MSP). topOfMainStack Main Stack Pointer value to set
Referenced by __attribute__.
__STATIC_INLINE uint32_t __get_PRIMASK(void)
Get Priority Mask.
Returns the current state of the priority mask bit from the Priority Mask Register. Priority Mask value
Referenced by __attribute__.
__STATIC_INLINE void __set_PRIMASK(uint32_t priMask)
Set Priority Mask.
Assigns the given value to the Priority Mask Register. priMask Priority Mask
Referenced by __attribute__.
__attribute__((section(".rev16_text"))) __STATIC_INLINE __ASM uint32_t __REV16(uint32_t value)
Reverse byte order (16 bit)
Reverses the byte order in two unsigned short values. value Value to reverse Reversed value
__attribute__((section(".revsh_text"))) __STATIC_INLINE __ASM int32_t __REVSH(int32_t value)
Reverse byte order in signed short value.
Reverses the byte order in a signed short value with sign extension to integer. value Value to reverse Reversed value
void __attribute__((always_inline)) __STATIC_INLINE uint32_t __RBIT(uint32_t value)
Reverse bit order of value.
Enable IRQ Interrupts.Set Priority Mask.Get Priority Mask.Set Main Stack Pointer.Get Main Stack Pointer.Set Process Stack Pointer.Get Process Stack Pointer.Get xPSR Register.Get APSR Register.Get IPSR Register.Set Control Register.Get Control Register.Disable IRQ Interrupts.Reverse byte order (16 bit)Reverse byte order (32 bit)Data Memory Barrier.Data Synchronization Barrier.Instruction Synchronization Barrier.Send Event.Wait For Event.Wait For Interrupt.No Operation.Rotate Right in unsigned value (32 bit)Reverse byte order in signed short value.Reverses the bit order of the given value. value Value to reverse Reversed value Reverses the byte order in a signed short value with sign extension to integer. value Value to reverse Reversed value Rotate Right (immediate) provides the value of the contents of a register rotated by a variable number of bits. op1 Value to rotate op2 Number of Bits to rotate Rotated value No Operation does nothing. This instruction can be used for code alignment purposes.Wait For Interrupt is a hint instruction that suspends execution until one of a number of events occurs.Wait For Event is a hint instruction that permits the processor to enter a low-power state until one of a number of events occurs.Send Event is a hint instruction. It causes an event to be signaled to the CPU.Instruction Synchronization Barrier flushes the pipeline in the processor, so that all instructions following the ISB are fetched from cache or memory, after the instruction has been completed.Acts as a special kind of Data Memory Barrier. It completes when all explicit memory accesses before this instruction complete.Ensures the apparent order of the explicit memory operations before and after the instruction, without ensuring their completion.Reverses the byte order in integer value. value Value to reverse Reversed value Reverses the byte order in two unsigned short values. value Value to reverse Reversed value Rotate Right (immediate) provides the value of the contents of a register rotated by a variable number of bits. value Value to rotate value Number of Bits to rotate Rotated value Disables IRQ interrupts by setting the I-bit in the CPSR. Can only be executed in Privileged modes.Returns the content of the Control Register. Control Register value Writes the given value to the Control Register. control Control Register value to set Returns the content of the IPSR Register. IPSR Register value Returns the content of the APSR Register. APSR Register value Returns the content of the xPSR Register. xPSR Register value Returns the current value of the Process Stack Pointer (PSP). PSP Register value Assigns the given value to the Process Stack Pointer (PSP). topOfProcStack Process Stack Pointer value to set Returns the current value of the Main Stack Pointer (MSP). MSP Register value Assigns the given value to the Main Stack Pointer (MSP). topOfMainStack Main Stack Pointer value to set Returns the current state of the priority mask bit from the Priority Mask Register. Priority Mask value Assigns the given value to the Priority Mask Register. priMask Priority Mask Enables IRQ interrupts by clearing the I-bit in the CPSR. Can only be executed in Privileged modes.
References value.