core_cm0.h
__CM0_CMSIS_VERSION_MAIN
[31:16] CMSIS HAL main version
__CM0_CMSIS_VERSION_SUB
[15:0] CMSIS HAL sub version
__CM0_CMSIS_VERSION
CMSIS HAL version number
__CORTEX_M
Cortex-M Core
__FPU_USED
__FPU_USED indicates whether an FPU is used or not. This core does not support an FPU at all
__CORE_CM0_H_DEPENDANT
__I
Defines 'read only' permissions
__O
Defines 'write only' permissions
__IO
Defines 'read / write' permissions
__IM
__OM
__IOM
__CORE_CM0_H_GENERIC
APSR_N_Pos
APSR: N Position
APSR_N_Msk
APSR: N Mask
APSR_Z_Pos
APSR: Z Position
APSR_Z_Msk
APSR: Z Mask
APSR_C_Pos
APSR: C Position
APSR_C_Msk
APSR: C Mask
APSR_V_Pos
APSR: V Position
APSR_V_Msk
APSR: V Mask
IPSR_ISR_Pos
IPSR: ISR Position
IPSR_ISR_Msk
IPSR: ISR Mask
xPSR_N_Pos
xPSR: N Position
xPSR_N_Msk
xPSR: N Mask
xPSR_Z_Pos
xPSR: Z Position
xPSR_Z_Msk
xPSR: Z Mask
xPSR_C_Pos
xPSR: C Position
xPSR_C_Msk
xPSR: C Mask
xPSR_V_Pos
xPSR: V Position
xPSR_V_Msk
xPSR: V Mask
xPSR_T_Pos
xPSR: T Position
xPSR_T_Msk
xPSR: T Mask
xPSR_ISR_Pos
xPSR: ISR Position
xPSR_ISR_Msk
xPSR: ISR Mask
CONTROL_SPSEL_Pos
CONTROL: SPSEL Position
CONTROL_SPSEL_Msk
CONTROL: SPSEL Mask
SCB_CPUID_IMPLEMENTER_Pos
SCB CPUID: IMPLEMENTER Position
SCB_CPUID_IMPLEMENTER_Msk
SCB CPUID: IMPLEMENTER Mask
SCB_CPUID_VARIANT_Pos
SCB CPUID: VARIANT Position
SCB_CPUID_VARIANT_Msk
SCB CPUID: VARIANT Mask
SCB_CPUID_ARCHITECTURE_Pos
SCB CPUID: ARCHITECTURE Position
SCB_CPUID_ARCHITECTURE_Msk
SCB CPUID: ARCHITECTURE Mask
SCB_CPUID_PARTNO_Pos
SCB CPUID: PARTNO Position
SCB_CPUID_PARTNO_Msk
SCB CPUID: PARTNO Mask
SCB_CPUID_REVISION_Pos
SCB CPUID: REVISION Position
SCB_CPUID_REVISION_Msk
SCB CPUID: REVISION Mask
SCB_ICSR_NMIPENDSET_Pos
SCB ICSR: NMIPENDSET Position
SCB_ICSR_NMIPENDSET_Msk
SCB ICSR: NMIPENDSET Mask
SCB_ICSR_PENDSVSET_Pos
SCB ICSR: PENDSVSET Position
SCB_ICSR_PENDSVSET_Msk
SCB ICSR: PENDSVSET Mask
SCB_ICSR_PENDSVCLR_Pos
SCB ICSR: PENDSVCLR Position
SCB_ICSR_PENDSVCLR_Msk
SCB ICSR: PENDSVCLR Mask
SCB_ICSR_PENDSTSET_Pos
SCB ICSR: PENDSTSET Position
SCB_ICSR_PENDSTSET_Msk
SCB ICSR: PENDSTSET Mask
SCB_ICSR_PENDSTCLR_Pos
SCB ICSR: PENDSTCLR Position
SCB_ICSR_PENDSTCLR_Msk
SCB ICSR: PENDSTCLR Mask
SCB_ICSR_ISRPREEMPT_Pos
SCB ICSR: ISRPREEMPT Position
SCB_ICSR_ISRPREEMPT_Msk
SCB ICSR: ISRPREEMPT Mask
SCB_ICSR_ISRPENDING_Pos
SCB ICSR: ISRPENDING Position
SCB_ICSR_ISRPENDING_Msk
SCB ICSR: ISRPENDING Mask
SCB_ICSR_VECTPENDING_Pos
SCB ICSR: VECTPENDING Position
SCB_ICSR_VECTPENDING_Msk
SCB ICSR: VECTPENDING Mask
SCB_ICSR_VECTACTIVE_Pos
SCB ICSR: VECTACTIVE Position
SCB_ICSR_VECTACTIVE_Msk
SCB ICSR: VECTACTIVE Mask
SCB_AIRCR_VECTKEY_Pos
SCB AIRCR: VECTKEY Position
SCB_AIRCR_VECTKEY_Msk
SCB AIRCR: VECTKEY Mask
SCB_AIRCR_VECTKEYSTAT_Pos
SCB AIRCR: VECTKEYSTAT Position
SCB_AIRCR_VECTKEYSTAT_Msk
SCB AIRCR: VECTKEYSTAT Mask
SCB_AIRCR_ENDIANESS_Pos
SCB AIRCR: ENDIANESS Position
SCB_AIRCR_ENDIANESS_Msk
SCB AIRCR: ENDIANESS Mask
SCB_AIRCR_SYSRESETREQ_Pos
SCB AIRCR: SYSRESETREQ Position
SCB_AIRCR_SYSRESETREQ_Msk
SCB AIRCR: SYSRESETREQ Mask
SCB_AIRCR_VECTCLRACTIVE_Pos
SCB AIRCR: VECTCLRACTIVE Position
SCB_AIRCR_VECTCLRACTIVE_Msk
SCB AIRCR: VECTCLRACTIVE Mask
SCB_SCR_SEVONPEND_Pos
SCB SCR: SEVONPEND Position
SCB_SCR_SEVONPEND_Msk
SCB SCR: SEVONPEND Mask
SCB_SCR_SLEEPDEEP_Pos
SCB SCR: SLEEPDEEP Position
SCB_SCR_SLEEPDEEP_Msk
SCB SCR: SLEEPDEEP Mask
SCB_SCR_SLEEPONEXIT_Pos
SCB SCR: SLEEPONEXIT Position
SCB_SCR_SLEEPONEXIT_Msk
SCB SCR: SLEEPONEXIT Mask
SCB_CCR_STKALIGN_Pos
SCB CCR: STKALIGN Position
SCB_CCR_STKALIGN_Msk
SCB CCR: STKALIGN Mask
SCB_CCR_UNALIGN_TRP_Pos
SCB CCR: UNALIGN_TRP Position
SCB_CCR_UNALIGN_TRP_Msk
SCB CCR: UNALIGN_TRP Mask
SCB_SHCSR_SVCALLPENDED_Pos
SCB SHCSR: SVCALLPENDED Position
SCB_SHCSR_SVCALLPENDED_Msk
SCB SHCSR: SVCALLPENDED Mask
SysTick_CTRL_COUNTFLAG_Pos
SysTick CTRL: COUNTFLAG Position
SysTick_CTRL_COUNTFLAG_Msk
SysTick CTRL: COUNTFLAG Mask
SysTick_CTRL_CLKSOURCE_Pos
SysTick CTRL: CLKSOURCE Position
SysTick_CTRL_CLKSOURCE_Msk
SysTick CTRL: CLKSOURCE Mask
SysTick_CTRL_TICKINT_Pos
SysTick CTRL: TICKINT Position
SysTick_CTRL_TICKINT_Msk
SysTick CTRL: TICKINT Mask
SysTick_CTRL_ENABLE_Pos
SysTick CTRL: ENABLE Position
SysTick_CTRL_ENABLE_Msk
SysTick CTRL: ENABLE Mask
SysTick_LOAD_RELOAD_Pos
SysTick LOAD: RELOAD Position
SysTick_LOAD_RELOAD_Msk
SysTick LOAD: RELOAD Mask
SysTick_VAL_CURRENT_Pos
SysTick VAL: CURRENT Position
SysTick_VAL_CURRENT_Msk
SysTick VAL: CURRENT Mask
SysTick_CALIB_NOREF_Pos
SysTick CALIB: NOREF Position
SysTick_CALIB_NOREF_Msk
SysTick CALIB: NOREF Mask
SysTick_CALIB_SKEW_Pos
SysTick CALIB: SKEW Position
SysTick_CALIB_SKEW_Msk
SysTick CALIB: SKEW Mask
SysTick_CALIB_TENMS_Pos
SysTick CALIB: TENMS Position
SysTick_CALIB_TENMS_Msk
SysTick CALIB: TENMS Mask
_VAL2FLD
Mask and shift a bit field value for use in a register bit range.
field Name of the register bit field. value Value of the bit field. Masked and shifted value.
_FLD2VAL
Mask and shift a register value to extract a bit filed value.
field Name of the register bit field. value Value of register. Masked and shifted bit field value.
SCS_BASE
System Control Space Base Address
SysTick_BASE
SysTick Base Address
NVIC_BASE
NVIC Base Address
SCB_BASE
System Control Block Base Address
SCB
SCB configuration struct
SysTick
SysTick configuration struct
NVIC
NVIC configuration struct
_BIT_SHIFT
_SHP_IDX
_IP_IDX
__STATIC_INLINE void NVIC_EnableIRQ(IRQn_Type IRQn)
Enable External Interrupt.
Enables a device-specific interrupt in the NVIC interrupt controller. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_DisableIRQ(IRQn_Type IRQn)
Disable External Interrupt.
Disables a device-specific interrupt in the NVIC interrupt controller. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ(IRQn_Type IRQn)
Get Pending Interrupt.
Reads the pending register in the NVIC and returns the pending bit for the specified interrupt. IRQn Interrupt number. 0 Interrupt status is not pending. 1 Interrupt status is pending.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_SetPendingIRQ(IRQn_Type IRQn)
Set Pending Interrupt.
Sets the pending bit of an external interrupt. IRQn Interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_ClearPendingIRQ(IRQn_Type IRQn)
Clear Pending Interrupt.
Clears the pending bit of an external interrupt. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_SetPriority(IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
Sets the priority of an interrupt. The priority cannot be set for every core interrupt. IRQn Interrupt number. priority Priority to set.
References SCB, _SHP_IDX, _BIT_SHIFT, __NVIC_PRIO_BITS, NVIC, _IP_IDX.
Referenced by SysTick_Config, NVIC_GetActive, NVIC_DecodePriority, SCB_CleanInvalidateDCache_by_Addr.
__STATIC_INLINE uint32_t NVIC_GetPriority(IRQn_Type IRQn)
Get Interrupt Priority.
Reads the priority of an interrupt. The interrupt number can be positive to specify an external (device specific) interrupt, or negative to specify an internal (core) interrupt. IRQn Interrupt number. Interrupt Priority. Value is aligned automatically to the implemented priority bits of the microcontroller.
References SCB, _SHP_IDX, _BIT_SHIFT, __NVIC_PRIO_BITS, NVIC, _IP_IDX.
Referenced by NVIC_GetActive.
__STATIC_INLINE void NVIC_SystemReset(void)
System Reset.
Initiates a system reset request to reset the MCU.
References __DSB, SCB, SCB_AIRCR_VECTKEY_Pos, SCB_AIRCR_SYSRESETREQ_Msk, __NOP.
Referenced by NVIC_DecodePriority, __attribute__.
__STATIC_INLINE uint32_t SysTick_Config(uint32_t ticks)
System Tick Configuration.
Initializes the System Timer and its interrupt, and starts the System Tick Timer. Counter is in free running mode to generate periodic interrupts. ticks Number of ticks between two interrupts. 0 Function succeeded. 1 Function failed. When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included. In this case, the file device.h must contain a vendor-specific implementation of this function.
References SysTick_LOAD_RELOAD_Msk, SysTick, NVIC_SetPriority, SysTick_IRQn, __NVIC_PRIO_BITS, SysTick_CTRL_CLKSOURCE_Msk, SysTick_CTRL_TICKINT_Msk, SysTick_CTRL_ENABLE_Msk.
Referenced by Timer::start, NVIC_DecodePriority, SCB_CleanInvalidateDCache_by_Addr.