core_cm4.h
__CM4_CMSIS_VERSION_MAIN
[31:16] CMSIS HAL main version
__CM4_CMSIS_VERSION_SUB
[15:0] CMSIS HAL sub version
__CM4_CMSIS_VERSION
CMSIS HAL version number
__CORTEX_M
Cortex-M Core
__CORE_CM4_H_DEPENDANT
__FPU_USED indicates whether an FPU is used or not. For this, __FPU_PRESENT has to be checked prior to making use of FPU specific registers and functions.
__I
Defines 'read only' permissions
__O
Defines 'write only' permissions
__IO
Defines 'read / write' permissions
__IM
__OM
__IOM
__CORE_CM4_H_GENERIC
APSR_N_Pos
APSR: N Position
APSR_N_Msk
APSR: N Mask
APSR_Z_Pos
APSR: Z Position
APSR_Z_Msk
APSR: Z Mask
APSR_C_Pos
APSR: C Position
APSR_C_Msk
APSR: C Mask
APSR_V_Pos
APSR: V Position
APSR_V_Msk
APSR: V Mask
APSR_Q_Pos
APSR: Q Position
APSR_Q_Msk
APSR: Q Mask
APSR_GE_Pos
APSR: GE Position
APSR_GE_Msk
APSR: GE Mask
IPSR_ISR_Pos
IPSR: ISR Position
IPSR_ISR_Msk
IPSR: ISR Mask
xPSR_N_Pos
xPSR: N Position
xPSR_N_Msk
xPSR: N Mask
xPSR_Z_Pos
xPSR: Z Position
xPSR_Z_Msk
xPSR: Z Mask
xPSR_C_Pos
xPSR: C Position
xPSR_C_Msk
xPSR: C Mask
xPSR_V_Pos
xPSR: V Position
xPSR_V_Msk
xPSR: V Mask
xPSR_Q_Pos
xPSR: Q Position
xPSR_Q_Msk
xPSR: Q Mask
xPSR_IT_Pos
xPSR: IT Position
xPSR_IT_Msk
xPSR: IT Mask
xPSR_T_Pos
xPSR: T Position
xPSR_T_Msk
xPSR: T Mask
xPSR_GE_Pos
xPSR: GE Position
xPSR_GE_Msk
xPSR: GE Mask
xPSR_ISR_Pos
xPSR: ISR Position
xPSR_ISR_Msk
xPSR: ISR Mask
CONTROL_FPCA_Pos
CONTROL: FPCA Position
CONTROL_FPCA_Msk
CONTROL: FPCA Mask
CONTROL_SPSEL_Pos
CONTROL: SPSEL Position
CONTROL_SPSEL_Msk
CONTROL: SPSEL Mask
CONTROL_nPRIV_Pos
CONTROL: nPRIV Position
CONTROL_nPRIV_Msk
CONTROL: nPRIV Mask
NVIC_STIR_INTID_Pos
STIR: INTLINESNUM Position
NVIC_STIR_INTID_Msk
STIR: INTLINESNUM Mask
SCB_CPUID_IMPLEMENTER_Pos
SCB CPUID: IMPLEMENTER Position
SCB_CPUID_IMPLEMENTER_Msk
SCB CPUID: IMPLEMENTER Mask
SCB_CPUID_VARIANT_Pos
SCB CPUID: VARIANT Position
SCB_CPUID_VARIANT_Msk
SCB CPUID: VARIANT Mask
SCB_CPUID_ARCHITECTURE_Pos
SCB CPUID: ARCHITECTURE Position
SCB_CPUID_ARCHITECTURE_Msk
SCB CPUID: ARCHITECTURE Mask
SCB_CPUID_PARTNO_Pos
SCB CPUID: PARTNO Position
SCB_CPUID_PARTNO_Msk
SCB CPUID: PARTNO Mask
SCB_CPUID_REVISION_Pos
SCB CPUID: REVISION Position
SCB_CPUID_REVISION_Msk
SCB CPUID: REVISION Mask
SCB_ICSR_NMIPENDSET_Pos
SCB ICSR: NMIPENDSET Position
SCB_ICSR_NMIPENDSET_Msk
SCB ICSR: NMIPENDSET Mask
SCB_ICSR_PENDSVSET_Pos
SCB ICSR: PENDSVSET Position
SCB_ICSR_PENDSVSET_Msk
SCB ICSR: PENDSVSET Mask
SCB_ICSR_PENDSVCLR_Pos
SCB ICSR: PENDSVCLR Position
SCB_ICSR_PENDSVCLR_Msk
SCB ICSR: PENDSVCLR Mask
SCB_ICSR_PENDSTSET_Pos
SCB ICSR: PENDSTSET Position
SCB_ICSR_PENDSTSET_Msk
SCB ICSR: PENDSTSET Mask
SCB_ICSR_PENDSTCLR_Pos
SCB ICSR: PENDSTCLR Position
SCB_ICSR_PENDSTCLR_Msk
SCB ICSR: PENDSTCLR Mask
SCB_ICSR_ISRPREEMPT_Pos
SCB ICSR: ISRPREEMPT Position
SCB_ICSR_ISRPREEMPT_Msk
SCB ICSR: ISRPREEMPT Mask
SCB_ICSR_ISRPENDING_Pos
SCB ICSR: ISRPENDING Position
SCB_ICSR_ISRPENDING_Msk
SCB ICSR: ISRPENDING Mask
SCB_ICSR_VECTPENDING_Pos
SCB ICSR: VECTPENDING Position
SCB_ICSR_VECTPENDING_Msk
SCB ICSR: VECTPENDING Mask
SCB_ICSR_RETTOBASE_Pos
SCB ICSR: RETTOBASE Position
SCB_ICSR_RETTOBASE_Msk
SCB ICSR: RETTOBASE Mask
SCB_ICSR_VECTACTIVE_Pos
SCB ICSR: VECTACTIVE Position
SCB_ICSR_VECTACTIVE_Msk
SCB ICSR: VECTACTIVE Mask
SCB_VTOR_TBLOFF_Pos
SCB VTOR: TBLOFF Position
SCB_VTOR_TBLOFF_Msk
SCB VTOR: TBLOFF Mask
SCB_AIRCR_VECTKEY_Pos
SCB AIRCR: VECTKEY Position
SCB_AIRCR_VECTKEY_Msk
SCB AIRCR: VECTKEY Mask
SCB_AIRCR_VECTKEYSTAT_Pos
SCB AIRCR: VECTKEYSTAT Position
SCB_AIRCR_VECTKEYSTAT_Msk
SCB AIRCR: VECTKEYSTAT Mask
SCB_AIRCR_ENDIANESS_Pos
SCB AIRCR: ENDIANESS Position
SCB_AIRCR_ENDIANESS_Msk
SCB AIRCR: ENDIANESS Mask
SCB_AIRCR_PRIGROUP_Pos
SCB AIRCR: PRIGROUP Position
SCB_AIRCR_PRIGROUP_Msk
SCB AIRCR: PRIGROUP Mask
SCB_AIRCR_SYSRESETREQ_Pos
SCB AIRCR: SYSRESETREQ Position
SCB_AIRCR_SYSRESETREQ_Msk
SCB AIRCR: SYSRESETREQ Mask
SCB_AIRCR_VECTCLRACTIVE_Pos
SCB AIRCR: VECTCLRACTIVE Position
SCB_AIRCR_VECTCLRACTIVE_Msk
SCB AIRCR: VECTCLRACTIVE Mask
SCB_AIRCR_VECTRESET_Pos
SCB AIRCR: VECTRESET Position
SCB_AIRCR_VECTRESET_Msk
SCB AIRCR: VECTRESET Mask
SCB_SCR_SEVONPEND_Pos
SCB SCR: SEVONPEND Position
SCB_SCR_SEVONPEND_Msk
SCB SCR: SEVONPEND Mask
SCB_SCR_SLEEPDEEP_Pos
SCB SCR: SLEEPDEEP Position
SCB_SCR_SLEEPDEEP_Msk
SCB SCR: SLEEPDEEP Mask
SCB_SCR_SLEEPONEXIT_Pos
SCB SCR: SLEEPONEXIT Position
SCB_SCR_SLEEPONEXIT_Msk
SCB SCR: SLEEPONEXIT Mask
SCB_CCR_STKALIGN_Pos
SCB CCR: STKALIGN Position
SCB_CCR_STKALIGN_Msk
SCB CCR: STKALIGN Mask
SCB_CCR_BFHFNMIGN_Pos
SCB CCR: BFHFNMIGN Position
SCB_CCR_BFHFNMIGN_Msk
SCB CCR: BFHFNMIGN Mask
SCB_CCR_DIV_0_TRP_Pos
SCB CCR: DIV_0_TRP Position
SCB_CCR_DIV_0_TRP_Msk
SCB CCR: DIV_0_TRP Mask
SCB_CCR_UNALIGN_TRP_Pos
SCB CCR: UNALIGN_TRP Position
SCB_CCR_UNALIGN_TRP_Msk
SCB CCR: UNALIGN_TRP Mask
SCB_CCR_USERSETMPEND_Pos
SCB CCR: USERSETMPEND Position
SCB_CCR_USERSETMPEND_Msk
SCB CCR: USERSETMPEND Mask
SCB_CCR_NONBASETHRDENA_Pos
SCB CCR: NONBASETHRDENA Position
SCB_CCR_NONBASETHRDENA_Msk
SCB CCR: NONBASETHRDENA Mask
SCB_SHCSR_USGFAULTENA_Pos
SCB SHCSR: USGFAULTENA Position
SCB_SHCSR_USGFAULTENA_Msk
SCB SHCSR: USGFAULTENA Mask
SCB_SHCSR_BUSFAULTENA_Pos
SCB SHCSR: BUSFAULTENA Position
SCB_SHCSR_BUSFAULTENA_Msk
SCB SHCSR: BUSFAULTENA Mask
SCB_SHCSR_MEMFAULTENA_Pos
SCB SHCSR: MEMFAULTENA Position
SCB_SHCSR_MEMFAULTENA_Msk
SCB SHCSR: MEMFAULTENA Mask
SCB_SHCSR_SVCALLPENDED_Pos
SCB SHCSR: SVCALLPENDED Position
SCB_SHCSR_SVCALLPENDED_Msk
SCB SHCSR: SVCALLPENDED Mask
SCB_SHCSR_BUSFAULTPENDED_Pos
SCB SHCSR: BUSFAULTPENDED Position
SCB_SHCSR_BUSFAULTPENDED_Msk
SCB SHCSR: BUSFAULTPENDED Mask
SCB_SHCSR_MEMFAULTPENDED_Pos
SCB SHCSR: MEMFAULTPENDED Position
SCB_SHCSR_MEMFAULTPENDED_Msk
SCB SHCSR: MEMFAULTPENDED Mask
SCB_SHCSR_USGFAULTPENDED_Pos
SCB SHCSR: USGFAULTPENDED Position
SCB_SHCSR_USGFAULTPENDED_Msk
SCB SHCSR: USGFAULTPENDED Mask
SCB_SHCSR_SYSTICKACT_Pos
SCB SHCSR: SYSTICKACT Position
SCB_SHCSR_SYSTICKACT_Msk
SCB SHCSR: SYSTICKACT Mask
SCB_SHCSR_PENDSVACT_Pos
SCB SHCSR: PENDSVACT Position
SCB_SHCSR_PENDSVACT_Msk
SCB SHCSR: PENDSVACT Mask
SCB_SHCSR_MONITORACT_Pos
SCB SHCSR: MONITORACT Position
SCB_SHCSR_MONITORACT_Msk
SCB SHCSR: MONITORACT Mask
SCB_SHCSR_SVCALLACT_Pos
SCB SHCSR: SVCALLACT Position
SCB_SHCSR_SVCALLACT_Msk
SCB SHCSR: SVCALLACT Mask
SCB_SHCSR_USGFAULTACT_Pos
SCB SHCSR: USGFAULTACT Position
SCB_SHCSR_USGFAULTACT_Msk
SCB SHCSR: USGFAULTACT Mask
SCB_SHCSR_BUSFAULTACT_Pos
SCB SHCSR: BUSFAULTACT Position
SCB_SHCSR_BUSFAULTACT_Msk
SCB SHCSR: BUSFAULTACT Mask
SCB_SHCSR_MEMFAULTACT_Pos
SCB SHCSR: MEMFAULTACT Position
SCB_SHCSR_MEMFAULTACT_Msk
SCB SHCSR: MEMFAULTACT Mask
SCB_CFSR_USGFAULTSR_Pos
SCB CFSR: Usage Fault Status Register Position
SCB_CFSR_USGFAULTSR_Msk
SCB CFSR: Usage Fault Status Register Mask
SCB_CFSR_BUSFAULTSR_Pos
SCB CFSR: Bus Fault Status Register Position
SCB_CFSR_BUSFAULTSR_Msk
SCB CFSR: Bus Fault Status Register Mask
SCB_CFSR_MEMFAULTSR_Pos
SCB CFSR: Memory Manage Fault Status Register Position
SCB_CFSR_MEMFAULTSR_Msk
SCB CFSR: Memory Manage Fault Status Register Mask
SCB_HFSR_DEBUGEVT_Pos
SCB HFSR: DEBUGEVT Position
SCB_HFSR_DEBUGEVT_Msk
SCB HFSR: DEBUGEVT Mask
SCB_HFSR_FORCED_Pos
SCB HFSR: FORCED Position
SCB_HFSR_FORCED_Msk
SCB HFSR: FORCED Mask
SCB_HFSR_VECTTBL_Pos
SCB HFSR: VECTTBL Position
SCB_HFSR_VECTTBL_Msk
SCB HFSR: VECTTBL Mask
SCB_DFSR_EXTERNAL_Pos
SCB DFSR: EXTERNAL Position
SCB_DFSR_EXTERNAL_Msk
SCB DFSR: EXTERNAL Mask
SCB_DFSR_VCATCH_Pos
SCB DFSR: VCATCH Position
SCB_DFSR_VCATCH_Msk
SCB DFSR: VCATCH Mask
SCB_DFSR_DWTTRAP_Pos
SCB DFSR: DWTTRAP Position
SCB_DFSR_DWTTRAP_Msk
SCB DFSR: DWTTRAP Mask
SCB_DFSR_BKPT_Pos
SCB DFSR: BKPT Position
SCB_DFSR_BKPT_Msk
SCB DFSR: BKPT Mask
SCB_DFSR_HALTED_Pos
SCB DFSR: HALTED Position
SCB_DFSR_HALTED_Msk
SCB DFSR: HALTED Mask
SCnSCB_ICTR_INTLINESNUM_Pos
ICTR: INTLINESNUM Position
SCnSCB_ICTR_INTLINESNUM_Msk
ICTR: INTLINESNUM Mask
SCnSCB_ACTLR_DISOOFP_Pos
ACTLR: DISOOFP Position
SCnSCB_ACTLR_DISOOFP_Msk
ACTLR: DISOOFP Mask
SCnSCB_ACTLR_DISFPCA_Pos
ACTLR: DISFPCA Position
SCnSCB_ACTLR_DISFPCA_Msk
ACTLR: DISFPCA Mask
SCnSCB_ACTLR_DISFOLD_Pos
ACTLR: DISFOLD Position
SCnSCB_ACTLR_DISFOLD_Msk
ACTLR: DISFOLD Mask
SCnSCB_ACTLR_DISDEFWBUF_Pos
ACTLR: DISDEFWBUF Position
SCnSCB_ACTLR_DISDEFWBUF_Msk
ACTLR: DISDEFWBUF Mask
SCnSCB_ACTLR_DISMCYCINT_Pos
ACTLR: DISMCYCINT Position
SCnSCB_ACTLR_DISMCYCINT_Msk
ACTLR: DISMCYCINT Mask
SysTick_CTRL_COUNTFLAG_Pos
SysTick CTRL: COUNTFLAG Position
SysTick_CTRL_COUNTFLAG_Msk
SysTick CTRL: COUNTFLAG Mask
SysTick_CTRL_CLKSOURCE_Pos
SysTick CTRL: CLKSOURCE Position
SysTick_CTRL_CLKSOURCE_Msk
SysTick CTRL: CLKSOURCE Mask
SysTick_CTRL_TICKINT_Pos
SysTick CTRL: TICKINT Position
SysTick_CTRL_TICKINT_Msk
SysTick CTRL: TICKINT Mask
SysTick_CTRL_ENABLE_Pos
SysTick CTRL: ENABLE Position
SysTick_CTRL_ENABLE_Msk
SysTick CTRL: ENABLE Mask
SysTick_LOAD_RELOAD_Pos
SysTick LOAD: RELOAD Position
SysTick_LOAD_RELOAD_Msk
SysTick LOAD: RELOAD Mask
SysTick_VAL_CURRENT_Pos
SysTick VAL: CURRENT Position
SysTick_VAL_CURRENT_Msk
SysTick VAL: CURRENT Mask
SysTick_CALIB_NOREF_Pos
SysTick CALIB: NOREF Position
SysTick_CALIB_NOREF_Msk
SysTick CALIB: NOREF Mask
SysTick_CALIB_SKEW_Pos
SysTick CALIB: SKEW Position
SysTick_CALIB_SKEW_Msk
SysTick CALIB: SKEW Mask
SysTick_CALIB_TENMS_Pos
SysTick CALIB: TENMS Position
SysTick_CALIB_TENMS_Msk
SysTick CALIB: TENMS Mask
ITM_TPR_PRIVMASK_Pos
ITM TPR: PRIVMASK Position
ITM_TPR_PRIVMASK_Msk
ITM TPR: PRIVMASK Mask
ITM_TCR_BUSY_Pos
ITM TCR: BUSY Position
ITM_TCR_BUSY_Msk
ITM TCR: BUSY Mask
ITM_TCR_TraceBusID_Pos
ITM TCR: ATBID Position
ITM_TCR_TraceBusID_Msk
ITM TCR: ATBID Mask
ITM_TCR_GTSFREQ_Pos
ITM TCR: Global timestamp frequency Position
ITM_TCR_GTSFREQ_Msk
ITM TCR: Global timestamp frequency Mask
ITM_TCR_TSPrescale_Pos
ITM TCR: TSPrescale Position
ITM_TCR_TSPrescale_Msk
ITM TCR: TSPrescale Mask
ITM_TCR_SWOENA_Pos
ITM TCR: SWOENA Position
ITM_TCR_SWOENA_Msk
ITM TCR: SWOENA Mask
ITM_TCR_DWTENA_Pos
ITM TCR: DWTENA Position
ITM_TCR_DWTENA_Msk
ITM TCR: DWTENA Mask
ITM_TCR_SYNCENA_Pos
ITM TCR: SYNCENA Position
ITM_TCR_SYNCENA_Msk
ITM TCR: SYNCENA Mask
ITM_TCR_TSENA_Pos
ITM TCR: TSENA Position
ITM_TCR_TSENA_Msk
ITM TCR: TSENA Mask
ITM_TCR_ITMENA_Pos
ITM TCR: ITM Enable bit Position
ITM_TCR_ITMENA_Msk
ITM TCR: ITM Enable bit Mask
ITM_IWR_ATVALIDM_Pos
ITM IWR: ATVALIDM Position
ITM_IWR_ATVALIDM_Msk
ITM IWR: ATVALIDM Mask
ITM_IRR_ATREADYM_Pos
ITM IRR: ATREADYM Position
ITM_IRR_ATREADYM_Msk
ITM IRR: ATREADYM Mask
ITM_IMCR_INTEGRATION_Pos
ITM IMCR: INTEGRATION Position
ITM_IMCR_INTEGRATION_Msk
ITM IMCR: INTEGRATION Mask
ITM_LSR_ByteAcc_Pos
ITM LSR: ByteAcc Position
ITM_LSR_ByteAcc_Msk
ITM LSR: ByteAcc Mask
ITM_LSR_Access_Pos
ITM LSR: Access Position
ITM_LSR_Access_Msk
ITM LSR: Access Mask
ITM_LSR_Present_Pos
ITM LSR: Present Position
ITM_LSR_Present_Msk
ITM LSR: Present Mask
DWT_CTRL_NUMCOMP_Pos
DWT CTRL: NUMCOMP Position
DWT_CTRL_NUMCOMP_Msk
DWT CTRL: NUMCOMP Mask
DWT_CTRL_NOTRCPKT_Pos
DWT CTRL: NOTRCPKT Position
DWT_CTRL_NOTRCPKT_Msk
DWT CTRL: NOTRCPKT Mask
DWT_CTRL_NOEXTTRIG_Pos
DWT CTRL: NOEXTTRIG Position
DWT_CTRL_NOEXTTRIG_Msk
DWT CTRL: NOEXTTRIG Mask
DWT_CTRL_NOCYCCNT_Pos
DWT CTRL: NOCYCCNT Position
DWT_CTRL_NOCYCCNT_Msk
DWT CTRL: NOCYCCNT Mask
DWT_CTRL_NOPRFCNT_Pos
DWT CTRL: NOPRFCNT Position
DWT_CTRL_NOPRFCNT_Msk
DWT CTRL: NOPRFCNT Mask
DWT_CTRL_CYCEVTENA_Pos
DWT CTRL: CYCEVTENA Position
DWT_CTRL_CYCEVTENA_Msk
DWT CTRL: CYCEVTENA Mask
DWT_CTRL_FOLDEVTENA_Pos
DWT CTRL: FOLDEVTENA Position
DWT_CTRL_FOLDEVTENA_Msk
DWT CTRL: FOLDEVTENA Mask
DWT_CTRL_LSUEVTENA_Pos
DWT CTRL: LSUEVTENA Position
DWT_CTRL_LSUEVTENA_Msk
DWT CTRL: LSUEVTENA Mask
DWT_CTRL_SLEEPEVTENA_Pos
DWT CTRL: SLEEPEVTENA Position
DWT_CTRL_SLEEPEVTENA_Msk
DWT CTRL: SLEEPEVTENA Mask
DWT_CTRL_EXCEVTENA_Pos
DWT CTRL: EXCEVTENA Position
DWT_CTRL_EXCEVTENA_Msk
DWT CTRL: EXCEVTENA Mask
DWT_CTRL_CPIEVTENA_Pos
DWT CTRL: CPIEVTENA Position
DWT_CTRL_CPIEVTENA_Msk
DWT CTRL: CPIEVTENA Mask
DWT_CTRL_EXCTRCENA_Pos
DWT CTRL: EXCTRCENA Position
DWT_CTRL_EXCTRCENA_Msk
DWT CTRL: EXCTRCENA Mask
DWT_CTRL_PCSAMPLENA_Pos
DWT CTRL: PCSAMPLENA Position
DWT_CTRL_PCSAMPLENA_Msk
DWT CTRL: PCSAMPLENA Mask
DWT_CTRL_SYNCTAP_Pos
DWT CTRL: SYNCTAP Position
DWT_CTRL_SYNCTAP_Msk
DWT CTRL: SYNCTAP Mask
DWT_CTRL_CYCTAP_Pos
DWT CTRL: CYCTAP Position
DWT_CTRL_CYCTAP_Msk
DWT CTRL: CYCTAP Mask
DWT_CTRL_POSTINIT_Pos
DWT CTRL: POSTINIT Position
DWT_CTRL_POSTINIT_Msk
DWT CTRL: POSTINIT Mask
DWT_CTRL_POSTPRESET_Pos
DWT CTRL: POSTPRESET Position
DWT_CTRL_POSTPRESET_Msk
DWT CTRL: POSTPRESET Mask
DWT_CTRL_CYCCNTENA_Pos
DWT CTRL: CYCCNTENA Position
DWT_CTRL_CYCCNTENA_Msk
DWT CTRL: CYCCNTENA Mask
DWT_CPICNT_CPICNT_Pos
DWT CPICNT: CPICNT Position
DWT_CPICNT_CPICNT_Msk
DWT CPICNT: CPICNT Mask
DWT_EXCCNT_EXCCNT_Pos
DWT EXCCNT: EXCCNT Position
DWT_EXCCNT_EXCCNT_Msk
DWT EXCCNT: EXCCNT Mask
DWT_SLEEPCNT_SLEEPCNT_Pos
DWT SLEEPCNT: SLEEPCNT Position
DWT_SLEEPCNT_SLEEPCNT_Msk
DWT SLEEPCNT: SLEEPCNT Mask
DWT_LSUCNT_LSUCNT_Pos
DWT LSUCNT: LSUCNT Position
DWT_LSUCNT_LSUCNT_Msk
DWT LSUCNT: LSUCNT Mask
DWT_FOLDCNT_FOLDCNT_Pos
DWT FOLDCNT: FOLDCNT Position
DWT_FOLDCNT_FOLDCNT_Msk
DWT FOLDCNT: FOLDCNT Mask
DWT_MASK_MASK_Pos
DWT MASK: MASK Position
DWT_MASK_MASK_Msk
DWT MASK: MASK Mask
DWT_FUNCTION_MATCHED_Pos
DWT FUNCTION: MATCHED Position
DWT_FUNCTION_MATCHED_Msk
DWT FUNCTION: MATCHED Mask
DWT_FUNCTION_DATAVADDR1_Pos
DWT FUNCTION: DATAVADDR1 Position
DWT_FUNCTION_DATAVADDR1_Msk
DWT FUNCTION: DATAVADDR1 Mask
DWT_FUNCTION_DATAVADDR0_Pos
DWT FUNCTION: DATAVADDR0 Position
DWT_FUNCTION_DATAVADDR0_Msk
DWT FUNCTION: DATAVADDR0 Mask
DWT_FUNCTION_DATAVSIZE_Pos
DWT FUNCTION: DATAVSIZE Position
DWT_FUNCTION_DATAVSIZE_Msk
DWT FUNCTION: DATAVSIZE Mask
DWT_FUNCTION_LNK1ENA_Pos
DWT FUNCTION: LNK1ENA Position
DWT_FUNCTION_LNK1ENA_Msk
DWT FUNCTION: LNK1ENA Mask
DWT_FUNCTION_DATAVMATCH_Pos
DWT FUNCTION: DATAVMATCH Position
DWT_FUNCTION_DATAVMATCH_Msk
DWT FUNCTION: DATAVMATCH Mask
DWT_FUNCTION_CYCMATCH_Pos
DWT FUNCTION: CYCMATCH Position
DWT_FUNCTION_CYCMATCH_Msk
DWT FUNCTION: CYCMATCH Mask
DWT_FUNCTION_EMITRANGE_Pos
DWT FUNCTION: EMITRANGE Position
DWT_FUNCTION_EMITRANGE_Msk
DWT FUNCTION: EMITRANGE Mask
DWT_FUNCTION_FUNCTION_Pos
DWT FUNCTION: FUNCTION Position
DWT_FUNCTION_FUNCTION_Msk
DWT FUNCTION: FUNCTION Mask
TPI_ACPR_PRESCALER_Pos
TPI ACPR: PRESCALER Position
TPI_ACPR_PRESCALER_Msk
TPI ACPR: PRESCALER Mask
TPI_SPPR_TXMODE_Pos
TPI SPPR: TXMODE Position
TPI_SPPR_TXMODE_Msk
TPI SPPR: TXMODE Mask
TPI_FFSR_FtNonStop_Pos
TPI FFSR: FtNonStop Position
TPI_FFSR_FtNonStop_Msk
TPI FFSR: FtNonStop Mask
TPI_FFSR_TCPresent_Pos
TPI FFSR: TCPresent Position
TPI_FFSR_TCPresent_Msk
TPI FFSR: TCPresent Mask
TPI_FFSR_FtStopped_Pos
TPI FFSR: FtStopped Position
TPI_FFSR_FtStopped_Msk
TPI FFSR: FtStopped Mask
TPI_FFSR_FlInProg_Pos
TPI FFSR: FlInProg Position
TPI_FFSR_FlInProg_Msk
TPI FFSR: FlInProg Mask
TPI_FFCR_TrigIn_Pos
TPI FFCR: TrigIn Position
TPI_FFCR_TrigIn_Msk
TPI FFCR: TrigIn Mask
TPI_FFCR_EnFCont_Pos
TPI FFCR: EnFCont Position
TPI_FFCR_EnFCont_Msk
TPI FFCR: EnFCont Mask
TPI_TRIGGER_TRIGGER_Pos
TPI TRIGGER: TRIGGER Position
TPI_TRIGGER_TRIGGER_Msk
TPI TRIGGER: TRIGGER Mask
TPI_FIFO0_ITM_ATVALID_Pos
TPI FIFO0: ITM_ATVALID Position
TPI_FIFO0_ITM_ATVALID_Msk
TPI FIFO0: ITM_ATVALID Mask
TPI_FIFO0_ITM_bytecount_Pos
TPI FIFO0: ITM_bytecount Position
TPI_FIFO0_ITM_bytecount_Msk
TPI FIFO0: ITM_bytecount Mask
TPI_FIFO0_ETM_ATVALID_Pos
TPI FIFO0: ETM_ATVALID Position
TPI_FIFO0_ETM_ATVALID_Msk
TPI FIFO0: ETM_ATVALID Mask
TPI_FIFO0_ETM_bytecount_Pos
TPI FIFO0: ETM_bytecount Position
TPI_FIFO0_ETM_bytecount_Msk
TPI FIFO0: ETM_bytecount Mask
TPI_FIFO0_ETM2_Pos
TPI FIFO0: ETM2 Position
TPI_FIFO0_ETM2_Msk
TPI FIFO0: ETM2 Mask
TPI_FIFO0_ETM1_Pos
TPI FIFO0: ETM1 Position
TPI_FIFO0_ETM1_Msk
TPI FIFO0: ETM1 Mask
TPI_FIFO0_ETM0_Pos
TPI FIFO0: ETM0 Position
TPI_FIFO0_ETM0_Msk
TPI FIFO0: ETM0 Mask
TPI_ITATBCTR2_ATREADY_Pos
TPI ITATBCTR2: ATREADY Position
TPI_ITATBCTR2_ATREADY_Msk
TPI ITATBCTR2: ATREADY Mask
TPI_FIFO1_ITM_ATVALID_Pos
TPI FIFO1: ITM_ATVALID Position
TPI_FIFO1_ITM_ATVALID_Msk
TPI FIFO1: ITM_ATVALID Mask
TPI_FIFO1_ITM_bytecount_Pos
TPI FIFO1: ITM_bytecount Position
TPI_FIFO1_ITM_bytecount_Msk
TPI FIFO1: ITM_bytecount Mask
TPI_FIFO1_ETM_ATVALID_Pos
TPI FIFO1: ETM_ATVALID Position
TPI_FIFO1_ETM_ATVALID_Msk
TPI FIFO1: ETM_ATVALID Mask
TPI_FIFO1_ETM_bytecount_Pos
TPI FIFO1: ETM_bytecount Position
TPI_FIFO1_ETM_bytecount_Msk
TPI FIFO1: ETM_bytecount Mask
TPI_FIFO1_ITM2_Pos
TPI FIFO1: ITM2 Position
TPI_FIFO1_ITM2_Msk
TPI FIFO1: ITM2 Mask
TPI_FIFO1_ITM1_Pos
TPI FIFO1: ITM1 Position
TPI_FIFO1_ITM1_Msk
TPI FIFO1: ITM1 Mask
TPI_FIFO1_ITM0_Pos
TPI FIFO1: ITM0 Position
TPI_FIFO1_ITM0_Msk
TPI FIFO1: ITM0 Mask
TPI_ITATBCTR0_ATREADY_Pos
TPI ITATBCTR0: ATREADY Position
TPI_ITATBCTR0_ATREADY_Msk
TPI ITATBCTR0: ATREADY Mask
TPI_ITCTRL_Mode_Pos
TPI ITCTRL: Mode Position
TPI_ITCTRL_Mode_Msk
TPI ITCTRL: Mode Mask
TPI_DEVID_NRZVALID_Pos
TPI DEVID: NRZVALID Position
TPI_DEVID_NRZVALID_Msk
TPI DEVID: NRZVALID Mask
TPI_DEVID_MANCVALID_Pos
TPI DEVID: MANCVALID Position
TPI_DEVID_MANCVALID_Msk
TPI DEVID: MANCVALID Mask
TPI_DEVID_PTINVALID_Pos
TPI DEVID: PTINVALID Position
TPI_DEVID_PTINVALID_Msk
TPI DEVID: PTINVALID Mask
TPI_DEVID_MinBufSz_Pos
TPI DEVID: MinBufSz Position
TPI_DEVID_MinBufSz_Msk
TPI DEVID: MinBufSz Mask
TPI_DEVID_AsynClkIn_Pos
TPI DEVID: AsynClkIn Position
TPI_DEVID_AsynClkIn_Msk
TPI DEVID: AsynClkIn Mask
TPI_DEVID_NrTraceInput_Pos
TPI DEVID: NrTraceInput Position
TPI_DEVID_NrTraceInput_Msk
TPI DEVID: NrTraceInput Mask
TPI_DEVTYPE_MajorType_Pos
TPI DEVTYPE: MajorType Position
TPI_DEVTYPE_MajorType_Msk
TPI DEVTYPE: MajorType Mask
TPI_DEVTYPE_SubType_Pos
TPI DEVTYPE: SubType Position
TPI_DEVTYPE_SubType_Msk
TPI DEVTYPE: SubType Mask
CoreDebug_DHCSR_DBGKEY_Pos
CoreDebug DHCSR: DBGKEY Position
CoreDebug_DHCSR_DBGKEY_Msk
CoreDebug DHCSR: DBGKEY Mask
CoreDebug_DHCSR_S_RESET_ST_Pos
CoreDebug DHCSR: S_RESET_ST Position
CoreDebug_DHCSR_S_RESET_ST_Msk
CoreDebug DHCSR: S_RESET_ST Mask
CoreDebug_DHCSR_S_RETIRE_ST_Pos
CoreDebug DHCSR: S_RETIRE_ST Position
CoreDebug_DHCSR_S_RETIRE_ST_Msk
CoreDebug DHCSR: S_RETIRE_ST Mask
CoreDebug_DHCSR_S_LOCKUP_Pos
CoreDebug DHCSR: S_LOCKUP Position
CoreDebug_DHCSR_S_LOCKUP_Msk
CoreDebug DHCSR: S_LOCKUP Mask
CoreDebug_DHCSR_S_SLEEP_Pos
CoreDebug DHCSR: S_SLEEP Position
CoreDebug_DHCSR_S_SLEEP_Msk
CoreDebug DHCSR: S_SLEEP Mask
CoreDebug_DHCSR_S_HALT_Pos
CoreDebug DHCSR: S_HALT Position
CoreDebug_DHCSR_S_HALT_Msk
CoreDebug DHCSR: S_HALT Mask
CoreDebug_DHCSR_S_REGRDY_Pos
CoreDebug DHCSR: S_REGRDY Position
CoreDebug_DHCSR_S_REGRDY_Msk
CoreDebug DHCSR: S_REGRDY Mask
CoreDebug_DHCSR_C_SNAPSTALL_Pos
CoreDebug DHCSR: C_SNAPSTALL Position
CoreDebug_DHCSR_C_SNAPSTALL_Msk
CoreDebug DHCSR: C_SNAPSTALL Mask
CoreDebug_DHCSR_C_MASKINTS_Pos
CoreDebug DHCSR: C_MASKINTS Position
CoreDebug_DHCSR_C_MASKINTS_Msk
CoreDebug DHCSR: C_MASKINTS Mask
CoreDebug_DHCSR_C_STEP_Pos
CoreDebug DHCSR: C_STEP Position
CoreDebug_DHCSR_C_STEP_Msk
CoreDebug DHCSR: C_STEP Mask
CoreDebug_DHCSR_C_HALT_Pos
CoreDebug DHCSR: C_HALT Position
CoreDebug_DHCSR_C_HALT_Msk
CoreDebug DHCSR: C_HALT Mask
CoreDebug_DHCSR_C_DEBUGEN_Pos
CoreDebug DHCSR: C_DEBUGEN Position
CoreDebug_DHCSR_C_DEBUGEN_Msk
CoreDebug DHCSR: C_DEBUGEN Mask
CoreDebug_DCRSR_REGWnR_Pos
CoreDebug DCRSR: REGWnR Position
CoreDebug_DCRSR_REGWnR_Msk
CoreDebug DCRSR: REGWnR Mask
CoreDebug_DCRSR_REGSEL_Pos
CoreDebug DCRSR: REGSEL Position
CoreDebug_DCRSR_REGSEL_Msk
CoreDebug DCRSR: REGSEL Mask
CoreDebug_DEMCR_TRCENA_Pos
CoreDebug DEMCR: TRCENA Position
CoreDebug_DEMCR_TRCENA_Msk
CoreDebug DEMCR: TRCENA Mask
CoreDebug_DEMCR_MON_REQ_Pos
CoreDebug DEMCR: MON_REQ Position
CoreDebug_DEMCR_MON_REQ_Msk
CoreDebug DEMCR: MON_REQ Mask
CoreDebug_DEMCR_MON_STEP_Pos
CoreDebug DEMCR: MON_STEP Position
CoreDebug_DEMCR_MON_STEP_Msk
CoreDebug DEMCR: MON_STEP Mask
CoreDebug_DEMCR_MON_PEND_Pos
CoreDebug DEMCR: MON_PEND Position
CoreDebug_DEMCR_MON_PEND_Msk
CoreDebug DEMCR: MON_PEND Mask
CoreDebug_DEMCR_MON_EN_Pos
CoreDebug DEMCR: MON_EN Position
CoreDebug_DEMCR_MON_EN_Msk
CoreDebug DEMCR: MON_EN Mask
CoreDebug_DEMCR_VC_HARDERR_Pos
CoreDebug DEMCR: VC_HARDERR Position
CoreDebug_DEMCR_VC_HARDERR_Msk
CoreDebug DEMCR: VC_HARDERR Mask
CoreDebug_DEMCR_VC_INTERR_Pos
CoreDebug DEMCR: VC_INTERR Position
CoreDebug_DEMCR_VC_INTERR_Msk
CoreDebug DEMCR: VC_INTERR Mask
CoreDebug_DEMCR_VC_BUSERR_Pos
CoreDebug DEMCR: VC_BUSERR Position
CoreDebug_DEMCR_VC_BUSERR_Msk
CoreDebug DEMCR: VC_BUSERR Mask
CoreDebug_DEMCR_VC_STATERR_Pos
CoreDebug DEMCR: VC_STATERR Position
CoreDebug_DEMCR_VC_STATERR_Msk
CoreDebug DEMCR: VC_STATERR Mask
CoreDebug_DEMCR_VC_CHKERR_Pos
CoreDebug DEMCR: VC_CHKERR Position
CoreDebug_DEMCR_VC_CHKERR_Msk
CoreDebug DEMCR: VC_CHKERR Mask
CoreDebug_DEMCR_VC_NOCPERR_Pos
CoreDebug DEMCR: VC_NOCPERR Position
CoreDebug_DEMCR_VC_NOCPERR_Msk
CoreDebug DEMCR: VC_NOCPERR Mask
CoreDebug_DEMCR_VC_MMERR_Pos
CoreDebug DEMCR: VC_MMERR Position
CoreDebug_DEMCR_VC_MMERR_Msk
CoreDebug DEMCR: VC_MMERR Mask
CoreDebug_DEMCR_VC_CORERESET_Pos
CoreDebug DEMCR: VC_CORERESET Position
CoreDebug_DEMCR_VC_CORERESET_Msk
CoreDebug DEMCR: VC_CORERESET Mask
_VAL2FLD
Mask and shift a bit field value for use in a register bit range.
field Name of the register bit field. value Value of the bit field. Masked and shifted value.
_FLD2VAL
Mask and shift a register value to extract a bit filed value.
field Name of the register bit field. value Value of register. Masked and shifted bit field value.
SCS_BASE
System Control Space Base Address
ITM_BASE
ITM Base Address
DWT_BASE
DWT Base Address
TPI_BASE
TPI Base Address
CoreDebug_BASE
Core Debug Base Address
SysTick_BASE
SysTick Base Address
NVIC_BASE
NVIC Base Address
SCB_BASE
System Control Block Base Address
SCnSCB
System control Register not in SCB
SCB
SCB configuration struct
SysTick
SysTick configuration struct
NVIC
NVIC configuration struct
ITM
ITM configuration struct
DWT
DWT configuration struct
TPI
TPI configuration struct
CoreDebug
Core Debug configuration struct
ITM_RXBUFFER_EMPTY
Value identifying ITM_RxBuffer is ready for next character.
volatile int32_t ITM_RxBuffer
External variable to receive characters.
__STATIC_INLINE void NVIC_SetPriorityGrouping(uint32_t PriorityGroup)
Set Priority Grouping.
Sets the priority grouping field using the required unlock sequence. The parameter PriorityGroup is assigned to the field SCB->AIRCR [10:8] PRIGROUP field. Only values from 0..7 are used. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set. PriorityGroup Priority grouping field.
References SCB, SCB_AIRCR_VECTKEY_Msk, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_VECTKEY_Pos.
__STATIC_INLINE uint32_t NVIC_GetPriorityGrouping(void)
Get Priority Grouping.
Reads the priority grouping field from the NVIC Interrupt Controller. Priority grouping field (SCB->AIRCR [10:8] PRIGROUP field).
References SCB, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_PRIGROUP_Pos, NVIC_EnableIRQ, NVIC, NVIC_DisableIRQ, NVIC_GetPendingIRQ, NVIC_SetPendingIRQ, NVIC_ClearPendingIRQ.
__STATIC_INLINE void NVIC_EnableIRQ(IRQn_Type IRQn)
Enable External Interrupt.
Enables a device-specific interrupt in the NVIC interrupt controller. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_DisableIRQ(IRQn_Type IRQn)
Disable External Interrupt.
Disables a device-specific interrupt in the NVIC interrupt controller. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ(IRQn_Type IRQn)
Get Pending Interrupt.
Reads the pending register in the NVIC and returns the pending bit for the specified interrupt. IRQn Interrupt number. 0 Interrupt status is not pending. 1 Interrupt status is pending.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_SetPendingIRQ(IRQn_Type IRQn)
Set Pending Interrupt.
Sets the pending bit of an external interrupt. IRQn Interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE void NVIC_ClearPendingIRQ(IRQn_Type IRQn)
Clear Pending Interrupt.
Clears the pending bit of an external interrupt. IRQn External interrupt number. Value cannot be negative.
References NVIC.
Referenced by NVIC_GetPriorityGrouping.
__STATIC_INLINE uint32_t NVIC_GetActive(IRQn_Type IRQn)
Get Active Interrupt.
Reads the active register in NVIC and returns the active bit. IRQn Interrupt number. 0 Interrupt status is not active. 1 Interrupt status is active.
References NVIC, NVIC_SetPriority, SCB, __NVIC_PRIO_BITS, NVIC_GetPriority.
__STATIC_INLINE void NVIC_SetPriority(IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
Sets the priority of an interrupt. The priority cannot be set for every core interrupt. IRQn Interrupt number. priority Priority to set.
References SCB, _SHP_IDX, _BIT_SHIFT, __NVIC_PRIO_BITS, NVIC, _IP_IDX.
Referenced by SysTick_Config, NVIC_GetActive, NVIC_DecodePriority, SCB_CleanInvalidateDCache_by_Addr.
__STATIC_INLINE uint32_t NVIC_GetPriority(IRQn_Type IRQn)
Get Interrupt Priority.
Reads the priority of an interrupt. The interrupt number can be positive to specify an external (device specific) interrupt, or negative to specify an internal (core) interrupt. IRQn Interrupt number. Interrupt Priority. Value is aligned automatically to the implemented priority bits of the microcontroller.
References SCB, _SHP_IDX, _BIT_SHIFT, __NVIC_PRIO_BITS, NVIC, _IP_IDX.
Referenced by NVIC_GetActive.
__STATIC_INLINE uint32_t NVIC_EncodePriority(uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)
Encode Priority.
Encodes the priority for an interrupt with the given priority group, preemptive priority value, and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set. PriorityGroup Used priority group. PreemptPriority Preemptive priority value (starting from 0). SubPriority Subpriority value (starting from 0). Encoded priority. Value can be used in the function NVIC_SetPriority().
References __NVIC_PRIO_BITS.
__STATIC_INLINE void NVIC_DecodePriority(uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)
Decode Priority.
Decodes an interrupt priority value with a given priority group to preemptive priority value and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS) the smallest possible priority group is set. Priority Priority value, which can be retrieved with the function NVIC_GetPriority(). PriorityGroup Used priority group. pPreemptPriority Preemptive priority value (starting from 0). pSubPriority Subpriority value (starting from 0).
References __NVIC_PRIO_BITS, NVIC_SystemReset, __DSB, SCB, SCB_AIRCR_VECTKEY_Pos, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_SYSRESETREQ_Msk, __NOP, SysTick_Config, SysTick_LOAD_RELOAD_Msk, SysTick, NVIC_SetPriority, SysTick_IRQn, SysTick_CTRL_CLKSOURCE_Msk, SysTick_CTRL_TICKINT_Msk, SysTick_CTRL_ENABLE_Msk, ITM_RxBuffer.
__STATIC_INLINE void NVIC_SystemReset(void)
System Reset.
Initiates a system reset request to reset the MCU.
References __DSB, SCB, SCB_AIRCR_VECTKEY_Pos, SCB_AIRCR_SYSRESETREQ_Msk, __NOP.
Referenced by NVIC_DecodePriority, __attribute__.
__STATIC_INLINE uint32_t SysTick_Config(uint32_t ticks)
System Tick Configuration.
Initializes the System Timer and its interrupt, and starts the System Tick Timer. Counter is in free running mode to generate periodic interrupts. ticks Number of ticks between two interrupts. 0 Function succeeded. 1 Function failed. When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included. In this case, the file device.h must contain a vendor-specific implementation of this function.
References SysTick_LOAD_RELOAD_Msk, SysTick, NVIC_SetPriority, SysTick_IRQn, __NVIC_PRIO_BITS, SysTick_CTRL_CLKSOURCE_Msk, SysTick_CTRL_TICKINT_Msk, SysTick_CTRL_ENABLE_Msk.
Referenced by Timer::start, NVIC_DecodePriority, SCB_CleanInvalidateDCache_by_Addr.
__STATIC_INLINE uint32_t ITM_SendChar(uint32_t ch)
ITM Send Character.
Transmits a character via the ITM channel 0, and Just returns when no debugger is connected that has booked the output. Is blocking when a debugger is connected, but the previous character sent has not been transmitted. ch Character to transmit. Character to transmit.
References ITM, ITM_TCR_ITMENA_Msk, __NOP.
__STATIC_INLINE int32_t ITM_ReceiveChar(void)
ITM Receive Character.
Inputs a character via the external variable ITM_RxBuffer. Received character. -1 No character pending.
References ITM_RXBUFFER_EMPTY, ITM_RxBuffer.
__STATIC_INLINE int32_t ITM_CheckChar(void)
ITM Check Character.
Checks whether a character is pending for reading in the variable ITM_RxBuffer. 0 No character available. 1 Character available.
References ITM_RXBUFFER_EMPTY.