CMSIS_Core_SysTickFunctions
__STATIC_INLINE uint32_t SysTick_Config(uint32_t ticks)
System Tick Configuration.
Initializes the System Timer and its interrupt, and starts the System Tick Timer. Counter is in free running mode to generate periodic interrupts. ticks Number of ticks between two interrupts. 0 Function succeeded. 1 Function failed. When the variable __Vendor_SysTickConfig is set to 1, then the function SysTick_Config is not included. In this case, the file device.h must contain a vendor-specific implementation of this function.
References SysTick_LOAD_RELOAD_Msk, SysTick, NVIC_SetPriority, SysTick_IRQn, __NVIC_PRIO_BITS, SysTick_CTRL_CLKSOURCE_Msk, SysTick_CTRL_TICKINT_Msk, SysTick_CTRL_ENABLE_Msk.
Referenced by Timer::start, NVIC_DecodePriority, SCB_CleanInvalidateDCache_by_Addr.