stm32f10x_tim.h
IS_TIM_ALL_PERIPH
IS_TIM_LIST1_PERIPH
IS_TIM_LIST2_PERIPH
IS_TIM_LIST3_PERIPH
IS_TIM_LIST4_PERIPH
IS_TIM_LIST5_PERIPH
IS_TIM_LIST6_PERIPH
IS_TIM_LIST7_PERIPH
IS_TIM_LIST8_PERIPH
IS_TIM_LIST9_PERIPH
TIM_OCMode_Timing
TIM_OCMode_Active
TIM_OCMode_Inactive
TIM_OCMode_Toggle
TIM_OCMode_PWM1
TIM_OCMode_PWM2
IS_TIM_OC_MODE
IS_TIM_OCM
TIM_OPMode_Single
TIM_OPMode_Repetitive
IS_TIM_OPM_MODE
TIM_Channel_1
TIM_Channel_2
TIM_Channel_3
TIM_Channel_4
IS_TIM_CHANNEL
IS_TIM_PWMI_CHANNEL
IS_TIM_COMPLEMENTARY_CHANNEL
TIM_CKD_DIV1
TIM_CKD_DIV2
TIM_CKD_DIV4
IS_TIM_CKD_DIV
TIM_CounterMode_Up
TIM_CounterMode_Down
TIM_CounterMode_CenterAligned1
TIM_CounterMode_CenterAligned2
TIM_CounterMode_CenterAligned3
IS_TIM_COUNTER_MODE
TIM_OCPolarity_High
TIM_OCPolarity_Low
IS_TIM_OC_POLARITY
TIM_OCNPolarity_High
TIM_OCNPolarity_Low
IS_TIM_OCN_POLARITY
TIM_OutputState_Disable
TIM_OutputState_Enable
IS_TIM_OUTPUT_STATE
TIM_OutputNState_Disable
TIM_OutputNState_Enable
IS_TIM_OUTPUTN_STATE
TIM_CCx_Enable
TIM_CCx_Disable
IS_TIM_CCX
TIM_CCxN_Enable
TIM_CCxN_Disable
IS_TIM_CCXN
TIM_Break_Enable
TIM_Break_Disable
IS_TIM_BREAK_STATE
TIM_BreakPolarity_Low
TIM_BreakPolarity_High
IS_TIM_BREAK_POLARITY
TIM_AutomaticOutput_Enable
TIM_AutomaticOutput_Disable
IS_TIM_AUTOMATIC_OUTPUT_STATE
TIM_LOCKLevel_OFF
TIM_LOCKLevel_1
TIM_LOCKLevel_2
TIM_LOCKLevel_3
IS_TIM_LOCK_LEVEL
TIM_OSSIState_Enable
TIM_OSSIState_Disable
IS_TIM_OSSI_STATE
TIM_OSSRState_Enable
TIM_OSSRState_Disable
IS_TIM_OSSR_STATE
TIM_OCIdleState_Set
TIM_OCIdleState_Reset
IS_TIM_OCIDLE_STATE
TIM_OCNIdleState_Set
TIM_OCNIdleState_Reset
IS_TIM_OCNIDLE_STATE
TIM_ICPolarity_Rising
TIM_ICPolarity_Falling
TIM_ICPolarity_BothEdge
IS_TIM_IC_POLARITY
IS_TIM_IC_POLARITY_LITE
TIM_ICSelection_DirectTI
TIM Input 1, 2, 3 or 4 is selected to be connected to IC1, IC2, IC3 or IC4, respectively
TIM_ICSelection_IndirectTI
TIM Input 1, 2, 3 or 4 is selected to be connected to IC2, IC1, IC4 or IC3, respectively.
TIM_ICSelection_TRC
TIM Input 1, 2, 3 or 4 is selected to be connected to TRC.
IS_TIM_IC_SELECTION
TIM_ICPSC_DIV1
Capture performed each time an edge is detected on the capture input.
TIM_ICPSC_DIV2
Capture performed once every 2 events.
TIM_ICPSC_DIV4
Capture performed once every 4 events.
TIM_ICPSC_DIV8
Capture performed once every 8 events.
IS_TIM_IC_PRESCALER
TIM_IT_Update
TIM_IT_CC1
TIM_IT_CC2
TIM_IT_CC3
TIM_IT_CC4
TIM_IT_COM
TIM_IT_Trigger
TIM_IT_Break
IS_TIM_IT
IS_TIM_GET_IT
TIM_DMABase_CR1
TIM_DMABase_CR2
TIM_DMABase_SMCR
TIM_DMABase_DIER
TIM_DMABase_SR
TIM_DMABase_EGR
TIM_DMABase_CCMR1
TIM_DMABase_CCMR2
TIM_DMABase_CCER
TIM_DMABase_CNT
TIM_DMABase_PSC
TIM_DMABase_ARR
TIM_DMABase_RCR
TIM_DMABase_CCR1
TIM_DMABase_CCR2
TIM_DMABase_CCR3
TIM_DMABase_CCR4
TIM_DMABase_BDTR
TIM_DMABase_DCR
IS_TIM_DMA_BASE
TIM_DMABurstLength_1Transfer
TIM_DMABurstLength_2Transfers
TIM_DMABurstLength_3Transfers
TIM_DMABurstLength_4Transfers
TIM_DMABurstLength_5Transfers
TIM_DMABurstLength_6Transfers
TIM_DMABurstLength_7Transfers
TIM_DMABurstLength_8Transfers
TIM_DMABurstLength_9Transfers
TIM_DMABurstLength_10Transfers
TIM_DMABurstLength_11Transfers
TIM_DMABurstLength_12Transfers
TIM_DMABurstLength_13Transfers
TIM_DMABurstLength_14Transfers
TIM_DMABurstLength_15Transfers
TIM_DMABurstLength_16Transfers
TIM_DMABurstLength_17Transfers
TIM_DMABurstLength_18Transfers
IS_TIM_DMA_LENGTH
TIM_DMA_Update
TIM_DMA_CC1
TIM_DMA_CC2
TIM_DMA_CC3
TIM_DMA_CC4
TIM_DMA_COM
TIM_DMA_Trigger
IS_TIM_DMA_SOURCE
TIM_ExtTRGPSC_OFF
TIM_ExtTRGPSC_DIV2
TIM_ExtTRGPSC_DIV4
TIM_ExtTRGPSC_DIV8
IS_TIM_EXT_PRESCALER
TIM_TS_ITR0
TIM_TS_ITR1
TIM_TS_ITR2
TIM_TS_ITR3
TIM_TS_TI1F_ED
TIM_TS_TI1FP1
TIM_TS_TI2FP2
TIM_TS_ETRF
IS_TIM_TRIGGER_SELECTION
IS_TIM_INTERNAL_TRIGGER_SELECTION
TIM_TIxExternalCLK1Source_TI1
TIM_TIxExternalCLK1Source_TI2
TIM_TIxExternalCLK1Source_TI1ED
IS_TIM_TIXCLK_SOURCE
TIM_ExtTRGPolarity_Inverted
TIM_ExtTRGPolarity_NonInverted
IS_TIM_EXT_POLARITY
TIM_PSCReloadMode_Update
TIM_PSCReloadMode_Immediate
IS_TIM_PRESCALER_RELOAD
TIM_ForcedAction_Active
TIM_ForcedAction_InActive
IS_TIM_FORCED_ACTION
TIM_EncoderMode_TI1
TIM_EncoderMode_TI2
TIM_EncoderMode_TI12
IS_TIM_ENCODER_MODE
TIM_EventSource_Update
TIM_EventSource_CC1
TIM_EventSource_CC2
TIM_EventSource_CC3
TIM_EventSource_CC4
TIM_EventSource_COM
TIM_EventSource_Trigger
TIM_EventSource_Break
IS_TIM_EVENT_SOURCE
TIM_UpdateSource_Global
Source of update is the counter overflow/underflow or the setting of UG bit, or an update generation through the slave mode controller.
TIM_UpdateSource_Regular
Source of update is counter overflow/underflow.
IS_TIM_UPDATE_SOURCE
TIM_OCPreload_Enable
TIM_OCPreload_Disable
IS_TIM_OCPRELOAD_STATE
TIM_OCFast_Enable
TIM_OCFast_Disable
IS_TIM_OCFAST_STATE
TIM_OCClear_Enable
TIM_OCClear_Disable
IS_TIM_OCCLEAR_STATE
TIM_TRGOSource_Reset
TIM_TRGOSource_Enable
TIM_TRGOSource_Update
TIM_TRGOSource_OC1
TIM_TRGOSource_OC1Ref
TIM_TRGOSource_OC2Ref
TIM_TRGOSource_OC3Ref
TIM_TRGOSource_OC4Ref
IS_TIM_TRGO_SOURCE
TIM_SlaveMode_Reset
TIM_SlaveMode_Gated
TIM_SlaveMode_Trigger
TIM_SlaveMode_External1
IS_TIM_SLAVE_MODE
TIM_MasterSlaveMode_Enable
TIM_MasterSlaveMode_Disable
IS_TIM_MSM_STATE
TIM_FLAG_Update
TIM_FLAG_CC1
TIM_FLAG_CC2
TIM_FLAG_CC3
TIM_FLAG_CC4
TIM_FLAG_COM
TIM_FLAG_Trigger
TIM_FLAG_Break
TIM_FLAG_CC1OF
TIM_FLAG_CC2OF
TIM_FLAG_CC3OF
TIM_FLAG_CC4OF
IS_TIM_GET_FLAG
IS_TIM_CLEAR_FLAG
IS_TIM_IC_FILTER
IS_TIM_EXT_FILTER
TIM_DMABurstLength_1Byte
TIM_DMABurstLength_2Bytes
TIM_DMABurstLength_3Bytes
TIM_DMABurstLength_4Bytes
TIM_DMABurstLength_5Bytes
TIM_DMABurstLength_6Bytes
TIM_DMABurstLength_7Bytes
TIM_DMABurstLength_8Bytes
TIM_DMABurstLength_9Bytes
TIM_DMABurstLength_10Bytes
TIM_DMABurstLength_11Bytes
TIM_DMABurstLength_12Bytes
TIM_DMABurstLength_13Bytes
TIM_DMABurstLength_14Bytes
TIM_DMABurstLength_15Bytes
TIM_DMABurstLength_16Bytes
TIM_DMABurstLength_17Bytes
TIM_DMABurstLength_18Bytes
void TIM_DeInit(TIM_TypeDef *TIMx)
Deinitializes the TIMx peripheral registers to their default reset values.
TIMx where x can be 1 to 17 to select the TIM peripheral. None
References assert_param, IS_TIM_ALL_PERIPH, TIM1, RCC_APB2PeriphResetCmd, RCC_APB2Periph_TIM1, ENABLE, DISABLE, TIM2, RCC_APB1PeriphResetCmd, RCC_APB1Periph_TIM2, TIM3, RCC_APB1Periph_TIM3, TIM4, RCC_APB1Periph_TIM4, TIM5, RCC_APB1Periph_TIM5, TIM6, RCC_APB1Periph_TIM6, TIM7, RCC_APB1Periph_TIM7, TIM8, RCC_APB2Periph_TIM8, TIM9, RCC_APB2Periph_TIM9, TIM10, RCC_APB2Periph_TIM10, TIM11, RCC_APB2Periph_TIM11, TIM12, RCC_APB1Periph_TIM12, TIM13, RCC_APB1Periph_TIM13, TIM14, RCC_APB1Periph_TIM14, TIM15, RCC_APB2Periph_TIM15, TIM16, RCC_APB2Periph_TIM16, TIM17, RCC_APB2Periph_TIM17.
void TIM_TimeBaseInit(TIM_TypeDef *TIMx, TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Initializes the TIMx Time Base Unit peripheral according to the specified parameters in the TIM_TimeBaseInitStruct.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_TimeBaseInitStruct pointer to a TIM_TimeBaseInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_COUNTER_MODE, TIM_TimeBaseInitTypeDef::TIM_CounterMode, IS_TIM_CKD_DIV, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_TypeDef::CR1, TIM1, TIM8, TIM2, TIM3, TIM4, TIM5, TIM_CR1_DIR, TIM_CR1_CMS, TIM6, TIM7, TIM_CR1_CKD, TIM_TypeDef::ARR, TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TypeDef::PSC, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM15, TIM16, TIM17, TIM_TypeDef::RCR, TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter, TIM_TypeDef::EGR, TIM_PSCReloadMode_Immediate.
void TIM_OC1Init(TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel1 according to the specified parameters in the TIM_OCInitStruct.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_OC_MODE, TIM_OCInitTypeDef::TIM_OCMode, IS_TIM_OUTPUT_STATE, TIM_OCInitTypeDef::TIM_OutputState, IS_TIM_OC_POLARITY, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_TypeDef::CCER, TIM_CCER_CC1E, TIM_TypeDef::CR2, TIM_TypeDef::CCMR1, TIM_CCMR1_OC1M, TIM_CCMR1_CC1S, TIM_CCER_CC1P, TIM1, TIM8, TIM15, TIM16, TIM17, IS_TIM_OUTPUTN_STATE, TIM_OCInitTypeDef::TIM_OutputNState, IS_TIM_OCN_POLARITY, TIM_OCInitTypeDef::TIM_OCNPolarity, IS_TIM_OCNIDLE_STATE, TIM_OCInitTypeDef::TIM_OCNIdleState, IS_TIM_OCIDLE_STATE, TIM_OCInitTypeDef::TIM_OCIdleState, TIM_CCER_CC1NP, TIM_CCER_CC1NE, TIM_CR2_OIS1, TIM_CR2_OIS1N, TIM_TypeDef::CCR1, TIM_OCInitTypeDef::TIM_Pulse.
void TIM_OC2Init(TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel2 according to the specified parameters in the TIM_OCInitStruct.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_OC_MODE, TIM_OCInitTypeDef::TIM_OCMode, IS_TIM_OUTPUT_STATE, TIM_OCInitTypeDef::TIM_OutputState, IS_TIM_OC_POLARITY, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_TypeDef::CCER, TIM_CCER_CC2E, TIM_TypeDef::CR2, TIM_TypeDef::CCMR1, TIM_CCMR1_OC2M, TIM_CCMR1_CC2S, TIM_CCER_CC2P, TIM1, TIM8, IS_TIM_OUTPUTN_STATE, TIM_OCInitTypeDef::TIM_OutputNState, IS_TIM_OCN_POLARITY, TIM_OCInitTypeDef::TIM_OCNPolarity, IS_TIM_OCNIDLE_STATE, TIM_OCInitTypeDef::TIM_OCNIdleState, IS_TIM_OCIDLE_STATE, TIM_OCInitTypeDef::TIM_OCIdleState, TIM_CCER_CC2NP, TIM_CCER_CC2NE, TIM_CR2_OIS2, TIM_CR2_OIS2N, TIM_TypeDef::CCR2, TIM_OCInitTypeDef::TIM_Pulse.
void TIM_OC3Init(TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel3 according to the specified parameters in the TIM_OCInitStruct.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OC_MODE, TIM_OCInitTypeDef::TIM_OCMode, IS_TIM_OUTPUT_STATE, TIM_OCInitTypeDef::TIM_OutputState, IS_TIM_OC_POLARITY, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_TypeDef::CCER, TIM_CCER_CC3E, TIM_TypeDef::CR2, TIM_TypeDef::CCMR2, TIM_CCMR2_OC3M, TIM_CCMR2_CC3S, TIM_CCER_CC3P, TIM1, TIM8, IS_TIM_OUTPUTN_STATE, TIM_OCInitTypeDef::TIM_OutputNState, IS_TIM_OCN_POLARITY, TIM_OCInitTypeDef::TIM_OCNPolarity, IS_TIM_OCNIDLE_STATE, TIM_OCInitTypeDef::TIM_OCNIdleState, IS_TIM_OCIDLE_STATE, TIM_OCInitTypeDef::TIM_OCIdleState, TIM_CCER_CC3NP, TIM_CCER_CC3NE, TIM_CR2_OIS3, TIM_CR2_OIS3N, TIM_TypeDef::CCR3, TIM_OCInitTypeDef::TIM_Pulse.
void TIM_OC4Init(TIM_TypeDef *TIMx, TIM_OCInitTypeDef *TIM_OCInitStruct)
Initializes the TIMx Channel4 according to the specified parameters in the TIM_OCInitStruct.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCInitStruct pointer to a TIM_OCInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OC_MODE, TIM_OCInitTypeDef::TIM_OCMode, IS_TIM_OUTPUT_STATE, TIM_OCInitTypeDef::TIM_OutputState, IS_TIM_OC_POLARITY, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_TypeDef::CCER, TIM_CCER_CC4E, TIM_TypeDef::CR2, TIM_TypeDef::CCMR2, TIM_CCMR2_OC4M, TIM_CCMR2_CC4S, TIM_CCER_CC4P, TIM1, TIM8, IS_TIM_OCIDLE_STATE, TIM_OCInitTypeDef::TIM_OCIdleState, TIM_CR2_OIS4, TIM_TypeDef::CCR4, TIM_OCInitTypeDef::TIM_Pulse.
void TIM_ICInit(TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Initializes the TIM peripheral according to the specified parameters in the TIM_ICInitStruct.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References assert_param, IS_TIM_CHANNEL, TIM_ICInitTypeDef::TIM_Channel, IS_TIM_IC_SELECTION, TIM_ICInitTypeDef::TIM_ICSelection, IS_TIM_IC_PRESCALER, TIM_ICInitTypeDef::TIM_ICPrescaler, IS_TIM_IC_FILTER, TIM_ICInitTypeDef::TIM_ICFilter, TIM1, TIM8, TIM2, TIM3, TIM4, TIM5, IS_TIM_IC_POLARITY, TIM_ICInitTypeDef::TIM_ICPolarity, IS_TIM_IC_POLARITY_LITE, TIM_Channel_1, IS_TIM_LIST8_PERIPH.
void TIM_PWMIConfig(TIM_TypeDef *TIMx, TIM_ICInitTypeDef *TIM_ICInitStruct)
Configures the TIM peripheral according to the specified parameters in the TIM_ICInitStruct to measure an external PWM signal.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure that contains the configuration information for the specified TIM peripheral. None
References TIM_ICPolarity_Rising, TIM_ICSelection_DirectTI, assert_param, IS_TIM_LIST6_PERIPH, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICPolarity_Falling, TIM_ICInitTypeDef::TIM_ICSelection, TIM_ICSelection_IndirectTI, TIM_ICInitTypeDef::TIM_Channel, TIM_Channel_1.
void TIM_BDTRConfig(TIM_TypeDef *TIMx, TIM_BDTRInitTypeDef *TIM_BDTRInitStruct)
Configures the: Break feature, dead time, Lock level, the OSSI, the OSSR State and the AOE(automatic output enable).
TIMx where x can be 1 or 8 to select the TIM TIM_BDTRInitStruct pointer to a TIM_BDTRInitTypeDef structure that contains the BDTR Register configuration information for the TIM peripheral. None
References assert_param, IS_TIM_LIST2_PERIPH, IS_TIM_OSSR_STATE, TIM_BDTRInitTypeDef::TIM_OSSRState, IS_TIM_OSSI_STATE, TIM_BDTRInitTypeDef::TIM_OSSIState, IS_TIM_LOCK_LEVEL, TIM_BDTRInitTypeDef::TIM_LOCKLevel, IS_TIM_BREAK_STATE, TIM_BDTRInitTypeDef::TIM_Break, IS_TIM_BREAK_POLARITY, TIM_BDTRInitTypeDef::TIM_BreakPolarity, IS_TIM_AUTOMATIC_OUTPUT_STATE, TIM_BDTRInitTypeDef::TIM_AutomaticOutput, TIM_TypeDef::BDTR, TIM_BDTRInitTypeDef::TIM_DeadTime.
void TIM_TimeBaseStructInit(TIM_TimeBaseInitTypeDef *TIM_TimeBaseInitStruct)
Fills each TIM_TimeBaseInitStruct member with its default value.
TIM_TimeBaseInitStruct : pointer to a TIM_TimeBaseInitTypeDef structure which will be initialized. None
References TIM_TimeBaseInitTypeDef::TIM_Period, TIM_TimeBaseInitTypeDef::TIM_Prescaler, TIM_TimeBaseInitTypeDef::TIM_ClockDivision, TIM_CKD_DIV1, TIM_TimeBaseInitTypeDef::TIM_CounterMode, TIM_CounterMode_Up, TIM_TimeBaseInitTypeDef::TIM_RepetitionCounter.
void TIM_OCStructInit(TIM_OCInitTypeDef *TIM_OCInitStruct)
Fills each TIM_OCInitStruct member with its default value.
TIM_OCInitStruct : pointer to a TIM_OCInitTypeDef structure which will be initialized. None
References TIM_OCInitTypeDef::TIM_OCMode, TIM_OCMode_Timing, TIM_OCInitTypeDef::TIM_OutputState, TIM_OutputState_Disable, TIM_OCInitTypeDef::TIM_OutputNState, TIM_OutputNState_Disable, TIM_OCInitTypeDef::TIM_Pulse, TIM_OCInitTypeDef::TIM_OCPolarity, TIM_OCPolarity_High, TIM_OCInitTypeDef::TIM_OCNPolarity, TIM_OCInitTypeDef::TIM_OCIdleState, TIM_OCIdleState_Reset, TIM_OCInitTypeDef::TIM_OCNIdleState, TIM_OCNIdleState_Reset.
void TIM_ICStructInit(TIM_ICInitTypeDef *TIM_ICInitStruct)
Fills each TIM_ICInitStruct member with its default value.
TIM_ICInitStruct pointer to a TIM_ICInitTypeDef structure which will be initialized. None
References TIM_ICInitTypeDef::TIM_Channel, TIM_Channel_1, TIM_ICInitTypeDef::TIM_ICPolarity, TIM_ICPolarity_Rising, TIM_ICInitTypeDef::TIM_ICSelection, TIM_ICSelection_DirectTI, TIM_ICInitTypeDef::TIM_ICPrescaler, TIM_ICPSC_DIV1, TIM_ICInitTypeDef::TIM_ICFilter.
void TIM_BDTRStructInit(TIM_BDTRInitTypeDef *TIM_BDTRInitStruct)
Fills each TIM_BDTRInitStruct member with its default value.
TIM_BDTRInitStruct pointer to a TIM_BDTRInitTypeDef structure which will be initialized. None
References TIM_BDTRInitTypeDef::TIM_OSSRState, TIM_OSSRState_Disable, TIM_BDTRInitTypeDef::TIM_OSSIState, TIM_OSSIState_Disable, TIM_BDTRInitTypeDef::TIM_LOCKLevel, TIM_LOCKLevel_OFF, TIM_BDTRInitTypeDef::TIM_DeadTime, TIM_BDTRInitTypeDef::TIM_Break, TIM_Break_Disable, TIM_BDTRInitTypeDef::TIM_BreakPolarity, TIM_BreakPolarity_Low, TIM_BDTRInitTypeDef::TIM_AutomaticOutput, TIM_AutomaticOutput_Disable.
void TIM_Cmd(TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the specified TIM peripheral.
TIMx where x can be 1 to 17 to select the TIMx peripheral. NewState new state of the TIMx peripheral. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_ALL_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR1, TIM_CR1_CEN.
void TIM_CtrlPWMOutputs(TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the TIM peripheral Main Outputs.
TIMx where x can be 1, 8, 15, 16 or 17 to select the TIMx peripheral. NewState new state of the TIM peripheral Main Outputs. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST2_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::BDTR, TIM_BDTR_MOE.
void TIM_ITConfig(TIM_TypeDef *TIMx, uint16_t TIM_IT, FunctionalState NewState)
Enables or disables the specified TIM interrupts.
TIMx where x can be 1 to 17 to select the TIMx peripheral. TIM_IT specifies the TIM interrupts sources to be enabled or disabled. This parameter can be any combination of the following values: TIM_IT_Update: TIM update Interrupt source TIM_IT_CC1: TIM Capture Compare 1 Interrupt source TIM_IT_CC2: TIM Capture Compare 2 Interrupt source TIM_IT_CC3: TIM Capture Compare 3 Interrupt source TIM_IT_CC4: TIM Capture Compare 4 Interrupt source TIM_IT_COM: TIM Commutation Interrupt source TIM_IT_Trigger: TIM Trigger Interrupt source TIM_IT_Break: TIM Break Interrupt source TIM6 and TIM7 can only generate an update interrupt.TIM9, TIM12 and TIM15 can have only TIM_IT_Update, TIM_IT_CC1, TIM_IT_CC2 or TIM_IT_Trigger.TIM10, TIM11, TIM13, TIM14, TIM16 and TIM17 can have TIM_IT_Update or TIM_IT_CC1.TIM_IT_Break is used only with TIM1, TIM8 and TIM15.TIM_IT_COM is used only with TIM1, TIM8, TIM15, TIM16 and TIM17. NewState new state of the TIM interrupts. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_IT, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::DIER.
void TIM_GenerateEvent(TIM_TypeDef *TIMx, uint16_t TIM_EventSource)
Configures the TIMx event to be generate by software.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_EventSource specifies the event source. This parameter can be one or more of the following values: TIM_EventSource_Update: Timer update Event source TIM_EventSource_CC1: Timer Capture Compare 1 Event source TIM_EventSource_CC2: Timer Capture Compare 2 Event source TIM_EventSource_CC3: Timer Capture Compare 3 Event source TIM_EventSource_CC4: Timer Capture Compare 4 Event source TIM_EventSource_COM: Timer COM event source TIM_EventSource_Trigger: Timer Trigger Event source TIM_EventSource_Break: Timer Break event source TIM6 and TIM7 can only generate an update event.TIM_EventSource_COM and TIM_EventSource_Break are used only with TIM1 and TIM8. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_EVENT_SOURCE, TIM_TypeDef::EGR.
void TIM_DMAConfig(TIM_TypeDef *TIMx, uint16_t TIM_DMABase, uint16_t TIM_DMABurstLength)
Configures the TIMx's DMA interface.
TIMx where x can be 1, 2, 3, 4, 5, 8, 15, 16 or 17 to select the TIM peripheral. TIM_DMABase DMA Base address. This parameter can be one of the following values: TIM_DMABase_CR, TIM_DMABase_CR2, TIM_DMABase_SMCR, TIM_DMABase_DIER, TIM1_DMABase_SR, TIM_DMABase_EGR, TIM_DMABase_CCMR1, TIM_DMABase_CCMR2, TIM_DMABase_CCER, TIM_DMABase_CNT, TIM_DMABase_PSC, TIM_DMABase_ARR, TIM_DMABase_RCR, TIM_DMABase_CCR1, TIM_DMABase_CCR2, TIM_DMABase_CCR3, TIM_DMABase_CCR4, TIM_DMABase_BDTR, TIM_DMABase_DCR. TIM_DMABurstLength DMA Burst length. This parameter can be one value between: TIM_DMABurstLength_1Transfer and TIM_DMABurstLength_18Transfers. None
References assert_param, IS_TIM_LIST4_PERIPH, IS_TIM_DMA_BASE, IS_TIM_DMA_LENGTH, TIM_TypeDef::DCR.
void TIM_DMACmd(TIM_TypeDef *TIMx, uint16_t TIM_DMASource, FunctionalState NewState)
Enables or disables the TIMx's DMA Requests.
TIMx where x can be 1, 2, 3, 4, 5, 6, 7, 8, 15, 16 or 17 to select the TIM peripheral. TIM_DMASource specifies the DMA Request sources. This parameter can be any combination of the following values: TIM_DMA_Update: TIM update Interrupt source TIM_DMA_CC1: TIM Capture Compare 1 DMA source TIM_DMA_CC2: TIM Capture Compare 2 DMA source TIM_DMA_CC3: TIM Capture Compare 3 DMA source TIM_DMA_CC4: TIM Capture Compare 4 DMA source TIM_DMA_COM: TIM Commutation DMA source TIM_DMA_Trigger: TIM Trigger DMA source NewState new state of the DMA Request sources. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST9_PERIPH, IS_TIM_DMA_SOURCE, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::DIER.
void TIM_InternalClockConfig(TIM_TypeDef *TIMx)
Configures the TIMx internal Clock.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. None
References assert_param, IS_TIM_LIST6_PERIPH, TIM_TypeDef::SMCR, TIM_SMCR_SMS.
void TIM_ITRxExternalClockConfig(TIM_TypeDef *TIMx, uint16_t TIM_InputTriggerSource)
Configures the TIMx Internal Trigger as External Clock.
TIMx where x can be 1, 2, 3, 4, 5, 9, 12 or 15 to select the TIM peripheral. TIM_ITRSource Trigger source. This parameter can be one of the following values: TIM_TS_ITR0 Internal Trigger 0 TIM_TS_ITR1 Internal Trigger 1 TIM_TS_ITR2 Internal Trigger 2 TIM_TS_ITR3 Internal Trigger 3 None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_INTERNAL_TRIGGER_SELECTION, TIM_SelectInputTrigger, TIM_TypeDef::SMCR, TIM_SlaveMode_External1.
void TIM_TIxExternalClockConfig(TIM_TypeDef *TIMx, uint16_t TIM_TIxExternalCLKSource, uint16_t TIM_ICPolarity, uint16_t ICFilter)
Configures the TIMx Trigger as External Clock.
TIMx where x can be 1, 2, 3, 4, 5, 9, 12 or 15 to select the TIM peripheral. TIM_TIxExternalCLKSource Trigger source. This parameter can be one of the following values: TIM_TIxExternalCLK1Source_TI1ED: TI1 Edge Detector TIM_TIxExternalCLK1Source_TI1: Filtered Timer Input 1 TIM_TIxExternalCLK1Source_TI2: Filtered Timer Input 2 TIM_ICPolarity specifies the TIx Polarity. This parameter can be one of the following values: TIM_ICPolarity_Rising TIM_ICPolarity_Falling ICFilter : specifies the filter value. This parameter must be a value between 0x0 and 0xF. None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_TIXCLK_SOURCE, IS_TIM_IC_POLARITY, IS_TIM_IC_FILTER, TIM_TIxExternalCLK1Source_TI2.
void TIM_ETRClockMode1Config(TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode1.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values: TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF. TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2. TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4. TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8. TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values: TIM_ExtTRGPolarity_Inverted: active low or falling edge active. TIM_ExtTRGPolarity_NonInverted: active high or rising edge active. ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_EXT_PRESCALER, IS_TIM_EXT_POLARITY, IS_TIM_EXT_FILTER, TIM_ETRConfig, TIM_TypeDef::SMCR, TIM_SMCR_SMS, TIM_SlaveMode_External1, TIM_SMCR_TS, TIM_TS_ETRF.
void TIM_ETRClockMode2Config(TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the External clock Mode2.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values: TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF. TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2. TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4. TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8. TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values: TIM_ExtTRGPolarity_Inverted: active low or falling edge active. TIM_ExtTRGPolarity_NonInverted: active high or rising edge active. ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_EXT_PRESCALER, IS_TIM_EXT_POLARITY, IS_TIM_EXT_FILTER, TIM_ETRConfig, TIM_TypeDef::SMCR, TIM_SMCR_ECE.
void TIM_ETRConfig(TIM_TypeDef *TIMx, uint16_t TIM_ExtTRGPrescaler, uint16_t TIM_ExtTRGPolarity, uint16_t ExtTRGFilter)
Configures the TIMx External Trigger (ETR).
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ExtTRGPrescaler The external Trigger Prescaler. This parameter can be one of the following values: TIM_ExtTRGPSC_OFF: ETRP Prescaler OFF. TIM_ExtTRGPSC_DIV2: ETRP frequency divided by 2. TIM_ExtTRGPSC_DIV4: ETRP frequency divided by 4. TIM_ExtTRGPSC_DIV8: ETRP frequency divided by 8. TIM_ExtTRGPolarity The external Trigger Polarity. This parameter can be one of the following values: TIM_ExtTRGPolarity_Inverted: active low or falling edge active. TIM_ExtTRGPolarity_NonInverted: active high or rising edge active. ExtTRGFilter External Trigger Filter. This parameter must be a value between 0x00 and 0x0F None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_EXT_PRESCALER, IS_TIM_EXT_POLARITY, IS_TIM_EXT_FILTER, TIM_TypeDef::SMCR, SMCR_ETR_Mask.
Referenced by TIM_ETRClockMode1Config, TIM_ETRClockMode2Config.
void TIM_PrescalerConfig(TIM_TypeDef *TIMx, uint16_t Prescaler, uint16_t TIM_PSCReloadMode)
Configures the TIMx Prescaler.
TIMx where x can be 1 to 17 to select the TIM peripheral. Prescaler specifies the Prescaler Register value TIM_PSCReloadMode specifies the TIM Prescaler Reload mode This parameter can be one of the following values: TIM_PSCReloadMode_Update: The Prescaler is loaded at the update event. TIM_PSCReloadMode_Immediate: The Prescaler is loaded immediately. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_PRESCALER_RELOAD, TIM_TypeDef::PSC, TIM_TypeDef::EGR.
void TIM_CounterModeConfig(TIM_TypeDef *TIMx, uint16_t TIM_CounterMode)
Specifies the TIMx Counter Mode to be used.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_CounterMode specifies the Counter Mode to be used This parameter can be one of the following values: TIM_CounterMode_Up: TIM Up Counting Mode TIM_CounterMode_Down: TIM Down Counting Mode TIM_CounterMode_CenterAligned1: TIM Center Aligned Mode1 TIM_CounterMode_CenterAligned2: TIM Center Aligned Mode2 TIM_CounterMode_CenterAligned3: TIM Center Aligned Mode3 None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_COUNTER_MODE, TIM_TypeDef::CR1, TIM_CR1_DIR, TIM_CR1_CMS.
void TIM_SelectInputTrigger(TIM_TypeDef *TIMx, uint16_t TIM_InputTriggerSource)
Selects the Input Trigger source.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_InputTriggerSource The Input Trigger source. This parameter can be one of the following values: TIM_TS_ITR0: Internal Trigger 0 TIM_TS_ITR1: Internal Trigger 1 TIM_TS_ITR2: Internal Trigger 2 TIM_TS_ITR3: Internal Trigger 3 TIM_TS_TI1F_ED: TI1 Edge Detector TIM_TS_TI1FP1: Filtered Timer Input 1 TIM_TS_TI2FP2: Filtered Timer Input 2 TIM_TS_ETRF: External Trigger input None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_TRIGGER_SELECTION, TIM_TypeDef::SMCR, TIM_SMCR_TS.
Referenced by TIM_ITRxExternalClockConfig.
void TIM_EncoderInterfaceConfig(TIM_TypeDef *TIMx, uint16_t TIM_EncoderMode, uint16_t TIM_IC1Polarity, uint16_t TIM_IC2Polarity)
Configures the TIMx Encoder Interface.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_EncoderMode specifies the TIMx Encoder Mode. This parameter can be one of the following values: TIM_EncoderMode_TI1: Counter counts on TI1FP1 edge depending on TI2FP2 level. TIM_EncoderMode_TI2: Counter counts on TI2FP2 edge depending on TI1FP1 level. TIM_EncoderMode_TI12: Counter counts on both TI1FP1 and TI2FP2 edges depending on the level of the other input. TIM_IC1Polarity specifies the IC1 Polarity This parameter can be one of the following values: TIM_ICPolarity_Falling: IC Falling edge. TIM_ICPolarity_Rising: IC Rising edge. TIM_IC2Polarity specifies the IC2 Polarity This parameter can be one of the following values: TIM_ICPolarity_Falling: IC Falling edge. TIM_ICPolarity_Rising: IC Rising edge. None
References assert_param, IS_TIM_LIST5_PERIPH, IS_TIM_ENCODER_MODE, IS_TIM_IC_POLARITY, TIM_TypeDef::SMCR, TIM_TypeDef::CCMR1, TIM_TypeDef::CCER, TIM_SMCR_SMS, TIM_CCMR1_CC1S, TIM_CCMR1_CC2S, TIM_CCMR1_CC1S_0, TIM_CCMR1_CC2S_0, TIM_CCER_CC1P, TIM_CCER_CC2P.
void TIM_ForcedOC1Config(TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 1 waveform to active or inactive level.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values: TIM_ForcedAction_Active: Force active level on OC1REF TIM_ForcedAction_InActive: Force inactive level on OC1REF. None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_FORCED_ACTION, TIM_TypeDef::CCMR1, TIM_CCMR1_OC1M.
void TIM_ForcedOC2Config(TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 2 waveform to active or inactive level.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values: TIM_ForcedAction_Active: Force active level on OC2REF TIM_ForcedAction_InActive: Force inactive level on OC2REF. None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_FORCED_ACTION, TIM_TypeDef::CCMR1, TIM_CCMR1_OC2M.
void TIM_ForcedOC3Config(TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 3 waveform to active or inactive level.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values: TIM_ForcedAction_Active: Force active level on OC3REF TIM_ForcedAction_InActive: Force inactive level on OC3REF. None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_FORCED_ACTION, TIM_TypeDef::CCMR2, TIM_CCMR2_OC3M.
void TIM_ForcedOC4Config(TIM_TypeDef *TIMx, uint16_t TIM_ForcedAction)
Forces the TIMx output 4 waveform to active or inactive level.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ForcedAction specifies the forced Action to be set to the output waveform. This parameter can be one of the following values: TIM_ForcedAction_Active: Force active level on OC4REF TIM_ForcedAction_InActive: Force inactive level on OC4REF. None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_FORCED_ACTION, TIM_TypeDef::CCMR2, TIM_CCMR2_OC4M.
void TIM_ARRPreloadConfig(TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables TIMx peripheral Preload register on ARR.
TIMx where x can be 1 to 17 to select the TIM peripheral. NewState new state of the TIMx peripheral Preload register This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_ALL_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR1, TIM_CR1_ARPE.
void TIM_SelectCOM(TIM_TypeDef *TIMx, FunctionalState NewState)
Selects the TIM peripheral Commutation event.
TIMx where x can be 1, 8, 15, 16 or 17 to select the TIMx peripheral NewState new state of the Commutation event. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST2_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR2, TIM_CR2_CCUS.
void TIM_SelectCCDMA(TIM_TypeDef *TIMx, FunctionalState NewState)
Selects the TIMx peripheral Capture Compare DMA source.
TIMx where x can be 1, 2, 3, 4, 5, 8, 15, 16 or 17 to select the TIM peripheral. NewState new state of the Capture Compare DMA source This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST4_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR2, TIM_CR2_CCDS.
void TIM_CCPreloadControl(TIM_TypeDef *TIMx, FunctionalState NewState)
Sets or Resets the TIM peripheral Capture Compare Preload Control bit.
TIMx where x can be 1, 2, 3, 4, 5, 8 or 15 to select the TIMx peripheral NewState new state of the Capture Compare Preload Control bit This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST5_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR2, TIM_CR2_CCPC.
void TIM_OC1PreloadConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR1.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values: TIM_OCPreload_Enable TIM_OCPreload_Disable None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_OCPRELOAD_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC1PE.
void TIM_OC2PreloadConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR2.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values: TIM_OCPreload_Enable TIM_OCPreload_Disable None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_OCPRELOAD_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC2PE.
void TIM_OC3PreloadConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR3.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values: TIM_OCPreload_Enable TIM_OCPreload_Disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCPRELOAD_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC3PE.
void TIM_OC4PreloadConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPreload)
Enables or disables the TIMx peripheral Preload register on CCR4.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCPreload new state of the TIMx peripheral Preload register This parameter can be one of the following values: TIM_OCPreload_Enable TIM_OCPreload_Disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCPRELOAD_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC4PE.
void TIM_OC1FastConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 1 Fast feature.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values: TIM_OCFast_Enable: TIM output compare fast enable TIM_OCFast_Disable: TIM output compare fast disable None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_OCFAST_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC1FE.
void TIM_OC2FastConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 2 Fast feature.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values: TIM_OCFast_Enable: TIM output compare fast enable TIM_OCFast_Disable: TIM output compare fast disable None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_OCFAST_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC2FE.
void TIM_OC3FastConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 3 Fast feature.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values: TIM_OCFast_Enable: TIM output compare fast enable TIM_OCFast_Disable: TIM output compare fast disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCFAST_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC3FE.
void TIM_OC4FastConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCFast)
Configures the TIMx Output Compare 4 Fast feature.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCFast new state of the Output Compare Fast Enable Bit. This parameter can be one of the following values: TIM_OCFast_Enable: TIM output compare fast enable TIM_OCFast_Disable: TIM output compare fast disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCFAST_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC4FE.
void TIM_ClearOC1Ref(TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF1 signal on an external event.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values: TIM_OCClear_Enable: TIM Output clear enable TIM_OCClear_Disable: TIM Output clear disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCCLEAR_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC1CE.
void TIM_ClearOC2Ref(TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF2 signal on an external event.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values: TIM_OCClear_Enable: TIM Output clear enable TIM_OCClear_Disable: TIM Output clear disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCCLEAR_STATE, TIM_TypeDef::CCMR1, TIM_CCMR1_OC2CE.
void TIM_ClearOC3Ref(TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF3 signal on an external event.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values: TIM_OCClear_Enable: TIM Output clear enable TIM_OCClear_Disable: TIM Output clear disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCCLEAR_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC3CE.
void TIM_ClearOC4Ref(TIM_TypeDef *TIMx, uint16_t TIM_OCClear)
Clears or safeguards the OCREF4 signal on an external event.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCClear new state of the Output Compare Clear Enable Bit. This parameter can be one of the following values: TIM_OCClear_Enable: TIM Output clear enable TIM_OCClear_Disable: TIM Output clear disable None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OCCLEAR_STATE, TIM_TypeDef::CCMR2, TIM_CCMR2_OC4CE.
void TIM_OC1PolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 1 polarity.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_OCPolarity specifies the OC1 Polarity This parameter can be one of the following values: TIM_OCPolarity_High: Output Compare active high TIM_OCPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_OC_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC1P.
void TIM_OC1NPolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 1N polarity.
TIMx where x can be 1, 8, 15, 16 or 17 to select the TIM peripheral. TIM_OCNPolarity specifies the OC1N Polarity This parameter can be one of the following values: TIM_OCNPolarity_High: Output Compare active high TIM_OCNPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST2_PERIPH, IS_TIM_OCN_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC1NP.
void TIM_OC2PolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 2 polarity.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_OCPolarity specifies the OC2 Polarity This parameter can be one of the following values: TIM_OCPolarity_High: Output Compare active high TIM_OCPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_OC_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC2P.
void TIM_OC2NPolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 2N polarity.
TIMx where x can be 1 or 8 to select the TIM peripheral. TIM_OCNPolarity specifies the OC2N Polarity This parameter can be one of the following values: TIM_OCNPolarity_High: Output Compare active high TIM_OCNPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST1_PERIPH, IS_TIM_OCN_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC2NP.
void TIM_OC3PolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 3 polarity.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCPolarity specifies the OC3 Polarity This parameter can be one of the following values: TIM_OCPolarity_High: Output Compare active high TIM_OCPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OC_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC3P.
void TIM_OC3NPolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCNPolarity)
Configures the TIMx Channel 3N polarity.
TIMx where x can be 1 or 8 to select the TIM peripheral. TIM_OCNPolarity specifies the OC3N Polarity This parameter can be one of the following values: TIM_OCNPolarity_High: Output Compare active high TIM_OCNPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST1_PERIPH, IS_TIM_OCN_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC3NP.
void TIM_OC4PolarityConfig(TIM_TypeDef *TIMx, uint16_t TIM_OCPolarity)
Configures the TIMx channel 4 polarity.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_OCPolarity specifies the OC4 Polarity This parameter can be one of the following values: TIM_OCPolarity_High: Output Compare active high TIM_OCPolarity_Low: Output Compare active low None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_OC_POLARITY, TIM_TypeDef::CCER, TIM_CCER_CC4P.
void TIM_CCxCmd(TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_CCx)
Enables or disables the TIM Capture Compare Channel x.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_Channel specifies the TIM Channel This parameter can be one of the following values: TIM_Channel_1: TIM Channel 1 TIM_Channel_2: TIM Channel 2 TIM_Channel_3: TIM Channel 3 TIM_Channel_4: TIM Channel 4 TIM_CCx specifies the TIM Channel CCxE bit new state. This parameter can be: TIM_CCx_Enable or TIM_CCx_Disable. None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_CHANNEL, IS_TIM_CCX, CCER_CCE_Set, TIM_TypeDef::CCER.
void TIM_CCxNCmd(TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_CCxN)
Enables or disables the TIM Capture Compare Channel xN.
TIMx where x can be 1, 8, 15, 16 or 17 to select the TIM peripheral. TIM_Channel specifies the TIM Channel This parameter can be one of the following values: TIM_Channel_1: TIM Channel 1 TIM_Channel_2: TIM Channel 2 TIM_Channel_3: TIM Channel 3 TIM_CCxN specifies the TIM Channel CCxNE bit new state. This parameter can be: TIM_CCxN_Enable or TIM_CCxN_Disable. None
References assert_param, IS_TIM_LIST2_PERIPH, IS_TIM_COMPLEMENTARY_CHANNEL, IS_TIM_CCXN, CCER_CCNE_Set, TIM_TypeDef::CCER.
void TIM_SelectOCxM(TIM_TypeDef *TIMx, uint16_t TIM_Channel, uint16_t TIM_OCMode)
Selects the TIM Output Compare Mode.
This function disables the selected channel before changing the Output Compare Mode. User has to enable this channel using TIM_CCxCmd and TIM_CCxNCmd functions. TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_Channel specifies the TIM Channel This parameter can be one of the following values: TIM_Channel_1: TIM Channel 1 TIM_Channel_2: TIM Channel 2 TIM_Channel_3: TIM Channel 3 TIM_Channel_4: TIM Channel 4 TIM_OCMode specifies the TIM Output Compare Mode. This parameter can be one of the following values: TIM_OCMode_Timing TIM_OCMode_Active TIM_OCMode_Toggle TIM_OCMode_PWM1 TIM_OCMode_PWM2 TIM_ForcedAction_Active TIM_ForcedAction_InActive None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_CHANNEL, IS_TIM_OCM, CCMR_Offset, CCER_CCE_Set, TIM_TypeDef::CCER, TIM_Channel_1, TIM_Channel_3, __IO, TIM_CCMR1_OC1M, TIM_CCMR1_OC2M.
void TIM_UpdateDisableConfig(TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or Disables the TIMx Update event.
TIMx where x can be 1 to 17 to select the TIM peripheral. NewState new state of the TIMx UDIS bit This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_ALL_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR1, TIM_CR1_UDIS.
void TIM_UpdateRequestConfig(TIM_TypeDef *TIMx, uint16_t TIM_UpdateSource)
Configures the TIMx Update Request Interrupt source.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_UpdateSource specifies the Update source. This parameter can be one of the following values: TIM_UpdateSource_Regular: Source of update is the counter overflow/underflow or the setting of UG bit, or an update generation through the slave mode controller. TIM_UpdateSource_Global: Source of update is counter overflow/underflow. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_UPDATE_SOURCE, TIM_UpdateSource_Global, TIM_TypeDef::CR1, TIM_CR1_URS.
void TIM_SelectHallSensor(TIM_TypeDef *TIMx, FunctionalState NewState)
Enables or disables the TIMx's Hall sensor interface.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. NewState new state of the TIMx Hall sensor interface. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_TIM_LIST6_PERIPH, IS_FUNCTIONAL_STATE, DISABLE, TIM_TypeDef::CR2, TIM_CR2_TI1S.
void TIM_SelectOnePulseMode(TIM_TypeDef *TIMx, uint16_t TIM_OPMode)
Selects the TIMx's One Pulse Mode.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_OPMode specifies the OPM Mode to be used. This parameter can be one of the following values: TIM_OPMode_Single TIM_OPMode_Repetitive None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_OPM_MODE, TIM_TypeDef::CR1, TIM_CR1_OPM.
void TIM_SelectOutputTrigger(TIM_TypeDef *TIMx, uint16_t TIM_TRGOSource)
Selects the TIMx Trigger Output Mode.
TIMx where x can be 1, 2, 3, 4, 5, 6, 7, 8, 9, 12 or 15 to select the TIM peripheral. TIM_TRGOSource specifies the Trigger Output source. This paramter can be one of the following values: For all TIMx TIM_TRGOSource_Reset: The UG bit in the TIM_EGR register is used as the trigger output (TRGO). TIM_TRGOSource_Enable: The Counter Enable CEN is used as the trigger output (TRGO). TIM_TRGOSource_Update: The update event is selected as the trigger output (TRGO). For all TIMx except TIM6 and TIM7 TIM_TRGOSource_OC1: The trigger output sends a positive pulse when the CC1IF flag is to be set, as soon as a capture or compare match occurs (TRGO). TIM_TRGOSource_OC1Ref: OC1REF signal is used as the trigger output (TRGO). TIM_TRGOSource_OC2Ref: OC2REF signal is used as the trigger output (TRGO). TIM_TRGOSource_OC3Ref: OC3REF signal is used as the trigger output (TRGO). TIM_TRGOSource_OC4Ref: OC4REF signal is used as the trigger output (TRGO). None
References assert_param, IS_TIM_LIST7_PERIPH, IS_TIM_TRGO_SOURCE, TIM_TypeDef::CR2, TIM_CR2_MMS.
void TIM_SelectSlaveMode(TIM_TypeDef *TIMx, uint16_t TIM_SlaveMode)
Selects the TIMx Slave Mode.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_SlaveMode specifies the Timer Slave Mode. This parameter can be one of the following values: TIM_SlaveMode_Reset: Rising edge of the selected trigger signal (TRGI) re-initializes the counter and triggers an update of the registers. TIM_SlaveMode_Gated: The counter clock is enabled when the trigger signal (TRGI) is high. TIM_SlaveMode_Trigger: The counter starts at a rising edge of the trigger TRGI. TIM_SlaveMode_External1: Rising edges of the selected trigger (TRGI) clock the counter. None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_SLAVE_MODE, TIM_TypeDef::SMCR, TIM_SMCR_SMS.
void TIM_SelectMasterSlaveMode(TIM_TypeDef *TIMx, uint16_t TIM_MasterSlaveMode)
Sets or Resets the TIMx Master/Slave Mode.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_MasterSlaveMode specifies the Timer Master Slave Mode. This parameter can be one of the following values: TIM_MasterSlaveMode_Enable: synchronization between the current timer and its slaves (through TRGO). TIM_MasterSlaveMode_Disable: No action None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_MSM_STATE, TIM_TypeDef::SMCR, TIM_SMCR_MSM.
void TIM_SetCounter(TIM_TypeDef *TIMx, uint16_t Counter)
Sets the TIMx Counter Register value.
TIMx where x can be 1 to 17 to select the TIM peripheral. Counter specifies the Counter register new value. None
References assert_param, IS_TIM_ALL_PERIPH, TIM_TypeDef::CNT.
void TIM_SetAutoreload(TIM_TypeDef *TIMx, uint16_t Autoreload)
Sets the TIMx Autoreload Register value.
TIMx where x can be 1 to 17 to select the TIM peripheral. Autoreload specifies the Autoreload register new value. None
References assert_param, IS_TIM_ALL_PERIPH, TIM_TypeDef::ARR.
void TIM_SetCompare1(TIM_TypeDef *TIMx, uint16_t Compare1)
Sets the TIMx Capture Compare1 Register value.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. Compare1 specifies the Capture Compare1 register new value. None
References assert_param, IS_TIM_LIST8_PERIPH, TIM_TypeDef::CCR1.
void TIM_SetCompare2(TIM_TypeDef *TIMx, uint16_t Compare2)
Sets the TIMx Capture Compare2 Register value.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. Compare2 specifies the Capture Compare2 register new value. None
References assert_param, IS_TIM_LIST6_PERIPH, TIM_TypeDef::CCR2.
void TIM_SetCompare3(TIM_TypeDef *TIMx, uint16_t Compare3)
Sets the TIMx Capture Compare3 Register value.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. Compare3 specifies the Capture Compare3 register new value. None
References assert_param, IS_TIM_LIST3_PERIPH, TIM_TypeDef::CCR3.
void TIM_SetCompare4(TIM_TypeDef *TIMx, uint16_t Compare4)
Sets the TIMx Capture Compare4 Register value.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. Compare4 specifies the Capture Compare4 register new value. None
References assert_param, IS_TIM_LIST3_PERIPH, TIM_TypeDef::CCR4.
void TIM_SetIC1Prescaler(TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 1 prescaler.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_ICPSC specifies the Input Capture1 prescaler new value. This parameter can be one of the following values: TIM_ICPSC_DIV1: no prescaler TIM_ICPSC_DIV2: capture is done once every 2 events TIM_ICPSC_DIV4: capture is done once every 4 events TIM_ICPSC_DIV8: capture is done once every 8 events None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_IC_PRESCALER, TIM_TypeDef::CCMR1, TIM_CCMR1_IC1PSC.
void TIM_SetIC2Prescaler(TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 2 prescaler.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. TIM_ICPSC specifies the Input Capture2 prescaler new value. This parameter can be one of the following values: TIM_ICPSC_DIV1: no prescaler TIM_ICPSC_DIV2: capture is done once every 2 events TIM_ICPSC_DIV4: capture is done once every 4 events TIM_ICPSC_DIV8: capture is done once every 8 events None
References assert_param, IS_TIM_LIST6_PERIPH, IS_TIM_IC_PRESCALER, TIM_TypeDef::CCMR1, TIM_CCMR1_IC2PSC.
void TIM_SetIC3Prescaler(TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 3 prescaler.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ICPSC specifies the Input Capture3 prescaler new value. This parameter can be one of the following values: TIM_ICPSC_DIV1: no prescaler TIM_ICPSC_DIV2: capture is done once every 2 events TIM_ICPSC_DIV4: capture is done once every 4 events TIM_ICPSC_DIV8: capture is done once every 8 events None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_IC_PRESCALER, TIM_TypeDef::CCMR2, TIM_CCMR2_IC3PSC.
void TIM_SetIC4Prescaler(TIM_TypeDef *TIMx, uint16_t TIM_ICPSC)
Sets the TIMx Input Capture 4 prescaler.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. TIM_ICPSC specifies the Input Capture4 prescaler new value. This parameter can be one of the following values: TIM_ICPSC_DIV1: no prescaler TIM_ICPSC_DIV2: capture is done once every 2 events TIM_ICPSC_DIV4: capture is done once every 4 events TIM_ICPSC_DIV8: capture is done once every 8 events None
References assert_param, IS_TIM_LIST3_PERIPH, IS_TIM_IC_PRESCALER, TIM_TypeDef::CCMR2, TIM_CCMR2_IC4PSC.
void TIM_SetClockDivision(TIM_TypeDef *TIMx, uint16_t TIM_CKD)
Sets the TIMx Clock Division value.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. TIM_CKD specifies the clock division value. This parameter can be one of the following value: TIM_CKD_DIV1: TDTS = Tck_tim TIM_CKD_DIV2: TDTS = 2*Tck_tim TIM_CKD_DIV4: TDTS = 4*Tck_tim None
References assert_param, IS_TIM_LIST8_PERIPH, IS_TIM_CKD_DIV, TIM_TypeDef::CR1, TIM_CR1_CKD.
uint16_t TIM_GetCapture1(TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 1 value.
TIMx where x can be 1 to 17 except 6 and 7 to select the TIM peripheral. Capture Compare 1 Register value.
References assert_param, IS_TIM_LIST8_PERIPH, TIM_TypeDef::CCR1.
uint16_t TIM_GetCapture2(TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 2 value.
TIMx where x can be 1, 2, 3, 4, 5, 8, 9, 12 or 15 to select the TIM peripheral. Capture Compare 2 Register value.
References assert_param, IS_TIM_LIST6_PERIPH, TIM_TypeDef::CCR2.
uint16_t TIM_GetCapture3(TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 3 value.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. Capture Compare 3 Register value.
References assert_param, IS_TIM_LIST3_PERIPH, TIM_TypeDef::CCR3.
uint16_t TIM_GetCapture4(TIM_TypeDef *TIMx)
Gets the TIMx Input Capture 4 value.
TIMx where x can be 1, 2, 3, 4, 5 or 8 to select the TIM peripheral. Capture Compare 4 Register value.
References assert_param, IS_TIM_LIST3_PERIPH, TIM_TypeDef::CCR4.
uint16_t TIM_GetCounter(TIM_TypeDef *TIMx)
Gets the TIMx Counter value.
TIMx where x can be 1 to 17 to select the TIM peripheral. Counter Register value.
References assert_param, IS_TIM_ALL_PERIPH, TIM_TypeDef::CNT.
uint16_t TIM_GetPrescaler(TIM_TypeDef *TIMx)
Gets the TIMx Prescaler value.
TIMx where x can be 1 to 17 to select the TIM peripheral. Prescaler Register value.
References assert_param, IS_TIM_ALL_PERIPH, TIM_TypeDef::PSC.
FlagStatus TIM_GetFlagStatus(TIM_TypeDef *TIMx, uint16_t TIM_FLAG)
Checks whether the specified TIM flag is set or not.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_FLAG specifies the flag to check. This parameter can be one of the following values: TIM_FLAG_Update: TIM update Flag TIM_FLAG_CC1: TIM Capture Compare 1 Flag TIM_FLAG_CC2: TIM Capture Compare 2 Flag TIM_FLAG_CC3: TIM Capture Compare 3 Flag TIM_FLAG_CC4: TIM Capture Compare 4 Flag TIM_FLAG_COM: TIM Commutation Flag TIM_FLAG_Trigger: TIM Trigger Flag TIM_FLAG_Break: TIM Break Flag TIM_FLAG_CC1OF: TIM Capture Compare 1 overcapture Flag TIM_FLAG_CC2OF: TIM Capture Compare 2 overcapture Flag TIM_FLAG_CC3OF: TIM Capture Compare 3 overcapture Flag TIM_FLAG_CC4OF: TIM Capture Compare 4 overcapture Flag TIM6 and TIM7 can have only one update flag.TIM9, TIM12 and TIM15 can have only TIM_FLAG_Update, TIM_FLAG_CC1, TIM_FLAG_CC2 or TIM_FLAG_Trigger.TIM10, TIM11, TIM13, TIM14, TIM16 and TIM17 can have TIM_FLAG_Update or TIM_FLAG_CC1.TIM_FLAG_Break is used only with TIM1, TIM8 and TIM15.TIM_FLAG_COM is used only with TIM1, TIM8, TIM15, TIM16 and TIM17. The new state of TIM_FLAG (SET or RESET).
References RESET, assert_param, IS_TIM_ALL_PERIPH, IS_TIM_GET_FLAG, TIM_TypeDef::SR, SET.
void TIM_ClearFlag(TIM_TypeDef *TIMx, uint16_t TIM_FLAG)
Clears the TIMx's pending flags.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_FLAG specifies the flag bit to clear. This parameter can be any combination of the following values: TIM_FLAG_Update: TIM update Flag TIM_FLAG_CC1: TIM Capture Compare 1 Flag TIM_FLAG_CC2: TIM Capture Compare 2 Flag TIM_FLAG_CC3: TIM Capture Compare 3 Flag TIM_FLAG_CC4: TIM Capture Compare 4 Flag TIM_FLAG_COM: TIM Commutation Flag TIM_FLAG_Trigger: TIM Trigger Flag TIM_FLAG_Break: TIM Break Flag TIM_FLAG_CC1OF: TIM Capture Compare 1 overcapture Flag TIM_FLAG_CC2OF: TIM Capture Compare 2 overcapture Flag TIM_FLAG_CC3OF: TIM Capture Compare 3 overcapture Flag TIM_FLAG_CC4OF: TIM Capture Compare 4 overcapture Flag TIM6 and TIM7 can have only one update flag.TIM9, TIM12 and TIM15 can have only TIM_FLAG_Update, TIM_FLAG_CC1, TIM_FLAG_CC2 or TIM_FLAG_Trigger.TIM10, TIM11, TIM13, TIM14, TIM16 and TIM17 can have TIM_FLAG_Update or TIM_FLAG_CC1.TIM_FLAG_Break is used only with TIM1, TIM8 and TIM15.TIM_FLAG_COM is used only with TIM1, TIM8, TIM15, TIM16 and TIM17. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_CLEAR_FLAG, TIM_TypeDef::SR.
ITStatus TIM_GetITStatus(TIM_TypeDef *TIMx, uint16_t TIM_IT)
Checks whether the TIM interrupt has occurred or not.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_IT specifies the TIM interrupt source to check. This parameter can be one of the following values: TIM_IT_Update: TIM update Interrupt source TIM_IT_CC1: TIM Capture Compare 1 Interrupt source TIM_IT_CC2: TIM Capture Compare 2 Interrupt source TIM_IT_CC3: TIM Capture Compare 3 Interrupt source TIM_IT_CC4: TIM Capture Compare 4 Interrupt source TIM_IT_COM: TIM Commutation Interrupt source TIM_IT_Trigger: TIM Trigger Interrupt source TIM_IT_Break: TIM Break Interrupt source TIM6 and TIM7 can generate only an update interrupt.TIM9, TIM12 and TIM15 can have only TIM_IT_Update, TIM_IT_CC1, TIM_IT_CC2 or TIM_IT_Trigger.TIM10, TIM11, TIM13, TIM14, TIM16 and TIM17 can have TIM_IT_Update or TIM_IT_CC1.TIM_IT_Break is used only with TIM1, TIM8 and TIM15.TIM_IT_COM is used only with TIM1, TIM8, TIM15, TIM16 and TIM17. The new state of the TIM_IT(SET or RESET).
References RESET, assert_param, IS_TIM_ALL_PERIPH, IS_TIM_GET_IT, TIM_TypeDef::SR, TIM_TypeDef::DIER, SET.
void TIM_ClearITPendingBit(TIM_TypeDef *TIMx, uint16_t TIM_IT)
Clears the TIMx's interrupt pending bits.
TIMx where x can be 1 to 17 to select the TIM peripheral. TIM_IT specifies the pending bit to clear. This parameter can be any combination of the following values: TIM_IT_Update: TIM1 update Interrupt source TIM_IT_CC1: TIM Capture Compare 1 Interrupt source TIM_IT_CC2: TIM Capture Compare 2 Interrupt source TIM_IT_CC3: TIM Capture Compare 3 Interrupt source TIM_IT_CC4: TIM Capture Compare 4 Interrupt source TIM_IT_COM: TIM Commutation Interrupt source TIM_IT_Trigger: TIM Trigger Interrupt source TIM_IT_Break: TIM Break Interrupt source TIM6 and TIM7 can generate only an update interrupt.TIM9, TIM12 and TIM15 can have only TIM_IT_Update, TIM_IT_CC1, TIM_IT_CC2 or TIM_IT_Trigger.TIM10, TIM11, TIM13, TIM14, TIM16 and TIM17 can have TIM_IT_Update or TIM_IT_CC1.TIM_IT_Break is used only with TIM1, TIM8 and TIM15.TIM_IT_COM is used only with TIM1, TIM8, TIM15, TIM16 and TIM17. None
References assert_param, IS_TIM_ALL_PERIPH, IS_TIM_IT, TIM_TypeDef::SR.