stm32f10x_flash.h
FLASH_Latency_0
FLASH Zero Latency cycle
FLASH_Latency_1
FLASH One Latency cycle
FLASH_Latency_2
FLASH Two Latency cycles
IS_FLASH_LATENCY
FLASH_HalfCycleAccess_Enable
FLASH Half Cycle Enable
FLASH_HalfCycleAccess_Disable
FLASH Half Cycle Disable
IS_FLASH_HALFCYCLEACCESS_STATE
FLASH_PrefetchBuffer_Enable
FLASH Prefetch Buffer Enable
FLASH_PrefetchBuffer_Disable
FLASH Prefetch Buffer Disable
IS_FLASH_PREFETCHBUFFER_STATE
FLASH_WRProt_Pages0to3
STM32 Low and Medium density devices: Write protection of page 0 to 3
FLASH_WRProt_Pages4to7
STM32 Low and Medium density devices: Write protection of page 4 to 7
FLASH_WRProt_Pages8to11
STM32 Low and Medium density devices: Write protection of page 8 to 11
FLASH_WRProt_Pages12to15
STM32 Low and Medium density devices: Write protection of page 12 to 15
FLASH_WRProt_Pages16to19
STM32 Low and Medium density devices: Write protection of page 16 to 19
FLASH_WRProt_Pages20to23
STM32 Low and Medium density devices: Write protection of page 20 to 23
FLASH_WRProt_Pages24to27
STM32 Low and Medium density devices: Write protection of page 24 to 27
FLASH_WRProt_Pages28to31
STM32 Low and Medium density devices: Write protection of page 28 to 31
FLASH_WRProt_Pages32to35
STM32 Medium-density devices: Write protection of page 32 to 35
FLASH_WRProt_Pages36to39
STM32 Medium-density devices: Write protection of page 36 to 39
FLASH_WRProt_Pages40to43
STM32 Medium-density devices: Write protection of page 40 to 43
FLASH_WRProt_Pages44to47
STM32 Medium-density devices: Write protection of page 44 to 47
FLASH_WRProt_Pages48to51
STM32 Medium-density devices: Write protection of page 48 to 51
FLASH_WRProt_Pages52to55
STM32 Medium-density devices: Write protection of page 52 to 55
FLASH_WRProt_Pages56to59
STM32 Medium-density devices: Write protection of page 56 to 59
FLASH_WRProt_Pages60to63
STM32 Medium-density devices: Write protection of page 60 to 63
FLASH_WRProt_Pages64to67
STM32 Medium-density devices: Write protection of page 64 to 67
FLASH_WRProt_Pages68to71
STM32 Medium-density devices: Write protection of page 68 to 71
FLASH_WRProt_Pages72to75
STM32 Medium-density devices: Write protection of page 72 to 75
FLASH_WRProt_Pages76to79
STM32 Medium-density devices: Write protection of page 76 to 79
FLASH_WRProt_Pages80to83
STM32 Medium-density devices: Write protection of page 80 to 83
FLASH_WRProt_Pages84to87
STM32 Medium-density devices: Write protection of page 84 to 87
FLASH_WRProt_Pages88to91
STM32 Medium-density devices: Write protection of page 88 to 91
FLASH_WRProt_Pages92to95
STM32 Medium-density devices: Write protection of page 92 to 95
FLASH_WRProt_Pages96to99
STM32 Medium-density devices: Write protection of page 96 to 99
FLASH_WRProt_Pages100to103
STM32 Medium-density devices: Write protection of page 100 to 103
FLASH_WRProt_Pages104to107
STM32 Medium-density devices: Write protection of page 104 to 107
FLASH_WRProt_Pages108to111
STM32 Medium-density devices: Write protection of page 108 to 111
FLASH_WRProt_Pages112to115
STM32 Medium-density devices: Write protection of page 112 to 115
FLASH_WRProt_Pages116to119
STM32 Medium-density devices: Write protection of page 115 to 119
FLASH_WRProt_Pages120to123
STM32 Medium-density devices: Write protection of page 120 to 123
FLASH_WRProt_Pages124to127
STM32 Medium-density devices: Write protection of page 124 to 127
FLASH_WRProt_Pages0to1
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 0 to 1
FLASH_WRProt_Pages2to3
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 2 to 3
FLASH_WRProt_Pages4to5
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 4 to 5
FLASH_WRProt_Pages6to7
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 6 to 7
FLASH_WRProt_Pages8to9
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 8 to 9
FLASH_WRProt_Pages10to11
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 10 to 11
FLASH_WRProt_Pages12to13
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 12 to 13
FLASH_WRProt_Pages14to15
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 14 to 15
FLASH_WRProt_Pages16to17
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 16 to 17
FLASH_WRProt_Pages18to19
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 18 to 19
FLASH_WRProt_Pages20to21
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 20 to 21
FLASH_WRProt_Pages22to23
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 22 to 23
FLASH_WRProt_Pages24to25
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 24 to 25
FLASH_WRProt_Pages26to27
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 26 to 27
FLASH_WRProt_Pages28to29
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 28 to 29
FLASH_WRProt_Pages30to31
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 30 to 31
FLASH_WRProt_Pages32to33
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 32 to 33
FLASH_WRProt_Pages34to35
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 34 to 35
FLASH_WRProt_Pages36to37
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 36 to 37
FLASH_WRProt_Pages38to39
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 38 to 39
FLASH_WRProt_Pages40to41
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 40 to 41
FLASH_WRProt_Pages42to43
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 42 to 43
FLASH_WRProt_Pages44to45
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 44 to 45
FLASH_WRProt_Pages46to47
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 46 to 47
FLASH_WRProt_Pages48to49
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 48 to 49
FLASH_WRProt_Pages50to51
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 50 to 51
FLASH_WRProt_Pages52to53
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 52 to 53
FLASH_WRProt_Pages54to55
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 54 to 55
FLASH_WRProt_Pages56to57
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 56 to 57
FLASH_WRProt_Pages58to59
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 58 to 59
FLASH_WRProt_Pages60to61
STM32 High-density, XL-density and Connectivity line devices: Write protection of page 60 to 61
FLASH_WRProt_Pages62to127
STM32 Connectivity line devices: Write protection of page 62 to 127
FLASH_WRProt_Pages62to255
STM32 Medium-density devices: Write protection of page 62 to 255
FLASH_WRProt_Pages62to511
STM32 XL-density devices: Write protection of page 62 to 511
FLASH_WRProt_AllPages
Write protection of all Pages
IS_FLASH_WRPROT_PAGE
IS_FLASH_ADDRESS
IS_OB_DATA_ADDRESS
OB_IWDG_SW
Software IWDG selected
OB_IWDG_HW
Hardware IWDG selected
IS_OB_IWDG_SOURCE
OB_STOP_NoRST
No reset generated when entering in STOP
OB_STOP_RST
Reset generated when entering in STOP
IS_OB_STOP_SOURCE
OB_STDBY_NoRST
No reset generated when entering in STANDBY
OB_STDBY_RST
Reset generated when entering in STANDBY
IS_OB_STDBY_SOURCE
FLASH_IT_ERROR
FPEC error interrupt source
FLASH_IT_EOP
End of FLASH Operation Interrupt source
FLASH_IT_BANK1_ERROR
FPEC BANK1 error interrupt source
FLASH_IT_BANK1_EOP
End of FLASH BANK1 Operation Interrupt source
IS_FLASH_IT
FLASH_FLAG_BSY
FLASH Busy flag
FLASH_FLAG_EOP
FLASH End of Operation flag
FLASH_FLAG_PGERR
FLASH Program error flag
FLASH_FLAG_WRPRTERR
FLASH Write protected error flag
FLASH_FLAG_OPTERR
FLASH Option Byte error flag
FLASH_FLAG_BANK1_BSY
FLASH BANK1 Busy flag
FLASH_FLAG_BANK1_EOP
FLASH BANK1 End of Operation flag
FLASH_FLAG_BANK1_PGERR
FLASH BANK1 Program error flag
FLASH_FLAG_BANK1_WRPRTERR
FLASH BANK1 Write protected error flag
IS_FLASH_CLEAR_FLAG
IS_FLASH_GET_FLAG
FLASH_Status
void FLASH_SetLatency(uint32_t FLASH_Latency)
Sets the code latency value.
ThisdriverprovidesfunctionstoconfigureandprogramtheFlashmemoryofallSTM32F10xdevices, includingthelatestSTM32F10x_XLdensitydevices. STM32F10x_XLdevicesfeatureupto1Mbytewithdualbankarchitectureforread-while-write(RWW)capability: -bank1:fixedsizeof512Kbytes(256pagesof2Kbyteseach) -bank2:upto512Kbytes(upto256pagesof2Kbyteseach) WhileotherSTM32F10xdevicesfeaturesonlyonebankwithmemoryupto512Kbytes. InversionV3.3.0,somefunctionswereupdatedandnewoneswereaddedtosupport STM32F10x_XLdevices.Thussomefunctionsmanagesalldevices,whileotherare dedicatedforXLdevicesonly. ThetablebelowpresentsthelistofavailablefunctionsdependingontheusedSTM32F10xdevices. LegacyfunctionsusedforallSTM32F10xdevices* +----------------------------------------------------------------------------------------------------------------------------------+ |Functionsprototypes|STM32F10x_XL|OtherSTM32F10x|Comments| ||devices|devices|| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_SetLatency|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_HalfCycleAccessCmd|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_PrefetchBufferCmd|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_Unlock|Yes|Yes|-ForSTM32F10X_XLdevices:unlockBank1andBank2.| ||||-Forotherdevices:unlockBank1anditisequivalent| ||||toFLASH_UnlockBank1function.| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_Lock|Yes|Yes|-ForSTM32F10X_XLdevices:lockBank1andBank2.| ||||-Forotherdevices:lockBank1anditisequivalent| ||||toFLASH_LockBank1function.| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ErasePage|Yes|Yes|-ForSTM32F10x_XLdevices:eraseapageinBank1andBank2| ||||-Forotherdevices:eraseapageinBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_EraseAllPages|Yes|Yes|-ForSTM32F10x_XLdevices:eraseallpagesinBank1andBank2| ||||-Forotherdevices:eraseallpagesinBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_EraseOptionBytes|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ProgramWord|Yes|Yes|Updatedtoprogramupto1MByte(dependingontheuseddevice)| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ProgramHalfWord|Yes|Yes|Updatedtoprogramupto1MByte(dependingontheuseddevice)| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ProgramOptionByteData|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_EnableWriteProtection|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ReadOutProtection|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_UserOptionByteConfig|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetUserOptionByte|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetWriteProtectionOptionByte|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetReadOutProtectionStatus|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetPrefetchBufferStatus|Yes|Yes|Nochange| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ITConfig|Yes|Yes|-ForSTM32F10x_XLdevices:enableBank1andBank2'sinterrupts| ||||-Forotherdevices:enableBank1'sinterrupts| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetFlagStatus|Yes|Yes|-ForSTM32F10x_XLdevices:returnBank1andBank2'sflagstatus| ||||-Forotherdevices:returnBank1'sflagstatus| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_ClearFlag|Yes|Yes|-ForSTM32F10x_XLdevices:clearBank1andBank2'sflag| ||||-Forotherdevices:clearBank1'sflag| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetStatus|Yes|Yes|-ReturnthestatusofBank1(foralldevices)| ||||equivalenttoFLASH_GetBank1Statusfunction| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_WaitForLastOperation|Yes|Yes|-WaitforBank1lastoperation(foralldevices)| ||||equivalentto:FLASH_WaitForLastBank1Operationfunction| +----------------------------------------------------------------------------------------------------------------------------------+ NewfunctionsusedforallSTM32F10xdevicestomanageBank1:* -ThesefunctionsaremainlyusefulforSTM32F10x_XLdensitydevices,tohaveseparatecontrolforBank1andbank2* -Forotherdevices,thesefunctionsareoptional(coveredbyfunctionslistedabove)* +----------------------------------------------------------------------------------------------------------------------------------+ |Functionsprototypes|STM32F10x_XL|OtherSTM32F10x|Comments| ||devices|devices|| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_UnlockBank1|Yes|Yes|-UnlockBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_LockBank1|Yes|Yes|-LockBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_EraseAllBank1Pages|Yes|Yes|-EraseallpagesinBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetBank1Status|Yes|Yes|-ReturnthestatusofBank1| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_WaitForLastBank1Operation|Yes|Yes|-WaitforBank1lastoperation| +----------------------------------------------------------------------------------------------------------------------------------+ NewFunctionsusedonlywithSTM32F10x_XLdensitydevicestomanageBank2* +----------------------------------------------------------------------------------------------------------------------------------+ |Functionsprototypes|STM32F10x_XL|OtherSTM32F10x|Comments| ||devices|devices|| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_UnlockBank2|Yes|No|-UnlockBank2| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_LockBank2|Yes|No|-LockBank2| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_EraseAllBank2Pages|Yes|No|-EraseallpagesinBank2| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_GetBank2Status|Yes|No|-ReturnthestatusofBank2| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_WaitForLastBank2Operation|Yes|No|-WaitforBank2lastoperation| |----------------------------------------------------------------------------------------------------------------------------------| |FLASH_BootConfig|Yes|No|-ConfiguretobootfromBank1orBank2| +----------------------------------------------------------------------------------------------------------------------------------+ This function can be used for all STM32F10x devices. FLASH_Latency specifies the FLASH Latency value. This parameter can be one of the following values: FLASH_Latency_0: FLASH Zero Latency cycle FLASH_Latency_1: FLASH One Latency cycle FLASH_Latency_2: FLASH Two Latency cycles None
References assert_param, IS_FLASH_LATENCY, FLASH, ACR_LATENCY_Mask.
void FLASH_HalfCycleAccessCmd(uint32_t FLASH_HalfCycleAccess)
Enables or disables the Half cycle flash access.
This function can be used for all STM32F10x devices. FLASH_HalfCycleAccess specifies the FLASH Half cycle Access mode. This parameter can be one of the following values: FLASH_HalfCycleAccess_Enable: FLASH Half Cycle Enable FLASH_HalfCycleAccess_Disable: FLASH Half Cycle Disable None
References assert_param, IS_FLASH_HALFCYCLEACCESS_STATE, FLASH, ACR_HLFCYA_Mask.
void FLASH_PrefetchBufferCmd(uint32_t FLASH_PrefetchBuffer)
Enables or disables the Prefetch Buffer.
This function can be used for all STM32F10x devices. FLASH_PrefetchBuffer specifies the Prefetch buffer status. This parameter can be one of the following values: FLASH_PrefetchBuffer_Enable: FLASH Prefetch Buffer Enable FLASH_PrefetchBuffer_Disable: FLASH Prefetch Buffer Disable None
References assert_param, IS_FLASH_PREFETCHBUFFER_STATE, FLASH, ACR_PRFTBE_Mask.
void FLASH_Unlock(void)
Unlocks the FLASH Program Erase Controller.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices this function unlocks Bank1 and Bank2.For all other devices it unlocks Bank1 and it is equivalent to FLASH_UnlockBank1 function.. None None
References FLASH, FLASH_KEY1, FLASH_KEY2.
void FLASH_Lock(void)
Locks the FLASH Program Erase Controller.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices this function Locks Bank1 and Bank2.For all other devices it Locks Bank1 and it is equivalent to FLASH_LockBank1 function. None None
References FLASH, CR_LOCK_Set.
FLASH_Status FLASH_ErasePage(uint32_t Page_Address)
Erases a specified FLASH page.
This function can be used for all STM32F10x devices. Page_Address The page address to be erased. FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_FLASH_ADDRESS, FLASH_BANK1_END_ADDRESS, FLASH_WaitForLastBank1Operation, EraseTimeout, FLASH, CR_PER_Set, CR_STRT_Set, CR_PER_Reset, FLASH_WaitForLastOperation.
FLASH_Status FLASH_EraseAllPages(void)
Erases all FLASH pages.
This function can be used for all STM32F10x devices. None FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, FLASH_WaitForLastBank1Operation, EraseTimeout, FLASH, CR_MER_Set, CR_STRT_Set, CR_MER_Reset, FLASH_WaitForLastOperation.
FLASH_Status FLASH_EraseOptionBytes(void)
Erases the FLASH option bytes.
This functions erases all option bytes except the Read protection (RDP). This function can be used for all STM32F10x devices. None FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References RDP_Key, FLASH_COMPLETE, FLASH_GetReadOutProtectionStatus, RESET, FLASH_WaitForLastOperation, EraseTimeout, FLASH, FLASH_KEY1, FLASH_KEY2, CR_OPTER_Set, CR_STRT_Set, CR_OPTER_Reset, CR_OPTPG_Set, OB, ProgramTimeout, FLASH_TIMEOUT, CR_OPTPG_Reset.
FLASH_Status FLASH_ProgramWord(uint32_t Address, uint32_t Data)
Programs a word at a specified address.
This function can be used for all STM32F10x devices. Address specifies the address to be programmed. Data specifies the data to be programmed. FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, __IO, assert_param, IS_FLASH_ADDRESS, FLASH_BANK1_END_ADDRESS, FLASH_WaitForLastBank1Operation, ProgramTimeout, FLASH, CR_PG_Set, FLASH_WaitForLastOperation, CR_PG_Reset.
FLASH_Status FLASH_ProgramHalfWord(uint32_t Address, uint16_t Data)
Programs a half word at a specified address.
This function can be used for all STM32F10x devices. Address specifies the address to be programmed. Data specifies the data to be programmed. FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_FLASH_ADDRESS, FLASH_WaitForLastOperation, ProgramTimeout, FLASH_BANK1_END_ADDRESS, FLASH, CR_PG_Set, __IO, FLASH_WaitForLastBank1Operation, CR_PG_Reset.
FLASH_Status FLASH_ProgramOptionByteData(uint32_t Address, uint8_t Data)
Programs a half word at a specified Option Byte Data address.
This function can be used for all STM32F10x devices. Address specifies the address to be programmed. This parameter can be 0x1FFFF804 or 0x1FFFF806. Data specifies the data to be programmed. FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_OB_DATA_ADDRESS, FLASH_WaitForLastOperation, ProgramTimeout, FLASH, FLASH_KEY1, FLASH_KEY2, CR_OPTPG_Set, __IO, FLASH_TIMEOUT, CR_OPTPG_Reset.
FLASH_Status FLASH_EnableWriteProtection(uint32_t FLASH_Pages)
Write protects the desired pages.
This function can be used for all STM32F10x devices. FLASH_Pages specifies the address of the pages to be write protected. This parameter can be: For STM32_Low-density_devices: value between FLASH_WRProt_Pages0to3 and FLASH_WRProt_Pages28to31 For STM32_Medium-density_devices: value between FLASH_WRProt_Pages0to3 and FLASH_WRProt_Pages124to127 For STM32_High-density_devices: value between FLASH_WRProt_Pages0to1 and FLASH_WRProt_Pages60to61 or FLASH_WRProt_Pages62to255 For STM32_Connectivity_line_devices: value between FLASH_WRProt_Pages0to1 and FLASH_WRProt_Pages60to61 or FLASH_WRProt_Pages62to127 For STM32_XL-density_devices: value between FLASH_WRProt_Pages0to1 and FLASH_WRProt_Pages60to61 or FLASH_WRProt_Pages62to511 FLASH_WRProt_AllPages FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_FLASH_WRPROT_PAGE, WRP0_Mask, WRP1_Mask, WRP2_Mask, WRP3_Mask, FLASH_WaitForLastOperation, ProgramTimeout, FLASH, FLASH_KEY1, FLASH_KEY2, CR_OPTPG_Set, OB, FLASH_TIMEOUT, CR_OPTPG_Reset.
FLASH_Status FLASH_ReadOutProtection(FunctionalState NewState)
Enables or disables the read out protection.
If the user has already programmed the other option bytes before calling this function, he must re-program them since this function erases all option bytes. This function can be used for all STM32F10x devices. Newstate new state of the ReadOut Protection. This parameter can be: ENABLE or DISABLE. FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_FUNCTIONAL_STATE, FLASH_WaitForLastOperation, EraseTimeout, FLASH, FLASH_KEY1, FLASH_KEY2, CR_OPTER_Set, CR_STRT_Set, CR_OPTER_Reset, CR_OPTPG_Set, DISABLE, OB, RDP_Key, FLASH_TIMEOUT, CR_OPTPG_Reset.
FLASH_Status FLASH_UserOptionByteConfig(uint16_t OB_IWDG, uint16_t OB_STOP, uint16_t OB_STDBY)
Programs the FLASH User Option Byte: IWDG_SW / RST_STOP / RST_STDBY.
This function can be used for all STM32F10x devices. OB_IWDG Selects the IWDG mode This parameter can be one of the following values: OB_IWDG_SW: Software IWDG selected OB_IWDG_HW: Hardware IWDG selected OB_STOP Reset event when entering STOP mode. This parameter can be one of the following values: OB_STOP_NoRST: No reset generated when entering in STOP OB_STOP_RST: Reset generated when entering in STOP OB_STDBY Reset event when entering Standby mode. This parameter can be one of the following values: OB_STDBY_NoRST: No reset generated when entering in STANDBY OB_STDBY_RST: Reset generated when entering in STANDBY FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, assert_param, IS_OB_IWDG_SOURCE, IS_OB_STOP_SOURCE, IS_OB_STDBY_SOURCE, FLASH, FLASH_KEY1, FLASH_KEY2, FLASH_WaitForLastOperation, ProgramTimeout, CR_OPTPG_Set, OB, FLASH_TIMEOUT, CR_OPTPG_Reset, OB_USER_BFB2.
uint32_t FLASH_GetUserOptionByte(void)
Returns the FLASH User Option Bytes values.
This function can be used for all STM32F10x devices. None The FLASH User Option Bytes values:IWDG_SW(Bit0), RST_STOP(Bit1) and RST_STDBY(Bit2).
References FLASH.
uint32_t FLASH_GetWriteProtectionOptionByte(void)
Returns the FLASH Write Protection Option Bytes Register value.
This function can be used for all STM32F10x devices. None The FLASH Write Protection Option Bytes Register value
References FLASH.
FlagStatus FLASH_GetReadOutProtectionStatus(void)
Checks whether the FLASH Read Out Protection Status is set or not.
This function can be used for all STM32F10x devices. None FLASH ReadOut Protection Status(SET or RESET)
References RESET, FLASH, RDPRT_Mask, SET.
Referenced by FLASH_EraseOptionBytes.
FlagStatus FLASH_GetPrefetchBufferStatus(void)
Checks whether the FLASH Prefetch Buffer status is set or not.
This function can be used for all STM32F10x devices. None FLASH Prefetch Buffer Status (SET or RESET).
References RESET, FLASH, ACR_PRFTBS_Mask, SET.
void FLASH_ITConfig(uint32_t FLASH_IT, FunctionalState NewState)
Enables or disables the specified FLASH interrupts.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices, enables or disables the specified FLASH interrupts for Bank1 and Bank2.For other devices it enables or disables the specified FLASH interrupts for Bank1. FLASH_IT specifies the FLASH interrupt sources to be enabled or disabled. This parameter can be any combination of the following values: FLASH_IT_ERROR: FLASH Error Interrupt FLASH_IT_EOP: FLASH end of operation Interrupt NewState new state of the specified Flash interrupts. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_FLASH_IT, IS_FUNCTIONAL_STATE, DISABLE, FLASH.
FlagStatus FLASH_GetFlagStatus(uint32_t FLASH_FLAG)
Checks whether the specified FLASH flag is set or not.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices, this function checks whether the specified Bank1 or Bank2 flag is set or not.For other devices, it checks whether the specified Bank1 flag is set or not. FLASH_FLAG specifies the FLASH flag to check. This parameter can be one of the following values: FLASH_FLAG_BSY: FLASH Busy flag FLASH_FLAG_PGERR: FLASH Program error flag FLASH_FLAG_WRPRTERR: FLASH Write protected error flag FLASH_FLAG_EOP: FLASH End of Operation flag FLASH_FLAG_OPTERR: FLASH Option Byte error flag The new state of FLASH_FLAG (SET or RESET).
References RESET, assert_param, IS_FLASH_GET_FLAG, FLASH_FLAG_OPTERR, FLASH, SET.
void FLASH_ClearFlag(uint32_t FLASH_FLAG)
Clears the FLASH's pending flags.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices, this function clears Bank1 or Bank2s pending flagsFor other devices, it clears Bank1s pending flags. FLASH_FLAG specifies the FLASH flags to clear. This parameter can be any combination of the following values: FLASH_FLAG_PGERR: FLASH Program error flag FLASH_FLAG_WRPRTERR: FLASH Write protected error flag FLASH_FLAG_EOP: FLASH End of Operation flag None
References assert_param, IS_FLASH_CLEAR_FLAG, FLASH.
FLASH_Status FLASH_GetStatus(void)
Returns the FLASH Status.
This function can be used for all STM32F10x devices, it is equivalent to FLASH_GetBank1Status function. None FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG, FLASH_ERROR_WRP or FLASH_COMPLETE
References FLASH_COMPLETE, FLASH, FLASH_FLAG_BSY, FLASH_BUSY, FLASH_FLAG_PGERR, FLASH_ERROR_PG, FLASH_FLAG_WRPRTERR, FLASH_ERROR_WRP.
FLASH_Status FLASH_WaitForLastOperation(uint32_t Timeout)
Waits for a Flash operation to complete or a TIMEOUT to occur.
This function can be used for all STM32F10x devices, it is equivalent to FLASH_WaitForLastBank1Operation. For STM32F10X_XL devices this function waits for a Bank1 Flash operation to complete or a TIMEOUT to occur.For all other devices it waits for a Flash operation to complete or a TIMEOUT to occur. Timeout FLASH programming Timeout FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, FLASH_GetBank1Status, FLASH_BUSY, FLASH_TIMEOUT.
Referenced by FLASH_ErasePage, FLASH_EraseAllPages, FLASH_EraseOptionBytes, FLASH_ProgramWord, FLASH_ProgramHalfWord, FLASH_ProgramOptionByteData, FLASH_EnableWriteProtection, FLASH_ReadOutProtection, FLASH_UserOptionByteConfig.
void FLASH_UnlockBank1(void)
Unlocks the FLASH Bank1 Program Erase Controller.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices this function unlocks Bank1.For all other devices it unlocks Bank1 and it is equivalent to FLASH_Unlock function. None None
References FLASH, FLASH_KEY1, FLASH_KEY2.
void FLASH_LockBank1(void)
Locks the FLASH Bank1 Program Erase Controller.
this function can be used for all STM32F10x devices. For STM32F10X_XL devices this function Locks Bank1.For all other devices it Locks Bank1 and it is equivalent to FLASH_Lock function. None None
References FLASH, CR_LOCK_Set.
FLASH_Status FLASH_EraseAllBank1Pages(void)
Erases all Bank1 FLASH pages.
This function can be used for all STM32F10x devices. For STM32F10X_XL devices this function erases all Bank1 pages.For all other devices it erases all Bank1 pages and it is equivalent to FLASH_EraseAllPages function. None FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, FLASH_WaitForLastBank1Operation, EraseTimeout, FLASH, CR_MER_Set, CR_STRT_Set, CR_MER_Reset.
FLASH_Status FLASH_GetBank1Status(void)
Returns the FLASH Bank1 Status.
This function can be used for all STM32F10x devices, it is equivalent to FLASH_GetStatus function. None FLASH Status: The returned value can be: FLASH_BUSY, FLASH_ERROR_PG, FLASH_ERROR_WRP or FLASH_COMPLETE
References FLASH_COMPLETE, FLASH, FLASH_FLAG_BANK1_BSY, FLASH_FLAG_BSY, FLASH_BUSY, FLASH_FLAG_BANK1_PGERR, FLASH_ERROR_PG, FLASH_FLAG_BANK1_WRPRTERR, FLASH_ERROR_WRP.
Referenced by FLASH_WaitForLastOperation, FLASH_WaitForLastBank1Operation.
FLASH_Status FLASH_WaitForLastBank1Operation(uint32_t Timeout)
Waits for a Flash operation on Bank1 to complete or a TIMEOUT to occur.
This function can be used for all STM32F10x devices, it is equivalent to FLASH_WaitForLastOperation. Timeout FLASH programming Timeout FLASH Status: The returned value can be: FLASH_ERROR_PG, FLASH_ERROR_WRP, FLASH_COMPLETE or FLASH_TIMEOUT.
References FLASH_COMPLETE, FLASH_GetBank1Status, FLASH_FLAG_BANK1_BSY, FLASH_TIMEOUT.
Referenced by FLASH_ErasePage, FLASH_EraseAllPages, FLASH_EraseAllBank1Pages, FLASH_ProgramWord, FLASH_ProgramHalfWord.