stm32f10x_gpio.h
IS_GPIO_ALL_PERIPH
IS_GPIO_SPEED
IS_GPIO_MODE
IS_GPIO_BIT_ACTION
GPIO_Pin_0
Pin 0 selected
GPIO_Pin_1
Pin 1 selected
GPIO_Pin_2
Pin 2 selected
GPIO_Pin_3
Pin 3 selected
GPIO_Pin_4
Pin 4 selected
GPIO_Pin_5
Pin 5 selected
GPIO_Pin_6
Pin 6 selected
GPIO_Pin_7
Pin 7 selected
GPIO_Pin_8
Pin 8 selected
GPIO_Pin_9
Pin 9 selected
GPIO_Pin_10
Pin 10 selected
GPIO_Pin_11
Pin 11 selected
GPIO_Pin_12
Pin 12 selected
GPIO_Pin_13
Pin 13 selected
GPIO_Pin_14
Pin 14 selected
GPIO_Pin_15
Pin 15 selected
GPIO_Pin_All
All pins selected
IS_GPIO_PIN
IS_GET_GPIO_PIN
GPIO_Remap_SPI1
SPI1 Alternate Function mapping
GPIO_Remap_I2C1
I2C1 Alternate Function mapping
GPIO_Remap_USART1
USART1 Alternate Function mapping
GPIO_Remap_USART2
USART2 Alternate Function mapping
GPIO_PartialRemap_USART3
USART3 Partial Alternate Function mapping
GPIO_FullRemap_USART3
USART3 Full Alternate Function mapping
GPIO_PartialRemap_TIM1
TIM1 Partial Alternate Function mapping
GPIO_FullRemap_TIM1
TIM1 Full Alternate Function mapping
GPIO_PartialRemap1_TIM2
TIM2 Partial1 Alternate Function mapping
GPIO_PartialRemap2_TIM2
TIM2 Partial2 Alternate Function mapping
GPIO_FullRemap_TIM2
TIM2 Full Alternate Function mapping
GPIO_PartialRemap_TIM3
TIM3 Partial Alternate Function mapping
GPIO_FullRemap_TIM3
TIM3 Full Alternate Function mapping
GPIO_Remap_TIM4
TIM4 Alternate Function mapping
GPIO_Remap1_CAN1
CAN1 Alternate Function mapping
GPIO_Remap2_CAN1
CAN1 Alternate Function mapping
GPIO_Remap_PD01
PD01 Alternate Function mapping
GPIO_Remap_TIM5CH4_LSI
LSI connected to TIM5 Channel4 input capture for calibration
GPIO_Remap_ADC1_ETRGINJ
ADC1 External Trigger Injected Conversion remapping
GPIO_Remap_ADC1_ETRGREG
ADC1 External Trigger Regular Conversion remapping
GPIO_Remap_ADC2_ETRGINJ
ADC2 External Trigger Injected Conversion remapping
GPIO_Remap_ADC2_ETRGREG
ADC2 External Trigger Regular Conversion remapping
GPIO_Remap_ETH
Ethernet remapping (only for Connectivity line devices)
GPIO_Remap_CAN2
CAN2 remapping (only for Connectivity line devices)
GPIO_Remap_SWJ_NoJTRST
Full SWJ Enabled (JTAG-DP + SW-DP) but without JTRST
GPIO_Remap_SWJ_JTAGDisable
JTAG-DP Disabled and SW-DP Enabled
GPIO_Remap_SWJ_Disable
Full SWJ Disabled (JTAG-DP + SW-DP)
GPIO_Remap_SPI3
SPI3/I2S3 Alternate Function mapping (only for Connectivity line devices)
GPIO_Remap_TIM2ITR1_PTP_SOF
Ethernet PTP output or USB OTG SOF (Start of Frame) connected to TIM2 Internal Trigger 1 for calibration (only for Connectivity line devices)
GPIO_Remap_PTP_PPS
Ethernet MAC PPS_PTS output on PB05 (only for Connectivity line devices)
GPIO_Remap_TIM15
TIM15 Alternate Function mapping (only for Value line devices)
GPIO_Remap_TIM16
TIM16 Alternate Function mapping (only for Value line devices)
GPIO_Remap_TIM17
TIM17 Alternate Function mapping (only for Value line devices)
GPIO_Remap_CEC
CEC Alternate Function mapping (only for Value line devices)
GPIO_Remap_TIM1_DMA
TIM1 DMA requests mapping (only for Value line devices)
GPIO_Remap_TIM9
TIM9 Alternate Function mapping (only for XL-density devices)
GPIO_Remap_TIM10
TIM10 Alternate Function mapping (only for XL-density devices)
GPIO_Remap_TIM11
TIM11 Alternate Function mapping (only for XL-density devices)
GPIO_Remap_TIM13
TIM13 Alternate Function mapping (only for High density Value line and XL-density devices)
GPIO_Remap_TIM14
TIM14 Alternate Function mapping (only for High density Value line and XL-density devices)
GPIO_Remap_FSMC_NADV
FSMC_NADV Alternate Function mapping (only for High density Value line and XL-density devices)
GPIO_Remap_TIM67_DAC_DMA
TIM6/TIM7 and DAC DMA requests remapping (only for High density Value line devices)
GPIO_Remap_TIM12
TIM12 Alternate Function mapping (only for High density Value line devices)
GPIO_Remap_MISC
Miscellaneous Remap (DMA2 Channel5 Position and DAC Trigger remapping, only for High density Value line devices)
IS_GPIO_REMAP
GPIO_PortSourceGPIOA
GPIO_PortSourceGPIOB
GPIO_PortSourceGPIOC
GPIO_PortSourceGPIOD
GPIO_PortSourceGPIOE
GPIO_PortSourceGPIOF
GPIO_PortSourceGPIOG
IS_GPIO_EVENTOUT_PORT_SOURCE
IS_GPIO_EXTI_PORT_SOURCE
GPIO_PinSource0
GPIO_PinSource1
GPIO_PinSource2
GPIO_PinSource3
GPIO_PinSource4
GPIO_PinSource5
GPIO_PinSource6
GPIO_PinSource7
GPIO_PinSource8
GPIO_PinSource9
GPIO_PinSource10
GPIO_PinSource11
GPIO_PinSource12
GPIO_PinSource13
GPIO_PinSource14
GPIO_PinSource15
IS_GPIO_PIN_SOURCE
GPIO_ETH_MediaInterface_MII
GPIO_ETH_MediaInterface_RMII
IS_GPIO_ETH_MEDIA_INTERFACE
GPIOSpeed_TypeDef
GPIOMode_TypeDef
BitAction
void GPIO_DeInit(GPIO_TypeDef *GPIOx)
Deinitializes the GPIOx peripheral registers to their default reset values.
GPIOx where x can be (A..G) to select the GPIO peripheral. None
References assert_param, IS_GPIO_ALL_PERIPH, GPIOA, RCC_APB2PeriphResetCmd, RCC_APB2Periph_GPIOA, ENABLE, DISABLE, GPIOB, RCC_APB2Periph_GPIOB, GPIOC, RCC_APB2Periph_GPIOC, GPIOD, RCC_APB2Periph_GPIOD, GPIOE, RCC_APB2Periph_GPIOE, GPIOF, RCC_APB2Periph_GPIOF, GPIOG, RCC_APB2Periph_GPIOG.
void GPIO_AFIODeInit(void)
Deinitializes the Alternate Functions (remap, event control and EXTI configuration) registers to their default reset values.
None None
References RCC_APB2PeriphResetCmd, RCC_APB2Periph_AFIO, ENABLE, DISABLE.
void GPIO_Init(GPIO_TypeDef *GPIOx, GPIO_InitTypeDef *GPIO_InitStruct)
Initializes the GPIOx peripheral according to the specified parameters in the GPIO_InitStruct.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_InitStruct pointer to a GPIO_InitTypeDef structure that contains the configuration information for the specified GPIO peripheral. None
References assert_param, IS_GPIO_ALL_PERIPH, IS_GPIO_MODE, GPIO_InitTypeDef::GPIO_Mode, IS_GPIO_PIN, GPIO_InitTypeDef::GPIO_Pin, IS_GPIO_SPEED, GPIO_InitTypeDef::GPIO_Speed, GPIO_TypeDef::CRL, GPIO_Mode_IPD, GPIO_TypeDef::BRR, GPIO_Mode_IPU, GPIO_TypeDef::BSRR, GPIO_TypeDef::CRH.
Referenced by BlinkLed::powerUp.
void GPIO_StructInit(GPIO_InitTypeDef *GPIO_InitStruct)
Fills each GPIO_InitStruct member with its default value.
GPIO_InitStruct : pointer to a GPIO_InitTypeDef structure which will be initialized. None
References GPIO_InitTypeDef::GPIO_Pin, GPIO_Pin_All, GPIO_InitTypeDef::GPIO_Speed, GPIO_Speed_2MHz, GPIO_InitTypeDef::GPIO_Mode, GPIO_Mode_IN_FLOATING.
uint8_t GPIO_ReadInputDataBit(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Reads the specified input port pin.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bit to read. This parameter can be GPIO_Pin_x where x can be (0..15). The input port pin value.
References assert_param, IS_GPIO_ALL_PERIPH, IS_GET_GPIO_PIN, GPIO_TypeDef::IDR, Bit_RESET, Bit_SET.
uint16_t GPIO_ReadInputData(GPIO_TypeDef *GPIOx)
Reads the specified GPIO input data port.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO input data port value.
References assert_param, IS_GPIO_ALL_PERIPH, GPIO_TypeDef::IDR.
uint8_t GPIO_ReadOutputDataBit(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Reads the specified output data port bit.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bit to read. This parameter can be GPIO_Pin_x where x can be (0..15). The output port pin value.
References assert_param, IS_GPIO_ALL_PERIPH, IS_GET_GPIO_PIN, GPIO_TypeDef::ODR, Bit_RESET, Bit_SET.
uint16_t GPIO_ReadOutputData(GPIO_TypeDef *GPIOx)
Reads the specified GPIO output data port.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO output data port value.
References assert_param, IS_GPIO_ALL_PERIPH, GPIO_TypeDef::ODR.
void GPIO_SetBits(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Sets the selected data port bits.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bits to be written. This parameter can be any combination of GPIO_Pin_x where x can be (0..15). None
References assert_param, IS_GPIO_ALL_PERIPH, IS_GPIO_PIN, GPIO_TypeDef::BSRR.
Referenced by BlinkLed::__attribute__.
void GPIO_ResetBits(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Clears the selected data port bits.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bits to be written. This parameter can be any combination of GPIO_Pin_x where x can be (0..15). None
References assert_param, IS_GPIO_ALL_PERIPH, IS_GPIO_PIN, GPIO_TypeDef::BRR.
Referenced by BlinkLed::__attribute__.
void GPIO_WriteBit(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin, BitAction BitVal)
Sets or clears the selected data port bit.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bit to be written. This parameter can be one of GPIO_Pin_x where x can be (0..15). BitVal specifies the value to be written to the selected bit. This parameter can be one of the BitAction enum values: Bit_RESET: to clear the port pin Bit_SET: to set the port pin None
References assert_param, IS_GPIO_ALL_PERIPH, IS_GET_GPIO_PIN, IS_GPIO_BIT_ACTION, Bit_RESET, GPIO_TypeDef::BSRR, GPIO_TypeDef::BRR.
void GPIO_Write(GPIO_TypeDef *GPIOx, uint16_t PortVal)
Writes data to the specified GPIO data port.
GPIOx where x can be (A..G) to select the GPIO peripheral. PortVal specifies the value to be written to the port output data register. None
References assert_param, IS_GPIO_ALL_PERIPH, GPIO_TypeDef::ODR.
void GPIO_PinLockConfig(GPIO_TypeDef *GPIOx, uint16_t GPIO_Pin)
Locks GPIO Pins configuration registers.
GPIOx where x can be (A..G) to select the GPIO peripheral. GPIO_Pin specifies the port bit to be written. This parameter can be any combination of GPIO_Pin_x where x can be (0..15). None
References assert_param, IS_GPIO_ALL_PERIPH, IS_GPIO_PIN, GPIO_TypeDef::LCKR.
void GPIO_EventOutputConfig(uint8_t GPIO_PortSource, uint8_t GPIO_PinSource)
Selects the GPIO pin used as Event output.
GPIO_PortSource selects the GPIO port to be used as source for Event output. This parameter can be GPIO_PortSourceGPIOx where x can be (A..E). GPIO_PinSource specifies the pin for the Event output. This parameter can be GPIO_PinSourcex where x can be (0..15). None
References assert_param, IS_GPIO_EVENTOUT_PORT_SOURCE, IS_GPIO_PIN_SOURCE, AFIO, EVCR_PORTPINCONFIG_MASK.
void GPIO_EventOutputCmd(FunctionalState NewState)
Enables or disables the Event Output.
NewState new state of the Event output. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_FUNCTIONAL_STATE, __IO, EVCR_EVOE_BB.
void GPIO_PinRemapConfig(uint32_t GPIO_Remap, FunctionalState NewState)
Changes the mapping of the specified pin.
GPIO_Remap selects the pin to remap. This parameter can be one of the following values: GPIO_Remap_SPI1 : SPI1 Alternate Function mapping GPIO_Remap_I2C1 : I2C1 Alternate Function mapping GPIO_Remap_USART1 : USART1 Alternate Function mapping GPIO_Remap_USART2 : USART2 Alternate Function mapping GPIO_PartialRemap_USART3 : USART3 Partial Alternate Function mapping GPIO_FullRemap_USART3 : USART3 Full Alternate Function mapping GPIO_PartialRemap_TIM1 : TIM1 Partial Alternate Function mapping GPIO_FullRemap_TIM1 : TIM1 Full Alternate Function mapping GPIO_PartialRemap1_TIM2 : TIM2 Partial1 Alternate Function mapping GPIO_PartialRemap2_TIM2 : TIM2 Partial2 Alternate Function mapping GPIO_FullRemap_TIM2 : TIM2 Full Alternate Function mapping GPIO_PartialRemap_TIM3 : TIM3 Partial Alternate Function mapping GPIO_FullRemap_TIM3 : TIM3 Full Alternate Function mapping GPIO_Remap_TIM4 : TIM4 Alternate Function mapping GPIO_Remap1_CAN1 : CAN1 Alternate Function mapping GPIO_Remap2_CAN1 : CAN1 Alternate Function mapping GPIO_Remap_PD01 : PD01 Alternate Function mapping GPIO_Remap_TIM5CH4_LSI : LSI connected to TIM5 Channel4 input capture for calibration GPIO_Remap_ADC1_ETRGINJ : ADC1 External Trigger Injected Conversion remapping GPIO_Remap_ADC1_ETRGREG : ADC1 External Trigger Regular Conversion remapping GPIO_Remap_ADC2_ETRGINJ : ADC2 External Trigger Injected Conversion remapping GPIO_Remap_ADC2_ETRGREG : ADC2 External Trigger Regular Conversion remapping GPIO_Remap_ETH : Ethernet remapping (only for Connectivity line devices) GPIO_Remap_CAN2 : CAN2 remapping (only for Connectivity line devices) GPIO_Remap_SWJ_NoJTRST : Full SWJ Enabled (JTAG-DP + SW-DP) but without JTRST GPIO_Remap_SWJ_JTAGDisable : JTAG-DP Disabled and SW-DP Enabled GPIO_Remap_SWJ_Disable : Full SWJ Disabled (JTAG-DP + SW-DP) GPIO_Remap_SPI3 : SPI3/I2S3 Alternate Function mapping (only for Connectivity line devices) When the SPI3/I2S3 is remapped using this function, the SWJ is configured to Full SWJ Enabled (JTAG-DP + SW-DP) but without JTRST. GPIO_Remap_TIM2ITR1_PTP_SOF : Ethernet PTP output or USB OTG SOF (Start of Frame) connected to TIM2 Internal Trigger 1 for calibration (only for Connectivity line devices) If the GPIO_Remap_TIM2ITR1_PTP_SOF is enabled the TIM2 ITR1 is connected to Ethernet PTP output. When Reset TIM2 ITR1 is connected to USB OTG SOF output. GPIO_Remap_PTP_PPS : Ethernet MAC PPS_PTS output on PB05 (only for Connectivity line devices) GPIO_Remap_TIM15 : TIM15 Alternate Function mapping (only for Value line devices) GPIO_Remap_TIM16 : TIM16 Alternate Function mapping (only for Value line devices) GPIO_Remap_TIM17 : TIM17 Alternate Function mapping (only for Value line devices) GPIO_Remap_CEC : CEC Alternate Function mapping (only for Value line devices) GPIO_Remap_TIM1_DMA : TIM1 DMA requests mapping (only for Value line devices) GPIO_Remap_TIM9 : TIM9 Alternate Function mapping (only for XL-density devices) GPIO_Remap_TIM10 : TIM10 Alternate Function mapping (only for XL-density devices) GPIO_Remap_TIM11 : TIM11 Alternate Function mapping (only for XL-density devices) GPIO_Remap_TIM13 : TIM13 Alternate Function mapping (only for High density Value line and XL-density devices) GPIO_Remap_TIM14 : TIM14 Alternate Function mapping (only for High density Value line and XL-density devices) GPIO_Remap_FSMC_NADV : FSMC_NADV Alternate Function mapping (only for High density Value line and XL-density devices) GPIO_Remap_TIM67_DAC_DMA : TIM6/TIM7 and DAC DMA requests remapping (only for High density Value line devices) GPIO_Remap_TIM12 : TIM12 Alternate Function mapping (only for High density Value line devices) GPIO_Remap_MISC : Miscellaneous Remap (DMA2 Channel5 Position and DAC Trigger remapping, only for High density Value line devices) NewState new state of the port pin remapping. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_GPIO_REMAP, IS_FUNCTIONAL_STATE, AFIO, DBGAFR_POSITION_MASK, LSB_MASK, DBGAFR_LOCATION_MASK, DBGAFR_NUMBITS_MASK, DBGAFR_SWJCFG_MASK, DISABLE.
void GPIO_EXTILineConfig(uint8_t GPIO_PortSource, uint8_t GPIO_PinSource)
Selects the GPIO pin used as EXTI Line.
GPIO_PortSource selects the GPIO port to be used as source for EXTI lines. This parameter can be GPIO_PortSourceGPIOx where x can be (A..G). GPIO_PinSource specifies the EXTI line to be configured. This parameter can be GPIO_PinSourcex where x can be (0..15). None
References assert_param, IS_GPIO_EXTI_PORT_SOURCE, IS_GPIO_PIN_SOURCE, AFIO.
void GPIO_ETH_MediaInterfaceConfig(uint32_t GPIO_ETH_MediaInterface)
Selects the Ethernet media interface.
This function applies only to STM32 Connectivity line devices. GPIO_ETH_MediaInterface specifies the Media Interface mode. This parameter can be one of the following values: GPIO_ETH_MediaInterface_MII: MII mode GPIO_ETH_MediaInterface_RMII: RMII mode None
References assert_param, IS_GPIO_ETH_MEDIA_INTERFACE, __IO, MAPR_MII_RMII_SEL_BB.