stm32f10x_rtc.h
RTC_IT_OW
Overflow interrupt
RTC_IT_ALR
Alarm interrupt
RTC_IT_SEC
Second interrupt
IS_RTC_IT
IS_RTC_GET_IT
RTC_FLAG_RTOFF
RTC Operation OFF flag
RTC_FLAG_RSF
Registers Synchronized flag
RTC_FLAG_OW
Overflow flag
RTC_FLAG_ALR
Alarm flag
RTC_FLAG_SEC
Second flag
IS_RTC_CLEAR_FLAG
IS_RTC_GET_FLAG
IS_RTC_PRESCALER
void RTC_ITConfig(uint16_t RTC_IT, FunctionalState NewState)
Enables or disables the specified RTC interrupts.
RTC_IT specifies the RTC interrupts sources to be enabled or disabled. This parameter can be any combination of the following values: RTC_IT_OW: Overflow interrupt RTC_IT_ALR: Alarm interrupt RTC_IT_SEC: Second interrupt NewState new state of the specified RTC interrupts. This parameter can be: ENABLE or DISABLE. None
References assert_param, IS_RTC_IT, IS_FUNCTIONAL_STATE, DISABLE, RTC.
void RTC_EnterConfigMode(void)
Enters the RTC configuration mode.
None None
References RTC, RTC_CRL_CNF.
Referenced by RTC_SetCounter, RTC_SetPrescaler, RTC_SetAlarm.
void RTC_ExitConfigMode(void)
Exits from the RTC configuration mode.
None None
References RTC, RTC_CRL_CNF.
Referenced by RTC_SetCounter, RTC_SetPrescaler, RTC_SetAlarm.
uint32_t RTC_GetCounter(void)
Gets the RTC counter value.
None RTC counter value.
References RTC.
void RTC_SetCounter(uint32_t CounterValue)
Sets the RTC counter value.
CounterValue RTC counter new value. None
References RTC_EnterConfigMode, RTC, RTC_LSB_MASK, RTC_ExitConfigMode.
void RTC_SetPrescaler(uint32_t PrescalerValue)
Sets the RTC prescaler value.
PrescalerValue RTC prescaler new value. None
References assert_param, IS_RTC_PRESCALER, RTC_EnterConfigMode, RTC, PRLH_MSB_MASK, RTC_LSB_MASK, RTC_ExitConfigMode.
void RTC_SetAlarm(uint32_t AlarmValue)
Sets the RTC alarm value.
AlarmValue RTC alarm new value. None
References RTC_EnterConfigMode, RTC, RTC_LSB_MASK, RTC_ExitConfigMode.
uint32_t RTC_GetDivider(void)
Gets the RTC divider value.
None RTC Divider value.
References RTC.
void RTC_WaitForLastTask(void)
Waits until last write operation on RTC registers has finished.
This function must be called before any write to RTC registers. None None
References RTC, RTC_FLAG_RTOFF, RESET.
void RTC_WaitForSynchro(void)
Waits until the RTC registers (RTC_CNT, RTC_ALR and RTC_PRL) are synchronized with RTC APB clock.
This function must be called before any read operation after an APB reset or an APB clock stop. None None
References RTC, RTC_FLAG_RSF, RESET.
FlagStatus RTC_GetFlagStatus(uint16_t RTC_FLAG)
Checks whether the specified RTC flag is set or not.
RTC_FLAG specifies the flag to check. This parameter can be one the following values: RTC_FLAG_RTOFF: RTC Operation OFF flag RTC_FLAG_RSF: Registers Synchronized flag RTC_FLAG_OW: Overflow flag RTC_FLAG_ALR: Alarm flag RTC_FLAG_SEC: Second flag The new state of RTC_FLAG (SET or RESET).
References RESET, assert_param, IS_RTC_GET_FLAG, RTC, SET.
void RTC_ClearFlag(uint16_t RTC_FLAG)
Clears the RTC's pending flags.
RTC_FLAG specifies the flag to clear. This parameter can be any combination of the following values: RTC_FLAG_RSF: Registers Synchronized flag. This flag is cleared only after an APB reset or an APB Clock stop. RTC_FLAG_OW: Overflow flag RTC_FLAG_ALR: Alarm flag RTC_FLAG_SEC: Second flag None
References assert_param, IS_RTC_CLEAR_FLAG, RTC.
ITStatus RTC_GetITStatus(uint16_t RTC_IT)
Checks whether the specified RTC interrupt has occurred or not.
RTC_IT specifies the RTC interrupts sources to check. This parameter can be one of the following values: RTC_IT_OW: Overflow interrupt RTC_IT_ALR: Alarm interrupt RTC_IT_SEC: Second interrupt The new state of the RTC_IT (SET or RESET).
References RESET, assert_param, IS_RTC_GET_IT, RTC, SET.
void RTC_ClearITPendingBit(uint16_t RTC_IT)
Clears the RTC's interrupt pending bits.
RTC_IT specifies the interrupt pending bit to clear. This parameter can be any combination of the following values: RTC_IT_OW: Overflow interrupt RTC_IT_ALR: Alarm interrupt RTC_IT_SEC: Second interrupt None
References assert_param, IS_RTC_IT, RTC.