.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_cxx.cpp" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_cxx.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'diag/Trace\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fB__gnu_cxx\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__gnu_cxx::__attribute__\fP ((noreturn)) __verbose_terminate_handler()"
.br
.ti -1c
.RI "void \fB__gnu_cxx::__verbose_terminate_handler\fP ()"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((noreturn)) \fB__cxa_pure_virtual\fP()"
.br
.ti -1c
.RI "void \fB__cxa_pure_virtual\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((noreturn))"

.PP
Definition at line 13 of file _reset_hardware\&.c\&.
.SS "void __cxa_pure_virtual ()"

.PP
Definition at line 42 of file _cxx\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
