.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_exit.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_exit.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'diag/Trace\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__attribute__\fP ((noreturn))"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((weak, noreturn))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((noreturn))"

.PP
Definition at line 15 of file _exit\&.c\&.
.SS "void __attribute__ ((weak, noreturn))"

.PP
Definition at line 51 of file _exit\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
