.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_sbrk.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_sbrk.c
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "caddr_t \fB_sbrk\fP (int incr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "caddr_t _sbrk (int incr)"

.PP
Definition at line 22 of file _sbrk\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
