.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_startup.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/newlib/_startup.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOS_INCLUDE_STARTUP_GUARD_CHECKS\fP   (1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__initialize_args\fP (int *, char ***)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((noreturn))"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((always_inline))"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((section('\&.after_vectors'), noreturn, weak))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fB_sidata\fP"
.br
.ti -1c
.RI "unsigned int \fB_sdata\fP"
.br
.ti -1c
.RI "unsigned int \fB_edata\fP"
.br
.ti -1c
.RI "unsigned int \fB__bss_start__\fP"
.br
.ti -1c
.RI "unsigned int \fB__bss_end__\fP"
.br
.ti -1c
.RI "void(* \fB__preinit_array_start\fP [])(void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OS_INCLUDE_STARTUP_GUARD_CHECKS   (1)"

.PP
Definition at line 40 of file _startup\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((noreturn))"

.PP
Definition at line 84 of file _startup\&.c\&.
.SS "void __attribute__ ((always_inline))\fC [inline]\fP"

.PP
Definition at line 128 of file _startup\&.c\&.
.SS "void __attribute__ ((section('\&.after_vectors'), noreturn, weak))"

.PP
Definition at line 222 of file _startup\&.c\&.
.SS "void __initialize_args (int *, char ***)"

.SS "int main (int argc, char * argv[])"

.PP
Definition at line 64 of file main\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned int __bss_end__"

.SS "unsigned int __bss_start__"

.SS "void(* __preinit_array_start[])(void)"

.SS "unsigned int _edata"

.SS "unsigned int _sdata"

.SS "unsigned int _sidata"

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
