.TH "ADC_interrupts_definition" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ADC_interrupts_definition
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADC_IT_EOC\fP   ((uint16_t)0x0220)"
.br
.ti -1c
.RI "#define \fBADC_IT_AWD\fP   ((uint16_t)0x0140)"
.br
.ti -1c
.RI "#define \fBADC_IT_JEOC\fP   ((uint16_t)0x0480)"
.br
.ti -1c
.RI "#define \fBIS_ADC_IT\fP(IT)   ((((IT) & (uint16_t)0xF81F) == 0x00) && ((IT) != 0x00))"
.br
.ti -1c
.RI "#define \fBIS_ADC_GET_IT\fP(IT)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_IT_AWD   ((uint16_t)0x0140)"

.PP
Definition at line 320 of file stm32f10x_adc\&.h\&.
.SS "#define ADC_IT_EOC   ((uint16_t)0x0220)"

.PP
Definition at line 319 of file stm32f10x_adc\&.h\&.
.SS "#define ADC_IT_JEOC   ((uint16_t)0x0480)"

.PP
Definition at line 321 of file stm32f10x_adc\&.h\&.
.SS "#define IS_ADC_GET_IT(IT)"
\fBValue:\fP
.PP
.nf
(((IT) == ADC_IT_EOC) || ((IT) == ADC_IT_AWD) || \
                           ((IT) == ADC_IT_JEOC))
.fi
.PP
Definition at line 325 of file stm32f10x_adc\&.h\&.
.SS "#define IS_ADC_IT(IT)   ((((IT) & (uint16_t)0xF81F) == 0x00) && ((IT) != 0x00))"

.PP
Definition at line 323 of file stm32f10x_adc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
