.TH "AFIO_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AFIO_TypeDef \- Alternate Function I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEVCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEXTICR\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMAPR2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Alternate Function I/O\&. 
.PP
Definition at line 1016 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t AFIO_TypeDef::EVCR"

.PP
Definition at line 1018 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t AFIO_TypeDef::EXTICR[4]"

.PP
Definition at line 1020 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t AFIO_TypeDef::MAPR"

.PP
Definition at line 1019 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t AFIO_TypeDef::MAPR2"

.PP
Definition at line 1022 of file stm32f10x\&.h\&.
.SS "uint32_t AFIO_TypeDef::RESERVED0"

.PP
Definition at line 1021 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
