.TH "AHB_peripheral" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AHB_peripheral
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_AHBPeriph_DMA1\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_DMA2\fP   ((uint32_t)0x00000002)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_SRAM\fP   ((uint32_t)0x00000004)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_FLITF\fP   ((uint32_t)0x00000010)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_CRC\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_FSMC\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBRCC_AHBPeriph_SDIO\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBIS_RCC_AHB_PERIPH\fP(PERIPH)   ((((PERIPH) & 0xFFFFFAA8) == 0x00) && ((PERIPH) != 0x00))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_AHB_PERIPH(PERIPH)   ((((PERIPH) & 0xFFFFFAA8) == 0x00) && ((PERIPH) != 0x00))"

.PP
Definition at line 479 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_CRC   ((uint32_t)0x00000040)"

.PP
Definition at line 474 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_DMA1   ((uint32_t)0x00000001)"

.PP
Definition at line 470 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_DMA2   ((uint32_t)0x00000002)"

.PP
Definition at line 471 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_FLITF   ((uint32_t)0x00000010)"

.PP
Definition at line 473 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_FSMC   ((uint32_t)0x00000100)"

.PP
Definition at line 477 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_SDIO   ((uint32_t)0x00000400)"

.PP
Definition at line 478 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_AHBPeriph_SRAM   ((uint32_t)0x00000004)"

.PP
Definition at line 472 of file stm32f10x_rcc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
