.TH "APB2_peripheral" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
APB2_peripheral
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_APB2Periph_AFIO\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOA\fP   ((uint32_t)0x00000004)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOB\fP   ((uint32_t)0x00000008)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOC\fP   ((uint32_t)0x00000010)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOD\fP   ((uint32_t)0x00000020)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOE\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOF\fP   ((uint32_t)0x00000080)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_GPIOG\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC1\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC2\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM1\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_SPI1\fP   ((uint32_t)0x00001000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM8\fP   ((uint32_t)0x00002000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_USART1\fP   ((uint32_t)0x00004000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_ADC3\fP   ((uint32_t)0x00008000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM15\fP   ((uint32_t)0x00010000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM16\fP   ((uint32_t)0x00020000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM17\fP   ((uint32_t)0x00040000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM9\fP   ((uint32_t)0x00080000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM10\fP   ((uint32_t)0x00100000)"
.br
.ti -1c
.RI "#define \fBRCC_APB2Periph_TIM11\fP   ((uint32_t)0x00200000)"
.br
.ti -1c
.RI "#define \fBIS_RCC_APB2_PERIPH\fP(PERIPH)   ((((PERIPH) & 0xFFC00002) == 0x00) && ((PERIPH) != 0x00))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_APB2_PERIPH(PERIPH)   ((((PERIPH) & 0xFFC00002) == 0x00) && ((PERIPH) != 0x00))"

.PP
Definition at line 519 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_ADC1   ((uint32_t)0x00000200)"

.PP
Definition at line 505 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_ADC2   ((uint32_t)0x00000400)"

.PP
Definition at line 506 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_ADC3   ((uint32_t)0x00008000)"

.PP
Definition at line 511 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_AFIO   ((uint32_t)0x00000001)"

.PP
Definition at line 497 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOA   ((uint32_t)0x00000004)"

.PP
Definition at line 498 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOB   ((uint32_t)0x00000008)"

.PP
Definition at line 499 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOC   ((uint32_t)0x00000010)"

.PP
Definition at line 500 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOD   ((uint32_t)0x00000020)"

.PP
Definition at line 501 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOE   ((uint32_t)0x00000040)"

.PP
Definition at line 502 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOF   ((uint32_t)0x00000080)"

.PP
Definition at line 503 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_GPIOG   ((uint32_t)0x00000100)"

.PP
Definition at line 504 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_SPI1   ((uint32_t)0x00001000)"

.PP
Definition at line 508 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM1   ((uint32_t)0x00000800)"

.PP
Definition at line 507 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM10   ((uint32_t)0x00100000)"

.PP
Definition at line 516 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM11   ((uint32_t)0x00200000)"

.PP
Definition at line 517 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM15   ((uint32_t)0x00010000)"

.PP
Definition at line 512 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM16   ((uint32_t)0x00020000)"

.PP
Definition at line 513 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM17   ((uint32_t)0x00040000)"

.PP
Definition at line 514 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM8   ((uint32_t)0x00002000)"

.PP
Definition at line 509 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_TIM9   ((uint32_t)0x00080000)"

.PP
Definition at line 515 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_APB2Periph_USART1   ((uint32_t)0x00004000)"

.PP
Definition at line 510 of file stm32f10x_rcc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
