.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/arm_common_tables.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/arm_common_tables.h
.SH SYNOPSIS
.br
.PP
\fC#include 'arm_math\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtwiddleCoef\fP   \fBtwiddleCoef_4096\fP"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE__16_TABLE_LENGTH\fP   ((uint16_t)20  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE__32_TABLE_LENGTH\fP   ((uint16_t)48  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE__64_TABLE_LENGTH\fP   ((uint16_t)56  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_128_TABLE_LENGTH\fP   ((uint16_t)208 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_256_TABLE_LENGTH\fP   ((uint16_t)440 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_512_TABLE_LENGTH\fP   ((uint16_t)448 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE1024_TABLE_LENGTH\fP   ((uint16_t)1800)"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE2048_TABLE_LENGTH\fP   ((uint16_t)3808)"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE4096_TABLE_LENGTH\fP   ((uint16_t)4032)"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED___16_TABLE_LENGTH\fP   ((uint16_t)12  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED___32_TABLE_LENGTH\fP   ((uint16_t)24  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED___64_TABLE_LENGTH\fP   ((uint16_t)56  )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED__128_TABLE_LENGTH\fP   ((uint16_t)112 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED__256_TABLE_LENGTH\fP   ((uint16_t)240 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED__512_TABLE_LENGTH\fP   ((uint16_t)480 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED_1024_TABLE_LENGTH\fP   ((uint16_t)992 )"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED_2048_TABLE_LENGTH\fP   ((uint16_t)1984)"
.br
.ti -1c
.RI "#define \fBARMBITREVINDEXTABLE_FIXED_4096_TABLE_LENGTH\fP   ((uint16_t)4032)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const uint16_t \fBarmBitRevTable\fP [1024]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBarmRecipTableQ15\fP [64]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBarmRecipTableQ31\fP [64]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_16\fP [32]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_32\fP [64]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_64\fP [128]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_128\fP [256]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_256\fP [512]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_512\fP [1024]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_1024\fP [2048]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_2048\fP [4096]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_4096\fP [8192]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_16_q31\fP [24]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_32_q31\fP [48]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_64_q31\fP [96]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_128_q31\fP [192]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_256_q31\fP [384]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_512_q31\fP [768]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_1024_q31\fP [1536]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_2048_q31\fP [3072]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBtwiddleCoef_4096_q31\fP [6144]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_16_q15\fP [24]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_32_q15\fP [48]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_64_q15\fP [96]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_128_q15\fP [192]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_256_q15\fP [384]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_512_q15\fP [768]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_1024_q15\fP [1536]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_2048_q15\fP [3072]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBtwiddleCoef_4096_q15\fP [6144]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_32\fP [32]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_64\fP [64]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_128\fP [128]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_256\fP [256]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_512\fP [512]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_1024\fP [1024]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_2048\fP [2048]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBtwiddleCoef_rfft_4096\fP [4096]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable16\fP [\fBARMBITREVINDEXTABLE__16_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable32\fP [\fBARMBITREVINDEXTABLE__32_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable64\fP [\fBARMBITREVINDEXTABLE__64_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable128\fP [\fBARMBITREVINDEXTABLE_128_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable256\fP [\fBARMBITREVINDEXTABLE_256_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable512\fP [\fBARMBITREVINDEXTABLE_512_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable1024\fP [\fBARMBITREVINDEXTABLE1024_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable2048\fP [\fBARMBITREVINDEXTABLE2048_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable4096\fP [\fBARMBITREVINDEXTABLE4096_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_16\fP [\fBARMBITREVINDEXTABLE_FIXED___16_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_32\fP [\fBARMBITREVINDEXTABLE_FIXED___32_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_64\fP [\fBARMBITREVINDEXTABLE_FIXED___64_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_128\fP [\fBARMBITREVINDEXTABLE_FIXED__128_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_256\fP [\fBARMBITREVINDEXTABLE_FIXED__256_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_512\fP [\fBARMBITREVINDEXTABLE_FIXED__512_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_1024\fP [\fBARMBITREVINDEXTABLE_FIXED_1024_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_2048\fP [\fBARMBITREVINDEXTABLE_FIXED_2048_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const uint16_t \fBarmBitRevIndexTable_fixed_4096\fP [\fBARMBITREVINDEXTABLE_FIXED_4096_TABLE_LENGTH\fP]"
.br
.ti -1c
.RI "const \fBfloat32_t\fP \fBsinTable_f32\fP [\fBFAST_MATH_TABLE_SIZE\fP+1]"
.br
.ti -1c
.RI "const \fBq31_t\fP \fBsinTable_q31\fP [\fBFAST_MATH_TABLE_SIZE\fP+1]"
.br
.ti -1c
.RI "const \fBq15_t\fP \fBsinTable_q15\fP [\fBFAST_MATH_TABLE_SIZE\fP+1]"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARMBITREVINDEXTABLE1024_TABLE_LENGTH   ((uint16_t)1800)"

.PP
Definition at line 96 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE2048_TABLE_LENGTH   ((uint16_t)3808)"

.PP
Definition at line 97 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE4096_TABLE_LENGTH   ((uint16_t)4032)"

.PP
Definition at line 98 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_128_TABLE_LENGTH   ((uint16_t)208 )"

.PP
Definition at line 93 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_256_TABLE_LENGTH   ((uint16_t)440 )"

.PP
Definition at line 94 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_512_TABLE_LENGTH   ((uint16_t)448 )"

.PP
Definition at line 95 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE__16_TABLE_LENGTH   ((uint16_t)20  )"

.PP
Definition at line 90 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE__32_TABLE_LENGTH   ((uint16_t)48  )"

.PP
Definition at line 91 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE__64_TABLE_LENGTH   ((uint16_t)56  )"

.PP
Definition at line 92 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED_1024_TABLE_LENGTH   ((uint16_t)992 )"

.PP
Definition at line 117 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED_2048_TABLE_LENGTH   ((uint16_t)1984)"

.PP
Definition at line 118 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED_4096_TABLE_LENGTH   ((uint16_t)4032)"

.PP
Definition at line 119 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED__128_TABLE_LENGTH   ((uint16_t)112 )"

.PP
Definition at line 114 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED__256_TABLE_LENGTH   ((uint16_t)240 )"

.PP
Definition at line 115 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED__512_TABLE_LENGTH   ((uint16_t)480 )"

.PP
Definition at line 116 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED___16_TABLE_LENGTH   ((uint16_t)12  )"

.PP
Definition at line 111 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED___32_TABLE_LENGTH   ((uint16_t)24  )"

.PP
Definition at line 112 of file arm_common_tables\&.h\&.
.SS "#define ARMBITREVINDEXTABLE_FIXED___64_TABLE_LENGTH   ((uint16_t)56  )"

.PP
Definition at line 113 of file arm_common_tables\&.h\&.
.SS "#define twiddleCoef   \fBtwiddleCoef_4096\fP"

.PP
Definition at line 60 of file arm_common_tables\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const uint16_t armBitRevIndexTable1024[\fBARMBITREVINDEXTABLE1024_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable128[\fBARMBITREVINDEXTABLE_128_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable16[\fBARMBITREVINDEXTABLE__16_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable2048[\fBARMBITREVINDEXTABLE2048_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable256[\fBARMBITREVINDEXTABLE_256_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable32[\fBARMBITREVINDEXTABLE__32_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable4096[\fBARMBITREVINDEXTABLE4096_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable512[\fBARMBITREVINDEXTABLE_512_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable64[\fBARMBITREVINDEXTABLE__64_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_1024[\fBARMBITREVINDEXTABLE_FIXED_1024_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_128[\fBARMBITREVINDEXTABLE_FIXED__128_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_16[\fBARMBITREVINDEXTABLE_FIXED___16_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_2048[\fBARMBITREVINDEXTABLE_FIXED_2048_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_256[\fBARMBITREVINDEXTABLE_FIXED__256_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_32[\fBARMBITREVINDEXTABLE_FIXED___32_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_4096[\fBARMBITREVINDEXTABLE_FIXED_4096_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_512[\fBARMBITREVINDEXTABLE_FIXED__512_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevIndexTable_fixed_64[\fBARMBITREVINDEXTABLE_FIXED___64_TABLE_LENGTH\fP]"

.SS "const uint16_t armBitRevTable[1024]"

.SS "const \fBq15_t\fP armRecipTableQ15[64]"

.SS "const \fBq31_t\fP armRecipTableQ31[64]"

.SS "const \fBfloat32_t\fP sinTable_f32[\fBFAST_MATH_TABLE_SIZE\fP+1]"

.SS "const \fBq15_t\fP sinTable_q15[\fBFAST_MATH_TABLE_SIZE\fP+1]"

.SS "const \fBq31_t\fP sinTable_q31[\fBFAST_MATH_TABLE_SIZE\fP+1]"

.SS "const \fBfloat32_t\fP twiddleCoef_1024[2048]"

.SS "const \fBq15_t\fP twiddleCoef_1024_q15[1536]"

.SS "const \fBq31_t\fP twiddleCoef_1024_q31[1536]"

.SS "const \fBfloat32_t\fP twiddleCoef_128[256]"

.SS "const \fBq15_t\fP twiddleCoef_128_q15[192]"

.SS "const \fBq31_t\fP twiddleCoef_128_q31[192]"

.SS "const \fBfloat32_t\fP twiddleCoef_16[32]"

.SS "const \fBq15_t\fP twiddleCoef_16_q15[24]"

.SS "const \fBq31_t\fP twiddleCoef_16_q31[24]"

.SS "const \fBfloat32_t\fP twiddleCoef_2048[4096]"

.SS "const \fBq15_t\fP twiddleCoef_2048_q15[3072]"

.SS "const \fBq31_t\fP twiddleCoef_2048_q31[3072]"

.SS "const \fBfloat32_t\fP twiddleCoef_256[512]"

.SS "const \fBq15_t\fP twiddleCoef_256_q15[384]"

.SS "const \fBq31_t\fP twiddleCoef_256_q31[384]"

.SS "const \fBfloat32_t\fP twiddleCoef_32[64]"

.SS "const \fBq15_t\fP twiddleCoef_32_q15[48]"

.SS "const \fBq31_t\fP twiddleCoef_32_q31[48]"

.SS "const \fBfloat32_t\fP twiddleCoef_4096[8192]"

.SS "const \fBq15_t\fP twiddleCoef_4096_q15[6144]"

.SS "const \fBq31_t\fP twiddleCoef_4096_q31[6144]"

.SS "const \fBfloat32_t\fP twiddleCoef_512[1024]"

.SS "const \fBq15_t\fP twiddleCoef_512_q15[768]"

.SS "const \fBq31_t\fP twiddleCoef_512_q31[768]"

.SS "const \fBfloat32_t\fP twiddleCoef_64[128]"

.SS "const \fBq15_t\fP twiddleCoef_64_q15[96]"

.SS "const \fBq31_t\fP twiddleCoef_64_q31[96]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_1024[1024]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_128[128]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_2048[2048]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_256[256]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_32[32]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_4096[4096]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_512[512]"

.SS "const \fBfloat32_t\fP twiddleCoef_rfft_64[64]"

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
