.TH "arm_biquad_casd_df1_inst_q15" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_biquad_casd_df1_inst_q15 \- Instance structure for the Q15 Biquad cascade filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int8_t \fBnumStages\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBq15_t\fP * \fBpCoeffs\fP"
.br
.ti -1c
.RI "int8_t \fBpostShift\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q15 Biquad cascade filter\&. 
.PP
Definition at line 1220 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int8_t arm_biquad_casd_df1_inst_q15::numStages"
number of 2nd order stages in the filter\&. Overall order is 2*numStages\&. 
.PP
Definition at line 1222 of file arm_math\&.h\&.
.SS "\fBq15_t\fP* arm_biquad_casd_df1_inst_q15::pCoeffs"
Points to the array of coefficients\&. The array is of length 5*numStages\&. 
.PP
Definition at line 1224 of file arm_math\&.h\&.
.SS "int8_t arm_biquad_casd_df1_inst_q15::postShift"
Additional shift, in bits, applied to each output sample\&. 
.PP
Definition at line 1225 of file arm_math\&.h\&.
.SS "\fBq15_t\fP* arm_biquad_casd_df1_inst_q15::pState"
Points to the array of state coefficients\&. The array is of length 4*numStages\&. 
.PP
Definition at line 1223 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
