.TH "arm_dct4_instance_q31" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_dct4_instance_q31 \- Instance structure for the Q31 DCT4/IDCT4 function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBN\fP"
.br
.ti -1c
.RI "uint16_t \fBNby2\fP"
.br
.ti -1c
.RI "\fBq31_t\fP \fBnormalize\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpTwiddle\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpCosFactor\fP"
.br
.ti -1c
.RI "\fBarm_rfft_instance_q31\fP * \fBpRfft\fP"
.br
.ti -1c
.RI "\fBarm_cfft_radix4_instance_q31\fP * \fBpCfft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q31 DCT4/IDCT4 function\&. 
.PP
Definition at line 2300 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t arm_dct4_instance_q31::N"
length of the DCT4\&. 
.PP
Definition at line 2302 of file arm_math\&.h\&.
.SS "uint16_t arm_dct4_instance_q31::Nby2"
half of the length of the DCT4\&. 
.PP
Definition at line 2303 of file arm_math\&.h\&.
.SS "\fBq31_t\fP arm_dct4_instance_q31::normalize"
normalizing factor\&. 
.PP
Definition at line 2304 of file arm_math\&.h\&.
.SS "\fBarm_cfft_radix4_instance_q31\fP* arm_dct4_instance_q31::pCfft"
points to the complex FFT instance\&. 
.PP
Definition at line 2308 of file arm_math\&.h\&.
.SS "\fBq31_t\fP* arm_dct4_instance_q31::pCosFactor"
points to the cosFactor table\&. 
.PP
Definition at line 2306 of file arm_math\&.h\&.
.SS "\fBarm_rfft_instance_q31\fP* arm_dct4_instance_q31::pRfft"
points to the real FFT instance\&. 
.PP
Definition at line 2307 of file arm_math\&.h\&.
.SS "\fBq31_t\fP* arm_dct4_instance_q31::pTwiddle"
points to the twiddle factor table\&. 
.PP
Definition at line 2305 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
