.TH "arm_matrix_instance_q31" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_matrix_instance_q31 \- Instance structure for the Q31 matrix structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBnumRows\fP"
.br
.ti -1c
.RI "uint16_t \fBnumCols\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the Q31 matrix structure\&. 
.PP
Definition at line 1400 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t arm_matrix_instance_q31::numCols"
number of columns of the matrix\&. 
.PP
Definition at line 1403 of file arm_math\&.h\&.
.SS "uint16_t arm_matrix_instance_q31::numRows"
number of rows of the matrix\&. 
.PP
Definition at line 1402 of file arm_math\&.h\&.
.SS "\fBq31_t\fP* arm_matrix_instance_q31::pData"
points to the data of the matrix\&. 
.PP
Definition at line 1404 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
