.TH "arm_biquad_cas_df1_32x64_ins_q31" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_biquad_cas_df1_32x64_ins_q31 \- Instance structure for the high precision Q31 Biquad cascade filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBnumStages\fP"
.br
.ti -1c
.RI "\fBq63_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBq31_t\fP * \fBpCoeffs\fP"
.br
.ti -1c
.RI "uint8_t \fBpostShift\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the high precision Q31 Biquad cascade filter\&. 
.PP
Definition at line 3568 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t arm_biquad_cas_df1_32x64_ins_q31::numStages"
number of 2nd order stages in the filter\&. Overall order is 2*numStages\&. 
.PP
Definition at line 3570 of file arm_math\&.h\&.
.SS "\fBq31_t\fP* arm_biquad_cas_df1_32x64_ins_q31::pCoeffs"
points to the array of coefficients\&. The array is of length 5*numStages\&. 
.PP
Definition at line 3572 of file arm_math\&.h\&.
.SS "uint8_t arm_biquad_cas_df1_32x64_ins_q31::postShift"
additional shift, in bits, applied to each output sample\&. 
.PP
Definition at line 3573 of file arm_math\&.h\&.
.SS "\fBq63_t\fP* arm_biquad_cas_df1_32x64_ins_q31::pState"
points to the array of state coefficients\&. The array is of length 4*numStages\&. 
.PP
Definition at line 3571 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
