.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/arm_const_structs.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/arm_const_structs.h
.SH SYNOPSIS
.br
.PP
\fC#include 'arm_math\&.h'\fP
.br
\fC#include 'arm_common_tables\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len16\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len32\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len64\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len128\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len256\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len512\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len1024\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len2048\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_f32\fP \fBarm_cfft_sR_f32_len4096\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len16\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len32\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len64\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len128\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len256\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len512\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len1024\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len2048\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q31\fP \fBarm_cfft_sR_q31_len4096\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len16\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len32\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len64\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len128\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len256\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len512\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len1024\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len2048\fP"
.br
.ti -1c
.RI "const \fBarm_cfft_instance_q15\fP \fBarm_cfft_sR_q15_len4096\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len1024"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len128"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len16"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len2048"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len256"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len32"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len4096"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len512"

.SS "const \fBarm_cfft_instance_f32\fP arm_cfft_sR_f32_len64"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len1024"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len128"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len16"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len2048"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len256"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len32"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len4096"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len512"

.SS "const \fBarm_cfft_instance_q15\fP arm_cfft_sR_q15_len64"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len1024"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len128"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len16"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len2048"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len256"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len32"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len4096"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len512"

.SS "const \fBarm_cfft_instance_q31\fP arm_cfft_sR_q31_len64"

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
