.TH "arm_pid_instance_f32" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_pid_instance_f32 \- Instance structure for the floating-point PID Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32_t\fP \fBA0\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBA1\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBA2\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBstate\fP [3]"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKp\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKi\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP \fBKd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the floating-point PID Control\&. 
.PP
Definition at line 1769 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat32_t\fP arm_pid_instance_f32::A0"
The derived gain, A0 = Kp + Ki + Kd \&. 
.PP
Definition at line 1771 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::A1"
The derived gain, A1 = -Kp - 2Kd\&. 
.PP
Definition at line 1772 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::A2"
The derived gain, A2 = Kd \&. 
.PP
Definition at line 1773 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::Kd"
The derivative gain\&. 
.PP
Definition at line 1777 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::Ki"
The integral gain\&. 
.PP
Definition at line 1776 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::Kp"
The proportional gain\&. 
.PP
Definition at line 1775 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP arm_pid_instance_f32::state[3]"
The state array of length 3\&. 
.PP
Definition at line 1774 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
