.TH "arm_iir_lattice_instance_f32" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arm_iir_lattice_instance_f32 \- Instance structure for the floating-point IIR lattice filter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arm_math\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBnumStages\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpState\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpkCoeffs\fP"
.br
.ti -1c
.RI "\fBfloat32_t\fP * \fBpvCoeffs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Instance structure for the floating-point IIR lattice filter\&. 
.PP
Definition at line 3860 of file arm_math\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t arm_iir_lattice_instance_f32::numStages"
number of stages in the filter\&. 
.PP
Definition at line 3862 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP* arm_iir_lattice_instance_f32::pkCoeffs"
points to the reflection coefficient array\&. The array is of length numStages\&. 
.PP
Definition at line 3864 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP* arm_iir_lattice_instance_f32::pState"
points to the state variable array\&. The array is of length numStages+blockSize\&. 
.PP
Definition at line 3863 of file arm_math\&.h\&.
.SS "\fBfloat32_t\fP* arm_iir_lattice_instance_f32::pvCoeffs"
points to the ladder coefficient array\&. The array is of length numStages+1\&. 
.PP
Definition at line 3865 of file arm_math\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
