.TH "BKP_Exported_Constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BKP_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTamper_Pin_active_level\fP"
.br
.ti -1c
.RI "\fBRTC_output_source_to_output_on_the_Tamper_pin\fP"
.br
.ti -1c
.RI "\fBData_Backup_Register\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
