.TH "BlinkLed" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlinkLed
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BlinkLed\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlinkLed\fP ()=default"
.br
.ti -1c
.RI "void \fBpowerUp\fP ()"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((always_inline)) turnOn()"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((always_inline)) turnOff()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file BlinkLed\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BlinkLed::BlinkLed ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void BlinkLed::__attribute__ ((always_inline))\fC [inline]\fP"

.PP
Definition at line 37 of file BlinkLed\&.h\&.
.SS "void BlinkLed::__attribute__ ((always_inline))\fC [inline]\fP"

.PP
Definition at line 50 of file BlinkLed\&.h\&.
.SS "void BlinkLed::powerUp ()"

.PP
Definition at line 11 of file BlinkLed\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
