.TH "Break_Polarity" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Break_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_BreakPolarity_Low\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_BreakPolarity_High\fP   ((uint16_t)0x2000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_BREAK_POLARITY\fP(POLARITY)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_BREAK_POLARITY(POLARITY)"
\fBValue:\fP
.PP
.nf
(((POLARITY) == TIM_BreakPolarity_Low) || \
                                         ((POLARITY) == TIM_BreakPolarity_High))
.fi
.PP
Definition at line 473 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_BreakPolarity_High   ((uint16_t)0x2000)"

.PP
Definition at line 472 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_BreakPolarity_Low   ((uint16_t)0x0000)"

.PP
Definition at line 471 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
