.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph Directory Reference" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmisc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the miscellaneous firmware library functions (add-on to CMSIS functions)\&. "
.ti -1c
.RI "file \fBstm32f10x_adc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the ADC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_bkp\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the BKP firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_can\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the CAN firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_cec\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the CEC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_crc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the CRC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_dac\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the DAC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_dbgmcu\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the DBGMCU firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_dma\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the DMA firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_exti\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the EXTI firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_flash\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the FLASH firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_fsmc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the FSMC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_gpio\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the GPIO firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_i2c\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the I2C firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_iwdg\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the IWDG firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_pwr\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the PWR firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_rcc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the RCC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_rtc\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the RTC firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_sdio\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the SDIO firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_spi\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the SPI firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_tim\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the TIM firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_usart\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the USART firmware library\&. "
.ti -1c
.RI "file \fBstm32f10x_wwdg\&.h\fP"
.br
.RI "This file contains all the functions prototypes for the WWDG firmware library\&. "
.in -1c
