.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph Directory Reference" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmisc\&.c\fP"
.br
.RI "This file provides all the miscellaneous firmware functions (add-on to CMSIS functions)\&. "
.ti -1c
.RI "file \fBstm32f10x_adc\&.c\fP"
.br
.RI "This file provides all the ADC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_bkp\&.c\fP"
.br
.RI "This file provides all the BKP firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_can\&.c\fP"
.br
.RI "This file provides all the CAN firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_cec\&.c\fP"
.br
.RI "This file provides all the CEC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_crc\&.c\fP"
.br
.RI "This file provides all the CRC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_dac\&.c\fP"
.br
.RI "This file provides all the DAC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_dbgmcu\&.c\fP"
.br
.RI "This file provides all the DBGMCU firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_dma\&.c\fP"
.br
.RI "This file provides all the DMA firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_exti\&.c\fP"
.br
.RI "This file provides all the EXTI firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_flash\&.c\fP"
.br
.RI "This file provides all the FLASH firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_fsmc\&.c\fP"
.br
.RI "This file provides all the FSMC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_gpio\&.c\fP"
.br
.RI "This file provides all the GPIO firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_i2c\&.c\fP"
.br
.RI "This file provides all the I2C firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_iwdg\&.c\fP"
.br
.RI "This file provides all the IWDG firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_pwr\&.c\fP"
.br
.RI "This file provides all the PWR firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_rcc\&.c\fP"
.br
.RI "This file provides all the RCC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_rtc\&.c\fP"
.br
.RI "This file provides all the RTC firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_sdio\&.c\fP"
.br
.RI "This file provides all the SDIO firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_spi\&.c\fP"
.br
.RI "This file provides all the SPI firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_tim\&.c\fP"
.br
.RI "This file provides all the TIM firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_usart\&.c\fP"
.br
.RI "This file provides all the USART firmware functions\&. "
.ti -1c
.RI "file \fBstm32f10x_wwdg\&.c\fP"
.br
.RI "This file provides all the WWDG firmware functions\&. "
.in -1c
