.TH "CAN_Error_Code_constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Error_Code_constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAN_ErrorCode_NoErr\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_StuffErr\fP   ((uint8_t)0x10)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_FormErr\fP   ((uint8_t)0x20)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_ACKErr\fP   ((uint8_t)0x30)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_BitRecessiveErr\fP   ((uint8_t)0x40)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_BitDominantErr\fP   ((uint8_t)0x50)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_CRCErr\fP   ((uint8_t)0x60)"
.br
.ti -1c
.RI "#define \fBCAN_ErrorCode_SoftwareSetErr\fP   ((uint8_t)0x70)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_ErrorCode_ACKErr   ((uint8_t)0x30)"
Acknowledgment Error 
.PP
Definition at line 494 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_BitDominantErr   ((uint8_t)0x50)"
Bit Dominant Error 
.PP
Definition at line 496 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_BitRecessiveErr   ((uint8_t)0x40)"
Bit Recessive Error 
.PP
Definition at line 495 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_CRCErr   ((uint8_t)0x60)"
CRC Error 
.PP
Definition at line 497 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_FormErr   ((uint8_t)0x20)"
Form Error 
.PP
Definition at line 493 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_NoErr   ((uint8_t)0x00)"
No Error 
.PP
Definition at line 491 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_SoftwareSetErr   ((uint8_t)0x70)"
Software Set Error 
.PP
Definition at line 498 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ErrorCode_StuffErr   ((uint8_t)0x10)"
Stuff Error 
.PP
Definition at line 492 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
