.TH "CAN_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_TypeDef \- Controller Area Network\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBMSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRF0R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRF1R\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBESR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBTR\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED0\fP [88]"
.br
.ti -1c
.RI "\fBCAN_TxMailBox_TypeDef\fP \fBsTxMailBox\fP [3]"
.br
.ti -1c
.RI "\fBCAN_FIFOMailBox_TypeDef\fP \fBsFIFOMailBox\fP [2]"
.br
.ti -1c
.RI "uint32_t \fBRESERVED1\fP [12]"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFM1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFS1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFFA1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFA1R\fP"
.br
.ti -1c
.RI "uint32_t \fBRESERVED5\fP [8]"
.br
.ti -1c
.RI "\fBCAN_FilterRegister_TypeDef\fP \fBsFilterRegister\fP [14]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controller Area Network\&. 
.PP
Definition at line 703 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CAN_TypeDef::BTR"

.PP
Definition at line 712 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::ESR"

.PP
Definition at line 711 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::FA1R"

.PP
Definition at line 724 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::FFA1R"

.PP
Definition at line 722 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::FM1R"

.PP
Definition at line 718 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::FMR"

.PP
Definition at line 717 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::FS1R"

.PP
Definition at line 720 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::IER"

.PP
Definition at line 710 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::MCR"

.PP
Definition at line 705 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::MSR"

.PP
Definition at line 706 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED0[88]"

.PP
Definition at line 713 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED1[12]"

.PP
Definition at line 716 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED2"

.PP
Definition at line 719 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED3"

.PP
Definition at line 721 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED4"

.PP
Definition at line 723 of file stm32f10x\&.h\&.
.SS "uint32_t CAN_TypeDef::RESERVED5[8]"

.PP
Definition at line 725 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::RF0R"

.PP
Definition at line 708 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::RF1R"

.PP
Definition at line 709 of file stm32f10x\&.h\&.
.SS "\fBCAN_FIFOMailBox_TypeDef\fP CAN_TypeDef::sFIFOMailBox[2]"

.PP
Definition at line 715 of file stm32f10x\&.h\&.
.SS "\fBCAN_FilterRegister_TypeDef\fP CAN_TypeDef::sFilterRegister[14]"

.PP
Definition at line 727 of file stm32f10x\&.h\&.
.SS "\fBCAN_TxMailBox_TypeDef\fP CAN_TypeDef::sTxMailBox[3]"

.PP
Definition at line 714 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CAN_TypeDef::TSR"

.PP
Definition at line 707 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
