.TH "CAN_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMCR_DBF\fP   ((uint32_t)0x00010000) /* software master reset */"
.br
.ti -1c
.RI "#define \fBTMIDxR_TXRQ\fP   ((uint32_t)0x00000001) /* Transmit mailbox request */"
.br
.ti -1c
.RI "#define \fBFMR_FINIT\fP   ((uint32_t)0x00000001) /* Filter init mode */"
.br
.ti -1c
.RI "#define \fBINAK_TIMEOUT\fP   ((uint32_t)0x0000FFFF)"
.br
.ti -1c
.RI "#define \fBSLAK_TIMEOUT\fP   ((uint32_t)0x0000FFFF)"
.br
.ti -1c
.RI "#define \fBCAN_FLAGS_TSR\fP   ((uint32_t)0x08000000)"
.br
.ti -1c
.RI "#define \fBCAN_FLAGS_RF1R\fP   ((uint32_t)0x04000000)"
.br
.ti -1c
.RI "#define \fBCAN_FLAGS_RF0R\fP   ((uint32_t)0x02000000)"
.br
.ti -1c
.RI "#define \fBCAN_FLAGS_MSR\fP   ((uint32_t)0x01000000)"
.br
.ti -1c
.RI "#define \fBCAN_FLAGS_ESR\fP   ((uint32_t)0x00F00000)"
.br
.ti -1c
.RI "#define \fBCAN_TXMAILBOX_0\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_TXMAILBOX_1\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBCAN_TXMAILBOX_2\fP   ((uint8_t)0x02)"
.br
.ti -1c
.RI "#define \fBCAN_MODE_MASK\fP   ((uint32_t) 0x00000003)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_FLAGS_ESR   ((uint32_t)0x00F00000)"

.PP
Definition at line 73 of file stm32f10x_can\&.c\&.
.SS "#define CAN_FLAGS_MSR   ((uint32_t)0x01000000)"

.PP
Definition at line 71 of file stm32f10x_can\&.c\&.
.SS "#define CAN_FLAGS_RF0R   ((uint32_t)0x02000000)"

.PP
Definition at line 69 of file stm32f10x_can\&.c\&.
.SS "#define CAN_FLAGS_RF1R   ((uint32_t)0x04000000)"

.PP
Definition at line 67 of file stm32f10x_can\&.c\&.
.SS "#define CAN_FLAGS_TSR   ((uint32_t)0x08000000)"

.PP
Definition at line 65 of file stm32f10x_can\&.c\&.
.SS "#define CAN_MODE_MASK   ((uint32_t) 0x00000003)"

.PP
Definition at line 82 of file stm32f10x_can\&.c\&.
.SS "#define CAN_TXMAILBOX_0   ((uint8_t)0x00)"

.PP
Definition at line 76 of file stm32f10x_can\&.c\&.
.SS "#define CAN_TXMAILBOX_1   ((uint8_t)0x01)"

.PP
Definition at line 77 of file stm32f10x_can\&.c\&.
.SS "#define CAN_TXMAILBOX_2   ((uint8_t)0x02)"

.PP
Definition at line 78 of file stm32f10x_can\&.c\&.
.SS "#define FMR_FINIT   ((uint32_t)0x00000001) /* Filter init mode */"

.PP
Definition at line 55 of file stm32f10x_can\&.c\&.
.SS "#define INAK_TIMEOUT   ((uint32_t)0x0000FFFF)"

.PP
Definition at line 58 of file stm32f10x_can\&.c\&.
.SS "#define MCR_DBF   ((uint32_t)0x00010000) /* software master reset */"

.PP
Definition at line 49 of file stm32f10x_can\&.c\&.
.SS "#define SLAK_TIMEOUT   ((uint32_t)0x0000FFFF)"

.PP
Definition at line 60 of file stm32f10x_can\&.c\&.
.SS "#define TMIDxR_TXRQ   ((uint32_t)0x00000001) /* Transmit mailbox request */"

.PP
Definition at line 52 of file stm32f10x_can\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
