.TH "CAN_Tx" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Tx
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_CAN_TRANSMITMAILBOX\fP(TRANSMITMAILBOX)   ((TRANSMITMAILBOX) <= ((uint8_t)0x02))"
.br
.ti -1c
.RI "#define \fBIS_CAN_STDID\fP(STDID)   ((STDID) <= ((uint32_t)0x7FF))"
.br
.ti -1c
.RI "#define \fBIS_CAN_EXTID\fP(EXTID)   ((EXTID) <= ((uint32_t)0x1FFFFFFF))"
.br
.ti -1c
.RI "#define \fBIS_CAN_DLC\fP(DLC)   ((DLC) <= ((uint8_t)0x08))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_CAN_DLC(DLC)   ((DLC) <= ((uint8_t)0x08))"

.PP
Definition at line 408 of file stm32f10x_can\&.h\&.
.SS "#define IS_CAN_EXTID(EXTID)   ((EXTID) <= ((uint32_t)0x1FFFFFFF))"

.PP
Definition at line 407 of file stm32f10x_can\&.h\&.
.SS "#define IS_CAN_STDID(STDID)   ((STDID) <= ((uint32_t)0x7FF))"

.PP
Definition at line 406 of file stm32f10x_can\&.h\&.
.SS "#define IS_CAN_TRANSMITMAILBOX(TRANSMITMAILBOX)   ((TRANSMITMAILBOX) <= ((uint8_t)0x02))"

.PP
Definition at line 405 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
