.TH "CAN_transmit_constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_transmit_constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAN_TxStatus_Failed\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_TxStatus_Ok\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBCAN_TxStatus_Pending\fP   ((uint8_t)0x02)"
.br
.ti -1c
.RI "#define \fBCAN_TxStatus_NoMailBox\fP   ((uint8_t)0x04)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_TxStatus_Failed   ((uint8_t)0x00)"
CAN transmission failed 
.PP
Definition at line 442 of file stm32f10x_can\&.h\&.
.SS "#define CAN_TxStatus_NoMailBox   ((uint8_t)0x04)"
CAN cell did not provide an empty mailbox 
.PP
Definition at line 445 of file stm32f10x_can\&.h\&.
.SS "#define CAN_TxStatus_Ok   ((uint8_t)0x01)"
CAN transmission succeeded 
.PP
Definition at line 443 of file stm32f10x_can\&.h\&.
.SS "#define CAN_TxStatus_Pending   ((uint8_t)0x02)"
CAN transmission pending 
.PP
Definition at line 444 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
