.TH "CAN_time_quantum_in_bit_segment_1" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_time_quantum_in_bit_segment_1
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAN_BS1_1tq\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_2tq\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_3tq\fP   ((uint8_t)0x02)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_4tq\fP   ((uint8_t)0x03)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_5tq\fP   ((uint8_t)0x04)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_6tq\fP   ((uint8_t)0x05)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_7tq\fP   ((uint8_t)0x06)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_8tq\fP   ((uint8_t)0x07)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_9tq\fP   ((uint8_t)0x08)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_10tq\fP   ((uint8_t)0x09)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_11tq\fP   ((uint8_t)0x0A)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_12tq\fP   ((uint8_t)0x0B)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_13tq\fP   ((uint8_t)0x0C)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_14tq\fP   ((uint8_t)0x0D)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_15tq\fP   ((uint8_t)0x0E)"
.br
.ti -1c
.RI "#define \fBCAN_BS1_16tq\fP   ((uint8_t)0x0F)"
.br
.ti -1c
.RI "#define \fBIS_CAN_BS1\fP(BS1)   ((BS1) <= \fBCAN_BS1_16tq\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_BS1_10tq   ((uint8_t)0x09)"
10 time quantum 
.PP
Definition at line 300 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_11tq   ((uint8_t)0x0A)"
11 time quantum 
.PP
Definition at line 301 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_12tq   ((uint8_t)0x0B)"
12 time quantum 
.PP
Definition at line 302 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_13tq   ((uint8_t)0x0C)"
13 time quantum 
.PP
Definition at line 303 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_14tq   ((uint8_t)0x0D)"
14 time quantum 
.PP
Definition at line 304 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_15tq   ((uint8_t)0x0E)"
15 time quantum 
.PP
Definition at line 305 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_16tq   ((uint8_t)0x0F)"
16 time quantum 
.PP
Definition at line 306 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_1tq   ((uint8_t)0x00)"
1 time quantum 
.PP
Definition at line 291 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_2tq   ((uint8_t)0x01)"
2 time quantum 
.PP
Definition at line 292 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_3tq   ((uint8_t)0x02)"
3 time quantum 
.PP
Definition at line 293 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_4tq   ((uint8_t)0x03)"
4 time quantum 
.PP
Definition at line 294 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_5tq   ((uint8_t)0x04)"
5 time quantum 
.PP
Definition at line 295 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_6tq   ((uint8_t)0x05)"
6 time quantum 
.PP
Definition at line 296 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_7tq   ((uint8_t)0x06)"
7 time quantum 
.PP
Definition at line 297 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_8tq   ((uint8_t)0x07)"
8 time quantum 
.PP
Definition at line 298 of file stm32f10x_can\&.h\&.
.SS "#define CAN_BS1_9tq   ((uint8_t)0x08)"
9 time quantum 
.PP
Definition at line 299 of file stm32f10x_can\&.h\&.
.SS "#define IS_CAN_BS1(BS1)   ((BS1) <= \fBCAN_BS1_16tq\fP)"

.PP
Definition at line 308 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
