.TH "CAN_sleep_constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_sleep_constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAN_InitStatus_Failed\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_InitStatus_Success\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBCAN_Sleep_Failed\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBCAN_Sleep_Ok\fP   ((uint8_t)0x01)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_InitStatus_Failed   ((uint8_t)0x00)"
CAN initialization failed 
.PP
Definition at line 218 of file stm32f10x_can\&.h\&.
.SS "#define CAN_InitStatus_Success   ((uint8_t)0x01)"
CAN initialization OK 
.PP
Definition at line 219 of file stm32f10x_can\&.h\&.
.SS "#define CAN_Sleep_Failed   ((uint8_t)0x00)"
CAN did not enter the sleep mode 
.PP
Definition at line 468 of file stm32f10x_can\&.h\&.
.SS "#define CAN_Sleep_Ok   ((uint8_t)0x01)"
CAN entered the sleep mode 
.PP
Definition at line 469 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
