.TH "CAN_Legacy" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CAN_Legacy
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCANINITFAILED\fP   \fBCAN_InitStatus_Failed\fP"
.br
.ti -1c
.RI "#define \fBCANINITOK\fP   \fBCAN_InitStatus_Success\fP"
.br
.ti -1c
.RI "#define \fBCAN_FilterFIFO0\fP   \fBCAN_Filter_FIFO0\fP"
.br
.ti -1c
.RI "#define \fBCAN_FilterFIFO1\fP   \fBCAN_Filter_FIFO1\fP"
.br
.ti -1c
.RI "#define \fBCAN_ID_STD\fP   \fBCAN_Id_Standard\fP"
.br
.ti -1c
.RI "#define \fBCAN_ID_EXT\fP   \fBCAN_Id_Extended\fP"
.br
.ti -1c
.RI "#define \fBCAN_RTR_DATA\fP   \fBCAN_RTR_Data\fP"
.br
.ti -1c
.RI "#define \fBCAN_RTR_REMOTE\fP   \fBCAN_RTR_Remote\fP"
.br
.ti -1c
.RI "#define \fBCANTXFAILE\fP   \fBCAN_TxStatus_Failed\fP"
.br
.ti -1c
.RI "#define \fBCANTXOK\fP   \fBCAN_TxStatus_Ok\fP"
.br
.ti -1c
.RI "#define \fBCANTXPENDING\fP   \fBCAN_TxStatus_Pending\fP"
.br
.ti -1c
.RI "#define \fBCAN_NO_MB\fP   \fBCAN_TxStatus_NoMailBox\fP"
.br
.ti -1c
.RI "#define \fBCANSLEEPFAILED\fP   \fBCAN_Sleep_Failed\fP"
.br
.ti -1c
.RI "#define \fBCANSLEEPOK\fP   \fBCAN_Sleep_Ok\fP"
.br
.ti -1c
.RI "#define \fBCANWAKEUPFAILED\fP   \fBCAN_WakeUp_Failed\fP"
.br
.ti -1c
.RI "#define \fBCANWAKEUPOK\fP   \fBCAN_WakeUp_Ok\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CAN_FilterFIFO0   \fBCAN_Filter_FIFO0\fP"

.PP
Definition at line 613 of file stm32f10x_can\&.h\&.
.SS "#define CAN_FilterFIFO1   \fBCAN_Filter_FIFO1\fP"

.PP
Definition at line 614 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ID_EXT   \fBCAN_Id_Extended\fP"

.PP
Definition at line 616 of file stm32f10x_can\&.h\&.
.SS "#define CAN_ID_STD   \fBCAN_Id_Standard\fP"

.PP
Definition at line 615 of file stm32f10x_can\&.h\&.
.SS "#define CAN_NO_MB   \fBCAN_TxStatus_NoMailBox\fP"

.PP
Definition at line 622 of file stm32f10x_can\&.h\&.
.SS "#define CAN_RTR_DATA   \fBCAN_RTR_Data\fP"

.PP
Definition at line 617 of file stm32f10x_can\&.h\&.
.SS "#define CAN_RTR_REMOTE   \fBCAN_RTR_Remote\fP"

.PP
Definition at line 618 of file stm32f10x_can\&.h\&.
.SS "#define CANINITFAILED   \fBCAN_InitStatus_Failed\fP"

.PP
Definition at line 611 of file stm32f10x_can\&.h\&.
.SS "#define CANINITOK   \fBCAN_InitStatus_Success\fP"

.PP
Definition at line 612 of file stm32f10x_can\&.h\&.
.SS "#define CANSLEEPFAILED   \fBCAN_Sleep_Failed\fP"

.PP
Definition at line 623 of file stm32f10x_can\&.h\&.
.SS "#define CANSLEEPOK   \fBCAN_Sleep_Ok\fP"

.PP
Definition at line 624 of file stm32f10x_can\&.h\&.
.SS "#define CANTXFAILE   \fBCAN_TxStatus_Failed\fP"

.PP
Definition at line 619 of file stm32f10x_can\&.h\&.
.SS "#define CANTXOK   \fBCAN_TxStatus_Ok\fP"

.PP
Definition at line 620 of file stm32f10x_can\&.h\&.
.SS "#define CANTXPENDING   \fBCAN_TxStatus_Pending\fP"

.PP
Definition at line 621 of file stm32f10x_can\&.h\&.
.SS "#define CANWAKEUPFAILED   \fBCAN_WakeUp_Failed\fP"

.PP
Definition at line 625 of file stm32f10x_can\&.h\&.
.SS "#define CANWAKEUPOK   \fBCAN_WakeUp_Ok\fP"

.PP
Definition at line 626 of file stm32f10x_can\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
