.TH "CanRxMsg" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CanRxMsg \- CAN Rx message structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x_can\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBStdId\fP"
.br
.ti -1c
.RI "uint32_t \fBExtId\fP"
.br
.ti -1c
.RI "uint8_t \fBIDE\fP"
.br
.ti -1c
.RI "uint8_t \fBRTR\fP"
.br
.ti -1c
.RI "uint8_t \fBDLC\fP"
.br
.ti -1c
.RI "uint8_t \fBData\fP [8]"
.br
.ti -1c
.RI "uint8_t \fBFMI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CAN Rx message structure definition\&. 
.PP
Definition at line 179 of file stm32f10x_can\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t CanRxMsg::Data[8]"
Contains the data to be received\&. It ranges from 0 to 0xFF\&. 
.PP
Definition at line 198 of file stm32f10x_can\&.h\&.
.SS "uint8_t CanRxMsg::DLC"
Specifies the length of the frame that will be received\&. This parameter can be a value between 0 to 8 
.PP
Definition at line 195 of file stm32f10x_can\&.h\&.
.SS "uint32_t CanRxMsg::ExtId"
Specifies the extended identifier\&. This parameter can be a value between 0 to 0x1FFFFFFF\&. 
.PP
Definition at line 184 of file stm32f10x_can\&.h\&.
.SS "uint8_t CanRxMsg::FMI"
Specifies the index of the filter the message stored in the mailbox passes through\&. This parameter can be a value between 0 to 0xFF 
.PP
Definition at line 201 of file stm32f10x_can\&.h\&.
.SS "uint8_t CanRxMsg::IDE"
Specifies the type of identifier for the message that will be received\&. This parameter can be a value of \fBCAN_identifier_type\fP 
.PP
Definition at line 187 of file stm32f10x_can\&.h\&.
.SS "uint8_t CanRxMsg::RTR"
Specifies the type of frame for the received message\&. This parameter can be a value of \fBCAN_remote_transmission_request\fP 
.PP
Definition at line 191 of file stm32f10x_can\&.h\&.
.SS "uint32_t CanRxMsg::StdId"
Specifies the standard identifier\&. This parameter can be a value between 0 to 0x7FF\&. 
.PP
Definition at line 181 of file stm32f10x_can\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
