.TH "CEC_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CEC_TypeDef \- Consumer Electronics Control (CEC)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPRES\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBESR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBTXD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRXD\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Consumer Electronics Control (CEC) 
.PP
Definition at line 736 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CEC_TypeDef::CFGR"

.PP
Definition at line 738 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::CSR"

.PP
Definition at line 742 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::ESR"

.PP
Definition at line 741 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::OAR"

.PP
Definition at line 739 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::PRES"

.PP
Definition at line 740 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::RXD"

.PP
Definition at line 744 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CEC_TypeDef::TXD"

.PP
Definition at line 743 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
