.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/cmsis_armcc.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/cmsis_armcc.h \- CMSIS Cortex-M Core Function/Instruction Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__NOP\fP   __nop"
.br
.RI "No Operation\&. "
.ti -1c
.RI "#define \fB__WFI\fP   __wfi"
.br
.RI "Wait For Interrupt\&. "
.ti -1c
.RI "#define \fB__WFE\fP   __wfe"
.br
.RI "Wait For Event\&. "
.ti -1c
.RI "#define \fB__SEV\fP   __sev"
.br
.RI "Send Event\&. "
.ti -1c
.RI "#define \fB__ISB\fP()"
.br
.RI "Instruction Synchronization Barrier\&. "
.ti -1c
.RI "#define \fB__DSB\fP()"
.br
.RI "Data Synchronization Barrier\&. "
.ti -1c
.RI "#define \fB__DMB\fP()"
.br
.RI "Data Memory Barrier\&. "
.ti -1c
.RI "#define \fB__REV\fP   __rev"
.br
.RI "Reverse byte order (32 bit) "
.ti -1c
.RI "#define \fB__ROR\fP   __ror"
.br
.RI "Rotate Right in unsigned value (32 bit) "
.ti -1c
.RI "#define \fB__BKPT\fP(\fBvalue\fP)   __breakpoint(\fBvalue\fP)"
.br
.RI "Breakpoint\&. "
.ti -1c
.RI "#define \fB__CLZ\fP   __clz"
.br
.RI "Count leading zeros\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_CONTROL\fP (void)"
.br
.RI "Get Control Register\&. "
.ti -1c
.RI "__STATIC_INLINE void \fB__set_CONTROL\fP (uint32_t control)"
.br
.RI "Set Control Register\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_IPSR\fP (void)"
.br
.RI "Get IPSR Register\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_APSR\fP (void)"
.br
.RI "Get APSR Register\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_xPSR\fP (void)"
.br
.RI "Get xPSR Register\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_PSP\fP (void)"
.br
.RI "Get Process Stack Pointer\&. "
.ti -1c
.RI "__STATIC_INLINE void \fB__set_PSP\fP (uint32_t topOfProcStack)"
.br
.RI "Set Process Stack Pointer\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_MSP\fP (void)"
.br
.RI "Get Main Stack Pointer\&. "
.ti -1c
.RI "__STATIC_INLINE void \fB__set_MSP\fP (uint32_t topOfMainStack)"
.br
.RI "Set Main Stack Pointer\&. "
.ti -1c
.RI "__STATIC_INLINE uint32_t \fB__get_PRIMASK\fP (void)"
.br
.RI "Get Priority Mask\&. "
.ti -1c
.RI "__STATIC_INLINE void \fB__set_PRIMASK\fP (uint32_t priMask)"
.br
.RI "Set Priority Mask\&. "
.ti -1c
.RI "\fB__attribute__\fP ((section('\&.rev16_text'))) __STATIC_INLINE __ASM uint32_t \fB__REV16\fP(uint32_t \fBvalue\fP)"
.br
.RI "Reverse byte order (16 bit) "
.ti -1c
.RI "\fB__attribute__\fP ((section('\&.revsh_text'))) __STATIC_INLINE __ASM int32_t __REVSH(int32_t \fBvalue\fP)"
.br
.RI "Reverse byte order in signed short value\&. "
.ti -1c
.RI "\fB__attribute__\fP ((always_inline)) __STATIC_INLINE uint32_t __RBIT(uint32_t \fBvalue\fP)"
.br
.RI "Reverse bit order of value\&. "
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M Core Function/Instruction Header File\&. 


.PP
\fBVersion:\fP
.RS 4
V4\&.30 
.RE
.PP
\fBDate:\fP
.RS 4
20\&. October 2015 
.RE
.PP

.PP
Definition in file \fBcmsis_armcc\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
