.TH "CMSIS_NVIC" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_NVIC \- Type definitions for the NVIC Registers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNVIC_Type\fP"
.br
.RI "Structure type to access the Nested Vectored Interrupt Controller (NVIC)\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBNVIC_STIR_INTID_Msk\fP   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the NVIC Registers\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.PP
Definition at line 402 of file core_sc300\&.h\&.
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.PP
Definition at line 410 of file core_cm3\&.h\&.
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.PP
Definition at line 478 of file core_cm4\&.h\&.
.SS "#define NVIC_STIR_INTID_Msk   (0x1FFUL /*<< NVIC_STIR_INTID_Pos*/)"
STIR: INTLINESNUM Mask 
.PP
Definition at line 493 of file core_cm7\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.PP
Definition at line 401 of file core_sc300\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.PP
Definition at line 409 of file core_cm3\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.PP
Definition at line 477 of file core_cm4\&.h\&.
.SS "#define NVIC_STIR_INTID_Pos   0U"
STIR: INTLINESNUM Position 
.PP
Definition at line 492 of file core_cm7\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
