.TH "CMSIS_core_register" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_core_register \- Type definitions and defines for Cortex-M processor based devices\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBStatus and Control Registers\fP"
.br
.RI "Core Register type definitions\&. "
.ti -1c
.RI "\fBNested Vectored Interrupt Controller (NVIC)\fP"
.br
.RI "Type definitions for the NVIC Registers\&. "
.ti -1c
.RI "\fBSystem Control Block (SCB)\fP"
.br
.RI "Type definitions for the System Control Block Registers\&. "
.ti -1c
.RI "\fBSystem Tick Timer (SysTick)\fP"
.br
.RI "Type definitions for the System \fBTimer\fP Registers\&. "
.ti -1c
.RI "\fBCore Debug Registers (CoreDebug)\fP"
.br
.RI "Cortex-M0 Core Debug Registers (DCB registers, SHCSR, and DFSR) are only accessible over DAP and not via processor\&. Therefore they are not covered by the Cortex-M0 header file\&. "
.ti -1c
.RI "\fBCore register bit field macros\fP"
.br
.RI "Macros for use with bit field definitions (xxx_Pos, xxx_Msk)\&. "
.ti -1c
.RI "\fBCore Definitions\fP"
.br
.RI "Definitions for base addresses, unions, and structures\&. "
.ti -1c
.RI "\fBSystem Controls not in SCB (SCnSCB)\fP"
.br
.RI "Type definitions for the System Control and ID Register not in the SCB\&. "
.ti -1c
.RI "\fBInstrumentation Trace Macrocell (ITM)\fP"
.br
.RI "Type definitions for the Instrumentation Trace Macrocell (ITM) "
.ti -1c
.RI "\fBData Watchpoint and Trace (DWT)\fP"
.br
.RI "Type definitions for the Data Watchpoint and Trace (DWT) "
.ti -1c
.RI "\fBTrace Port Interface (TPI)\fP"
.br
.RI "Type definitions for the Trace Port Interface (TPI) "
.in -1c
.SH "Detailed Description"
.PP 
Type definitions and defines for Cortex-M processor based devices\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
