.TH "CMSIS_SCnSCB" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_SCnSCB \- Type definitions for the System Control and ID Register not in the SCB\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSCnSCB_Type\fP"
.br
.RI "Structure type to access the System Control and ID Register not in the SCB\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Msk\fP   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Pos\fP   9U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISOOFP_Msk\fP   (1UL << SCnSCB_ACTLR_DISOOFP_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Pos\fP   8U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFPCA_Msk\fP   (1UL << SCnSCB_ACTLR_DISFPCA_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Pos\fP   1U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISDEFWBUF_Msk\fP   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Pos\fP   12U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISITMATBFLUSH_Msk\fP   (1UL << SCnSCB_ACTLR_DISITMATBFLUSH_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISRAMODE_Pos\fP   11U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISRAMODE_Msk\fP   (1UL << SCnSCB_ACTLR_DISRAMODE_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Pos\fP   10U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_FPEXCODIS_Msk\fP   (1UL << SCnSCB_ACTLR_FPEXCODIS_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Pos\fP   2U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISFOLD_Msk\fP   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ACTLR_DISMCYCINT_Msk\fP   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Pos\fP   0U"
.br
.ti -1c
.RI "#define \fBSCnSCB_ICTR_INTLINESNUM_Msk\fP   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type definitions for the System Control and ID Register not in the SCB\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Msk   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
ACTLR: DISDEFWBUF Mask 
.PP
Definition at line 673 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Msk   (1UL << SCnSCB_ACTLR_DISDEFWBUF_Pos)"
ACTLR: DISDEFWBUF Mask 
.PP
Definition at line 734 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Pos   1U"
ACTLR: DISDEFWBUF Position 
.PP
Definition at line 672 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISDEFWBUF_Pos   1U"
ACTLR: DISDEFWBUF Position 
.PP
Definition at line 733 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
ACTLR: DISFOLD Mask 
.PP
Definition at line 670 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
ACTLR: DISFOLD Mask 
.PP
Definition at line 731 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Msk   (1UL << SCnSCB_ACTLR_DISFOLD_Pos)"
ACTLR: DISFOLD Mask 
.PP
Definition at line 936 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line 669 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line 730 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFOLD_Pos   2U"
ACTLR: DISFOLD Position 
.PP
Definition at line 935 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFPCA_Msk   (1UL << SCnSCB_ACTLR_DISFPCA_Pos)"
ACTLR: DISFPCA Mask 
.PP
Definition at line 728 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISFPCA_Pos   8U"
ACTLR: DISFPCA Position 
.PP
Definition at line 727 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Msk   (1UL << SCnSCB_ACTLR_DISITMATBFLUSH_Pos)"
ACTLR: DISITMATBFLUSH Mask 
.PP
Definition at line 927 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISITMATBFLUSH_Pos   12U"
ACTLR: DISITMATBFLUSH Position 
.PP
Definition at line 926 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line 516 of file core_sc000\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line 676 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line 737 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Msk   (1UL /*<< SCnSCB_ACTLR_DISMCYCINT_Pos*/)"
ACTLR: DISMCYCINT Mask 
.PP
Definition at line 939 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line 515 of file core_sc000\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line 675 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line 736 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISMCYCINT_Pos   0U"
ACTLR: DISMCYCINT Position 
.PP
Definition at line 938 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISOOFP_Msk   (1UL << SCnSCB_ACTLR_DISOOFP_Pos)"
ACTLR: DISOOFP Mask 
.PP
Definition at line 725 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISOOFP_Pos   9U"
ACTLR: DISOOFP Position 
.PP
Definition at line 724 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ACTLR_DISRAMODE_Msk   (1UL << SCnSCB_ACTLR_DISRAMODE_Pos)"
ACTLR: DISRAMODE Mask 
.PP
Definition at line 930 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_DISRAMODE_Pos   11U"
ACTLR: DISRAMODE Position 
.PP
Definition at line 929 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Msk   (1UL << SCnSCB_ACTLR_FPEXCODIS_Pos)"
ACTLR: FPEXCODIS Mask 
.PP
Definition at line 933 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ACTLR_FPEXCODIS_Pos   10U"
ACTLR: FPEXCODIS Position 
.PP
Definition at line 932 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line 650 of file core_sc300\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line 665 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line 721 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Msk   (0xFUL /*<< SCnSCB_ICTR_INTLINESNUM_Pos*/)"
ICTR: INTLINESNUM Mask 
.PP
Definition at line 923 of file core_cm7\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line 649 of file core_sc300\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line 664 of file core_cm3\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line 720 of file core_cm4\&.h\&.
.SS "#define SCnSCB_ICTR_INTLINESNUM_Pos   0U"
ICTR: INTLINESNUM Position 
.PP
Definition at line 922 of file core_cm7\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
