.TH "CMSIS_glob_defs" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMSIS_glob_defs
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBIO Type Qualifiers\fP are used 
.PD 0

.IP "\(bu" 2
to specify the access to peripheral variables\&. 
.IP "\(bu" 2
for automatic generation of peripheral register debug information\&. 
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
