.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/cmsis_armcc_V6.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/cmsis_armcc_V6.h \- CMSIS Cortex-M Core Function/Instruction Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CMSIS_GCC_OUT_REG\fP(r)   '=r' (r)"
.br
.ti -1c
.RI "#define \fB__CMSIS_GCC_USE_REG\fP(r)   'r' (r)"
.br
.ti -1c
.RI "#define \fB__NOP\fP   __builtin_arm_nop"
.br
.RI "No Operation\&. "
.ti -1c
.RI "#define \fB__WFI\fP   __builtin_arm_wfi"
.br
.RI "Wait For Interrupt\&. "
.ti -1c
.RI "#define \fB__WFE\fP   __builtin_arm_wfe"
.br
.RI "Wait For Event\&. "
.ti -1c
.RI "#define \fB__SEV\fP   __builtin_arm_sev"
.br
.RI "Send Event\&. "
.ti -1c
.RI "#define \fB__ISB\fP()   __builtin_arm_isb(0xF);"
.br
.RI "Instruction Synchronization Barrier\&. "
.ti -1c
.RI "#define \fB__DSB\fP()   __builtin_arm_dsb(0xF);"
.br
.RI "Data Synchronization Barrier\&. "
.ti -1c
.RI "#define \fB__DMB\fP()   __builtin_arm_dmb(0xF);"
.br
.RI "Data Memory Barrier\&. "
.ti -1c
.RI "#define \fB__REV\fP   __builtin_bswap32"
.br
.RI "Reverse byte order (32 bit) "
.ti -1c
.RI "#define \fB__REV16\fP   __builtin_bswap16                           /* ToDo:  ARMCC_V6: check if __builtin_bswap16 could be used */"
.br
.RI "Reverse byte order (16 bit) "
.ti -1c
.RI "#define \fB__BKPT\fP(\fBvalue\fP)   __ASM \fBvolatile\fP ('bkpt '#value)"
.br
.RI "Breakpoint\&. "
.ti -1c
.RI "#define \fB__CLZ\fP   __builtin_clz"
.br
.RI "Count leading zeros\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__attribute__\fP ((always_inline)) __STATIC_INLINE void __enable_irq(void)"
.br
.RI "Enable IRQ Interrupts\&. "
.ti -1c
.RI "\fB__attribute__\fP ((always_inline)) __STATIC_INLINE uint32_t __RBIT(uint32_t \fBvalue\fP)"
.br
.RI "Reverse bit order of value\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBop2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M Core Function/Instruction Header File\&. 


.PP
\fBVersion:\fP
.RS 4
V4\&.30 
.RE
.PP
\fBDate:\fP
.RS 4
20\&. October 2015 
.RE
.PP

.PP
Definition in file \fBcmsis_armcc_V6\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
