.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/core_cmSimd.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/cmsis/core_cmSimd.h \- CMSIS Cortex-M SIMD Header File\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__CORE_CMSIMD_H\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CMSIS Cortex-M SIMD Header File\&. 


.PP
\fBVersion:\fP
.RS 4
V4\&.30 
.RE
.PP
\fBDate:\fP
.RS 4
20\&. October 2015 
.RE
.PP

.PP
Definition in file \fBcore_cmSimd\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define __CORE_CMSIMD_H"

.PP
Definition at line 42 of file core_cmSimd\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
