.TH "CRC" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC \- CRC driver modules\&.  

.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBCRC_Exported_Types\fP"
.br
.ti -1c
.RI "\fBCRC_Exported_Constants\fP"
.br
.ti -1c
.RI "\fBCRC_Exported_Macros\fP"
.br
.ti -1c
.RI "\fBCRC_Exported_Functions\fP"
.br
.ti -1c
.RI "\fBCRC_Private_TypesDefinitions\fP"
.br
.ti -1c
.RI "\fBCRC_Private_Defines\fP"
.br
.ti -1c
.RI "\fBCRC_Private_Macros\fP"
.br
.ti -1c
.RI "\fBCRC_Private_Variables\fP"
.br
.ti -1c
.RI "\fBCRC_Private_FunctionPrototypes\fP"
.br
.ti -1c
.RI "\fBCRC_Private_Functions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CRC driver modules\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
