.TH "CRC_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CRC_TypeDef \- CRC calculation unit\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint8_t \fBIDR\fP"
.br
.ti -1c
.RI "uint8_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
CRC calculation unit\&. 
.PP
Definition at line 751 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t CRC_TypeDef::CR"

.PP
Definition at line 757 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t CRC_TypeDef::DR"

.PP
Definition at line 753 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint8_t CRC_TypeDef::IDR"

.PP
Definition at line 754 of file stm32f10x\&.h\&.
.SS "uint8_t CRC_TypeDef::RESERVED0"

.PP
Definition at line 755 of file stm32f10x\&.h\&.
.SS "uint16_t CRC_TypeDef::RESERVED1"

.PP
Definition at line 756 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
