.TH "DAC_lfsrunmask_triangleamplitude" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAC_lfsrunmask_triangleamplitude
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bit0\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits1_0\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits2_0\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits3_0\fP   ((uint32_t)0x00000300)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits4_0\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits5_0\fP   ((uint32_t)0x00000500)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits6_0\fP   ((uint32_t)0x00000600)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits7_0\fP   ((uint32_t)0x00000700)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits8_0\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits9_0\fP   ((uint32_t)0x00000900)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits10_0\fP   ((uint32_t)0x00000A00)"
.br
.ti -1c
.RI "#define \fBDAC_LFSRUnmask_Bits11_0\fP   ((uint32_t)0x00000B00)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_1\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_3\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_7\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_15\fP   ((uint32_t)0x00000300)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_31\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_63\fP   ((uint32_t)0x00000500)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_127\fP   ((uint32_t)0x00000600)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_255\fP   ((uint32_t)0x00000700)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_511\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_1023\fP   ((uint32_t)0x00000900)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_2047\fP   ((uint32_t)0x00000A00)"
.br
.ti -1c
.RI "#define \fBDAC_TriangleAmplitude_4095\fP   ((uint32_t)0x00000B00)"
.br
.ti -1c
.RI "#define \fBIS_DAC_LFSR_UNMASK_TRIANGLE_AMPLITUDE\fP(VALUE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DAC_LFSRUnmask_Bit0   ((uint32_t)0x00000000)"
Unmask DAC channel LFSR bit0 for noise wave generation 
.PP
Definition at line 131 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits10_0   ((uint32_t)0x00000A00)"
Unmask DAC channel LFSR bit[10:0] for noise wave generation 
.PP
Definition at line 141 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits11_0   ((uint32_t)0x00000B00)"
Unmask DAC channel LFSR bit[11:0] for noise wave generation 
.PP
Definition at line 142 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits1_0   ((uint32_t)0x00000100)"
Unmask DAC channel LFSR bit[1:0] for noise wave generation 
.PP
Definition at line 132 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits2_0   ((uint32_t)0x00000200)"
Unmask DAC channel LFSR bit[2:0] for noise wave generation 
.PP
Definition at line 133 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits3_0   ((uint32_t)0x00000300)"
Unmask DAC channel LFSR bit[3:0] for noise wave generation 
.PP
Definition at line 134 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits4_0   ((uint32_t)0x00000400)"
Unmask DAC channel LFSR bit[4:0] for noise wave generation 
.PP
Definition at line 135 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits5_0   ((uint32_t)0x00000500)"
Unmask DAC channel LFSR bit[5:0] for noise wave generation 
.PP
Definition at line 136 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits6_0   ((uint32_t)0x00000600)"
Unmask DAC channel LFSR bit[6:0] for noise wave generation 
.PP
Definition at line 137 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits7_0   ((uint32_t)0x00000700)"
Unmask DAC channel LFSR bit[7:0] for noise wave generation 
.PP
Definition at line 138 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits8_0   ((uint32_t)0x00000800)"
Unmask DAC channel LFSR bit[8:0] for noise wave generation 
.PP
Definition at line 139 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_LFSRUnmask_Bits9_0   ((uint32_t)0x00000900)"
Unmask DAC channel LFSR bit[9:0] for noise wave generation 
.PP
Definition at line 140 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_1   ((uint32_t)0x00000000)"
Select max triangle amplitude of 1 
.PP
Definition at line 143 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_1023   ((uint32_t)0x00000900)"
Select max triangle amplitude of 1023 
.PP
Definition at line 152 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_127   ((uint32_t)0x00000600)"
Select max triangle amplitude of 127 
.PP
Definition at line 149 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_15   ((uint32_t)0x00000300)"
Select max triangle amplitude of 15 
.PP
Definition at line 146 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_2047   ((uint32_t)0x00000A00)"
Select max triangle amplitude of 2047 
.PP
Definition at line 153 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_255   ((uint32_t)0x00000700)"
Select max triangle amplitude of 255 
.PP
Definition at line 150 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_3   ((uint32_t)0x00000100)"
Select max triangle amplitude of 3 
.PP
Definition at line 144 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_31   ((uint32_t)0x00000400)"
Select max triangle amplitude of 31 
.PP
Definition at line 147 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_4095   ((uint32_t)0x00000B00)"
Select max triangle amplitude of 4095 
.PP
Definition at line 154 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_511   ((uint32_t)0x00000800)"
Select max triangle amplitude of 511 
.PP
Definition at line 151 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_63   ((uint32_t)0x00000500)"
Select max triangle amplitude of 63 
.PP
Definition at line 148 of file stm32f10x_dac\&.h\&.
.SS "#define DAC_TriangleAmplitude_7   ((uint32_t)0x00000200)"
Select max triangle amplitude of 7 
.PP
Definition at line 145 of file stm32f10x_dac\&.h\&.
.SS "#define IS_DAC_LFSR_UNMASK_TRIANGLE_AMPLITUDE(VALUE)"
\fBValue:\fP
.PP
.nf
(((VALUE) == DAC_LFSRUnmask_Bit0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits1_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits2_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits3_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits4_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits5_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits6_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits7_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits8_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits9_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits10_0) || \
                                                      ((VALUE) == DAC_LFSRUnmask_Bits11_0) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_1) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_3) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_7) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_15) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_31) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_63) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_127) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_255) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_511) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_1023) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_2047) || \
                                                      ((VALUE) == DAC_TriangleAmplitude_4095))
.fi
.PP
Definition at line 156 of file stm32f10x_dac\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
