.TH "DAC_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DAC_TypeDef \- Digital to Analog Converter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSWTRIGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12R1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12L1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR8R1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12R2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12L2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR8R2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12RD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR12LD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDHR8RD\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDOR1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBDOR2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Digital to Analog Converter\&. 
.PP
Definition at line 764 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DAC_TypeDef::CR"

.PP
Definition at line 766 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12L1"

.PP
Definition at line 769 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12L2"

.PP
Definition at line 772 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12LD"

.PP
Definition at line 775 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12R1"

.PP
Definition at line 768 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12R2"

.PP
Definition at line 771 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR12RD"

.PP
Definition at line 774 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR8R1"

.PP
Definition at line 770 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR8R2"

.PP
Definition at line 773 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DHR8RD"

.PP
Definition at line 776 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DOR1"

.PP
Definition at line 777 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::DOR2"

.PP
Definition at line 778 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DAC_TypeDef::SWTRIGR"

.PP
Definition at line 767 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
