.TH "DBGMCU_Exported_Constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DBGMCU_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDBGMCU_SLEEP\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBDBGMCU_STOP\fP   ((uint32_t)0x00000002)"
.br
.ti -1c
.RI "#define \fBDBGMCU_STANDBY\fP   ((uint32_t)0x00000004)"
.br
.ti -1c
.RI "#define \fBDBGMCU_IWDG_STOP\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBDBGMCU_WWDG_STOP\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM1_STOP\fP   ((uint32_t)0x00000400)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM2_STOP\fP   ((uint32_t)0x00000800)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM3_STOP\fP   ((uint32_t)0x00001000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM4_STOP\fP   ((uint32_t)0x00002000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_CAN1_STOP\fP   ((uint32_t)0x00004000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_I2C1_SMBUS_TIMEOUT\fP   ((uint32_t)0x00008000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_I2C2_SMBUS_TIMEOUT\fP   ((uint32_t)0x00010000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM8_STOP\fP   ((uint32_t)0x00020000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM5_STOP\fP   ((uint32_t)0x00040000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM6_STOP\fP   ((uint32_t)0x00080000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM7_STOP\fP   ((uint32_t)0x00100000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_CAN2_STOP\fP   ((uint32_t)0x00200000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM15_STOP\fP   ((uint32_t)0x00400000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM16_STOP\fP   ((uint32_t)0x00800000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM17_STOP\fP   ((uint32_t)0x01000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM12_STOP\fP   ((uint32_t)0x02000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM13_STOP\fP   ((uint32_t)0x04000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM14_STOP\fP   ((uint32_t)0x08000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM9_STOP\fP   ((uint32_t)0x10000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM10_STOP\fP   ((uint32_t)0x20000000)"
.br
.ti -1c
.RI "#define \fBDBGMCU_TIM11_STOP\fP   ((uint32_t)0x40000000)"
.br
.ti -1c
.RI "#define \fBIS_DBGMCU_PERIPH\fP(PERIPH)   ((((PERIPH) & 0x800000F8) == 0x00) && ((PERIPH) != 0x00))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DBGMCU_CAN1_STOP   ((uint32_t)0x00004000)"

.PP
Definition at line 63 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_CAN2_STOP   ((uint32_t)0x00200000)"

.PP
Definition at line 70 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_I2C1_SMBUS_TIMEOUT   ((uint32_t)0x00008000)"

.PP
Definition at line 64 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_I2C2_SMBUS_TIMEOUT   ((uint32_t)0x00010000)"

.PP
Definition at line 65 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_IWDG_STOP   ((uint32_t)0x00000100)"

.PP
Definition at line 57 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_SLEEP   ((uint32_t)0x00000001)"

.PP
Definition at line 54 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_STANDBY   ((uint32_t)0x00000004)"

.PP
Definition at line 56 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_STOP   ((uint32_t)0x00000002)"

.PP
Definition at line 55 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM10_STOP   ((uint32_t)0x20000000)"

.PP
Definition at line 78 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM11_STOP   ((uint32_t)0x40000000)"

.PP
Definition at line 79 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM12_STOP   ((uint32_t)0x02000000)"

.PP
Definition at line 74 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM13_STOP   ((uint32_t)0x04000000)"

.PP
Definition at line 75 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM14_STOP   ((uint32_t)0x08000000)"

.PP
Definition at line 76 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM15_STOP   ((uint32_t)0x00400000)"

.PP
Definition at line 71 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM16_STOP   ((uint32_t)0x00800000)"

.PP
Definition at line 72 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM17_STOP   ((uint32_t)0x01000000)"

.PP
Definition at line 73 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM1_STOP   ((uint32_t)0x00000400)"

.PP
Definition at line 59 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM2_STOP   ((uint32_t)0x00000800)"

.PP
Definition at line 60 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM3_STOP   ((uint32_t)0x00001000)"

.PP
Definition at line 61 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM4_STOP   ((uint32_t)0x00002000)"

.PP
Definition at line 62 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM5_STOP   ((uint32_t)0x00040000)"

.PP
Definition at line 67 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM6_STOP   ((uint32_t)0x00080000)"

.PP
Definition at line 68 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM7_STOP   ((uint32_t)0x00100000)"

.PP
Definition at line 69 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM8_STOP   ((uint32_t)0x00020000)"

.PP
Definition at line 66 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_TIM9_STOP   ((uint32_t)0x10000000)"

.PP
Definition at line 77 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define DBGMCU_WWDG_STOP   ((uint32_t)0x00000200)"

.PP
Definition at line 58 of file stm32f10x_dbgmcu\&.h\&.
.SS "#define IS_DBGMCU_PERIPH(PERIPH)   ((((PERIPH) & 0x800000F8) == 0x00) && ((PERIPH) != 0x00))"

.PP
Definition at line 81 of file stm32f10x_dbgmcu\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
