.TH "DMA_Channel_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Channel_TypeDef \- DMA Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCNDTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCPAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCMAR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
DMA Controller\&. 
.PP
Definition at line 798 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CCR"

.PP
Definition at line 800 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CMAR"

.PP
Definition at line 803 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CNDTR"

.PP
Definition at line 801 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t DMA_Channel_TypeDef::CPAR"

.PP
Definition at line 802 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
