.TH "DMA_priority_level" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_priority_level
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA_Priority_VeryHigh\fP   ((uint32_t)0x00003000)"
.br
.ti -1c
.RI "#define \fBDMA_Priority_High\fP   ((uint32_t)0x00002000)"
.br
.ti -1c
.RI "#define \fBDMA_Priority_Medium\fP   ((uint32_t)0x00001000)"
.br
.ti -1c
.RI "#define \fBDMA_Priority_Low\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBIS_DMA_PRIORITY\fP(PRIORITY)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define DMA_Priority_High   ((uint32_t)0x00002000)"

.PP
Definition at line 188 of file stm32f10x_dma\&.h\&.
.SS "#define DMA_Priority_Low   ((uint32_t)0x00000000)"

.PP
Definition at line 190 of file stm32f10x_dma\&.h\&.
.SS "#define DMA_Priority_Medium   ((uint32_t)0x00001000)"

.PP
Definition at line 189 of file stm32f10x_dma\&.h\&.
.SS "#define DMA_Priority_VeryHigh   ((uint32_t)0x00003000)"

.PP
Definition at line 187 of file stm32f10x_dma\&.h\&.
.SS "#define IS_DMA_PRIORITY(PRIORITY)"
\fBValue:\fP
.PP
.nf
(((PRIORITY) == DMA_Priority_VeryHigh) || \
                                   ((PRIORITY) == DMA_Priority_High) || \
                                   ((PRIORITY) == DMA_Priority_Medium) || \
                                   ((PRIORITY) == DMA_Priority_Low))
.fi
.PP
Definition at line 191 of file stm32f10x_dma\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
