.TH "DMA_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDMA1_Channel1_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF1\fP | \fBDMA_ISR_TCIF1\fP | \fBDMA_ISR_HTIF1\fP | \fBDMA_ISR_TEIF1\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel2_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF2\fP | \fBDMA_ISR_TCIF2\fP | \fBDMA_ISR_HTIF2\fP | \fBDMA_ISR_TEIF2\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel3_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF3\fP | \fBDMA_ISR_TCIF3\fP | \fBDMA_ISR_HTIF3\fP | \fBDMA_ISR_TEIF3\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel4_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF4\fP | \fBDMA_ISR_TCIF4\fP | \fBDMA_ISR_HTIF4\fP | \fBDMA_ISR_TEIF4\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel5_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF5\fP | \fBDMA_ISR_TCIF5\fP | \fBDMA_ISR_HTIF5\fP | \fBDMA_ISR_TEIF5\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel6_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF6\fP | \fBDMA_ISR_TCIF6\fP | \fBDMA_ISR_HTIF6\fP | \fBDMA_ISR_TEIF6\fP))"
.br
.ti -1c
.RI "#define \fBDMA1_Channel7_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF7\fP | \fBDMA_ISR_TCIF7\fP | \fBDMA_ISR_HTIF7\fP | \fBDMA_ISR_TEIF7\fP))"
.br
.ti -1c
.RI "#define \fBDMA2_Channel1_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF1\fP | \fBDMA_ISR_TCIF1\fP | \fBDMA_ISR_HTIF1\fP | \fBDMA_ISR_TEIF1\fP))"
.br
.ti -1c
.RI "#define \fBDMA2_Channel2_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF2\fP | \fBDMA_ISR_TCIF2\fP | \fBDMA_ISR_HTIF2\fP | \fBDMA_ISR_TEIF2\fP))"
.br
.ti -1c
.RI "#define \fBDMA2_Channel3_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF3\fP | \fBDMA_ISR_TCIF3\fP | \fBDMA_ISR_HTIF3\fP | \fBDMA_ISR_TEIF3\fP))"
.br
.ti -1c
.RI "#define \fBDMA2_Channel4_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF4\fP | \fBDMA_ISR_TCIF4\fP | \fBDMA_ISR_HTIF4\fP | \fBDMA_ISR_TEIF4\fP))"
.br
.ti -1c
.RI "#define \fBDMA2_Channel5_IT_Mask\fP   ((uint32_t)(\fBDMA_ISR_GIF5\fP | \fBDMA_ISR_TCIF5\fP | \fBDMA_ISR_HTIF5\fP | \fBDMA_ISR_TEIF5\fP))"
.br
.ti -1c
.RI "#define \fBFLAG_Mask\fP   ((uint32_t)0x10000000)"
.br
.ti -1c
.RI "#define \fBCCR_CLEAR_Mask\fP   ((uint32_t)0xFFFF800F)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CCR_CLEAR_Mask   ((uint32_t)0xFFFF800F)"

.PP
Definition at line 67 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel1_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF1\fP | \fBDMA_ISR_TCIF1\fP | \fBDMA_ISR_HTIF1\fP | \fBDMA_ISR_TEIF1\fP))"

.PP
Definition at line 48 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel2_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF2\fP | \fBDMA_ISR_TCIF2\fP | \fBDMA_ISR_HTIF2\fP | \fBDMA_ISR_TEIF2\fP))"

.PP
Definition at line 49 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel3_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF3\fP | \fBDMA_ISR_TCIF3\fP | \fBDMA_ISR_HTIF3\fP | \fBDMA_ISR_TEIF3\fP))"

.PP
Definition at line 50 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel4_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF4\fP | \fBDMA_ISR_TCIF4\fP | \fBDMA_ISR_HTIF4\fP | \fBDMA_ISR_TEIF4\fP))"

.PP
Definition at line 51 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel5_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF5\fP | \fBDMA_ISR_TCIF5\fP | \fBDMA_ISR_HTIF5\fP | \fBDMA_ISR_TEIF5\fP))"

.PP
Definition at line 52 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel6_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF6\fP | \fBDMA_ISR_TCIF6\fP | \fBDMA_ISR_HTIF6\fP | \fBDMA_ISR_TEIF6\fP))"

.PP
Definition at line 53 of file stm32f10x_dma\&.c\&.
.SS "#define DMA1_Channel7_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF7\fP | \fBDMA_ISR_TCIF7\fP | \fBDMA_ISR_HTIF7\fP | \fBDMA_ISR_TEIF7\fP))"

.PP
Definition at line 54 of file stm32f10x_dma\&.c\&.
.SS "#define DMA2_Channel1_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF1\fP | \fBDMA_ISR_TCIF1\fP | \fBDMA_ISR_HTIF1\fP | \fBDMA_ISR_TEIF1\fP))"

.PP
Definition at line 57 of file stm32f10x_dma\&.c\&.
.SS "#define DMA2_Channel2_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF2\fP | \fBDMA_ISR_TCIF2\fP | \fBDMA_ISR_HTIF2\fP | \fBDMA_ISR_TEIF2\fP))"

.PP
Definition at line 58 of file stm32f10x_dma\&.c\&.
.SS "#define DMA2_Channel3_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF3\fP | \fBDMA_ISR_TCIF3\fP | \fBDMA_ISR_HTIF3\fP | \fBDMA_ISR_TEIF3\fP))"

.PP
Definition at line 59 of file stm32f10x_dma\&.c\&.
.SS "#define DMA2_Channel4_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF4\fP | \fBDMA_ISR_TCIF4\fP | \fBDMA_ISR_HTIF4\fP | \fBDMA_ISR_TEIF4\fP))"

.PP
Definition at line 60 of file stm32f10x_dma\&.c\&.
.SS "#define DMA2_Channel5_IT_Mask   ((uint32_t)(\fBDMA_ISR_GIF5\fP | \fBDMA_ISR_TCIF5\fP | \fBDMA_ISR_HTIF5\fP | \fBDMA_ISR_TEIF5\fP))"

.PP
Definition at line 61 of file stm32f10x_dma\&.c\&.
.SS "#define FLAG_Mask   ((uint32_t)0x10000000)"

.PP
Definition at line 64 of file stm32f10x_dma\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
