.TH "DMA_Buffer_Size" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DMA_Buffer_Size
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_DMA_BUFFER_SIZE\fP(SIZE)   (((SIZE) >= 0x1) && ((SIZE) < 0x10000))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_DMA_BUFFER_SIZE(SIZE)   (((SIZE) >= 0x1) && ((SIZE) < 0x10000))"

.PP
Definition at line 388 of file stm32f10x_dma\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
