.TH "ExceptionStackFrame" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionStackFrame
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExceptionHandlers\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBr0\fP"
.br
.ti -1c
.RI "uint32_t \fBr1\fP"
.br
.ti -1c
.RI "uint32_t \fBr2\fP"
.br
.ti -1c
.RI "uint32_t \fBr3\fP"
.br
.ti -1c
.RI "uint32_t \fBr12\fP"
.br
.ti -1c
.RI "uint32_t \fBlr\fP"
.br
.ti -1c
.RI "uint32_t \fBpc\fP"
.br
.ti -1c
.RI "uint32_t \fBpsr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file ExceptionHandlers\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t ExceptionStackFrame::lr"

.PP
Definition at line 58 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::pc"

.PP
Definition at line 59 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::psr"

.PP
Definition at line 60 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::r0"

.PP
Definition at line 53 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::r1"

.PP
Definition at line 54 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::r12"

.PP
Definition at line 57 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::r2"

.PP
Definition at line 55 of file ExceptionHandlers\&.h\&.
.SS "uint32_t ExceptionStackFrame::r3"

.PP
Definition at line 56 of file ExceptionHandlers\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
