.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/cortexm/exception_handlers.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/cortexm/exception_handlers.c
.SH SYNOPSIS
.br
.PP
\fC#include 'cortexm/ExceptionHandlers\&.h'\fP
.br
\fC#include 'cmsis_device\&.h'\fP
.br
\fC#include 'arm/semihosting\&.h'\fP
.br
\fC#include 'diag/Trace\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__attribute__\fP ((noreturn, weak))"
.br
.ti -1c
.RI "void \fB__attribute__\fP ((section('\&.after_vectors'), weak))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((noreturn, weak))"

.PP
Definition at line 17 of file exception_handlers\&.c\&.
.SS "void __attribute__ ((section('\&.after_vectors'), weak))"

.PP
Definition at line 53 of file exception_handlers\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
