.TH "Exported_macro" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exported_macro
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSET_BIT\fP(REG,  BIT)   ((REG) |= (BIT))"
.br
.ti -1c
.RI "#define \fBCLEAR_BIT\fP(REG,  BIT)   ((REG) &= ~(BIT))"
.br
.ti -1c
.RI "#define \fBREAD_BIT\fP(REG,  BIT)   ((REG) & (BIT))"
.br
.ti -1c
.RI "#define \fBCLEAR_REG\fP(REG)   ((REG) = (0x0))"
.br
.ti -1c
.RI "#define \fBWRITE_REG\fP(REG,  VAL)   ((REG) = (VAL))"
.br
.ti -1c
.RI "#define \fBREAD_REG\fP(REG)   ((REG))"
.br
.ti -1c
.RI "#define \fBMODIFY_REG\fP(REG,  CLEARMASK,  SETMASK)   \fBWRITE_REG\fP((REG), (((\fBREAD_REG\fP(REG)) & (~(CLEARMASK))) | (SETMASK)))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEAR_BIT(REG, BIT)   ((REG) &= ~(BIT))"

.PP
Definition at line 8319 of file stm32f10x\&.h\&.
.SS "#define CLEAR_REG(REG)   ((REG) = (0x0))"

.PP
Definition at line 8323 of file stm32f10x\&.h\&.
.SS "#define MODIFY_REG(REG, CLEARMASK, SETMASK)   \fBWRITE_REG\fP((REG), (((\fBREAD_REG\fP(REG)) & (~(CLEARMASK))) | (SETMASK)))"

.PP
Definition at line 8329 of file stm32f10x\&.h\&.
.SS "#define READ_BIT(REG, BIT)   ((REG) & (BIT))"

.PP
Definition at line 8321 of file stm32f10x\&.h\&.
.SS "#define READ_REG(REG)   ((REG))"

.PP
Definition at line 8327 of file stm32f10x\&.h\&.
.SS "#define SET_BIT(REG, BIT)   ((REG) |= (BIT))"

.PP
Definition at line 8317 of file stm32f10x\&.h\&.
.SS "#define WRITE_REG(REG, VAL)   ((REG) = (VAL))"

.PP
Definition at line 8325 of file stm32f10x\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
