.TH "EXTI_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EXTI_TypeDef \- External Interrupt/Event Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBEMR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBFTSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSWIER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
External Interrupt/Event Controller\&. 
.PP
Definition at line 887 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::EMR"

.PP
Definition at line 890 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::FTSR"

.PP
Definition at line 892 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::IMR"

.PP
Definition at line 889 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::PR"

.PP
Definition at line 894 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::RTSR"

.PP
Definition at line 891 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t EXTI_TypeDef::SWIER"

.PP
Definition at line 893 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
