.TH "FLASH_Exported_Types" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFLASH_Status\fP { \fBFLASH_BUSY\fP = 1, \fBFLASH_ERROR_PG\fP, \fBFLASH_ERROR_WRP\fP, \fBFLASH_COMPLETE\fP, \fBFLASH_TIMEOUT\fP }
.RI "FLASH Status\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFLASH_Status\fP"

.PP
FLASH Status\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFLASH_BUSY \fP\fP
.TP
\fB\fIFLASH_ERROR_PG \fP\fP
.TP
\fB\fIFLASH_ERROR_WRP \fP\fP
.TP
\fB\fIFLASH_COMPLETE \fP\fP
.TP
\fB\fIFLASH_TIMEOUT \fP\fP
.PP
Definition at line 50 of file stm32f10x_flash\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
