.TH "FLASH_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLASH_TypeDef \- FLASH Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBACR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOPTKEYR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRESERVED\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBOBR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBWRPR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
FLASH Registers\&. 
.PP
Definition at line 901 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::ACR"

.PP
Definition at line 903 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::AR"

.PP
Definition at line 908 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::CR"

.PP
Definition at line 907 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::KEYR"

.PP
Definition at line 904 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::OBR"

.PP
Definition at line 910 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::OPTKEYR"

.PP
Definition at line 905 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::RESERVED"

.PP
Definition at line 909 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::SR"

.PP
Definition at line 906 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FLASH_TypeDef::WRPR"

.PP
Definition at line 911 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
