.TH "FSMC_Data_Address_Bus_Multiplexing" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Data_Address_Bus_Multiplexing
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_DataAddressMux_Disable\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBFSMC_DataAddressMux_Enable\fP   ((uint32_t)0x00000002)"
.br
.ti -1c
.RI "#define \fBIS_FSMC_MUX\fP(MUX)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_DataAddressMux_Disable   ((uint32_t)0x00000000)"

.PP
Definition at line 298 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_DataAddressMux_Enable   ((uint32_t)0x00000002)"

.PP
Definition at line 299 of file stm32f10x_fsmc\&.h\&.
.SS "#define IS_FSMC_MUX(MUX)"
\fBValue:\fP
.PP
.nf
(((MUX) == FSMC_DataAddressMux_Disable) || \
                          ((MUX) == FSMC_DataAddressMux_Enable))
.fi
.PP
Definition at line 300 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
