.TH "FSMC_Wait_Setup_Time" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Wait_Setup_Time
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_FSMC_WAIT_TIME\fP(TIME)   ((TIME) <= 0xFF)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_FSMC_WAIT_TIME(TIME)   ((TIME) <= 0xFF)"

.PP
Definition at line 616 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
