.TH "FSMC_NORSRAM_Bank" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_NORSRAM_Bank
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_Bank1_NORSRAM1\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBFSMC_Bank1_NORSRAM2\fP   ((uint32_t)0x00000002)"
.br
.ti -1c
.RI "#define \fBFSMC_Bank1_NORSRAM3\fP   ((uint32_t)0x00000004)"
.br
.ti -1c
.RI "#define \fBFSMC_Bank1_NORSRAM4\fP   ((uint32_t)0x00000006)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_Bank1_NORSRAM1   ((uint32_t)0x00000000)"

.PP
Definition at line 249 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_Bank1_NORSRAM2   ((uint32_t)0x00000002)"

.PP
Definition at line 250 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_Bank1_NORSRAM3   ((uint32_t)0x00000004)"

.PP
Definition at line 251 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_Bank1_NORSRAM4   ((uint32_t)0x00000006)"

.PP
Definition at line 252 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
