.TH "FSMC_ECC_Page_Size" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_ECC_Page_Size
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_256Bytes\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_512Bytes\fP   ((uint32_t)0x00020000)"
.br
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_1024Bytes\fP   ((uint32_t)0x00040000)"
.br
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_2048Bytes\fP   ((uint32_t)0x00060000)"
.br
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_4096Bytes\fP   ((uint32_t)0x00080000)"
.br
.ti -1c
.RI "#define \fBFSMC_ECCPageSize_8192Bytes\fP   ((uint32_t)0x000A0000)"
.br
.ti -1c
.RI "#define \fBIS_FSMC_ECCPAGE_SIZE\fP(SIZE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_ECCPageSize_1024Bytes   ((uint32_t)0x00040000)"

.PP
Definition at line 567 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_ECCPageSize_2048Bytes   ((uint32_t)0x00060000)"

.PP
Definition at line 568 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_ECCPageSize_256Bytes   ((uint32_t)0x00000000)"

.PP
Definition at line 565 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_ECCPageSize_4096Bytes   ((uint32_t)0x00080000)"

.PP
Definition at line 569 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_ECCPageSize_512Bytes   ((uint32_t)0x00020000)"

.PP
Definition at line 566 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_ECCPageSize_8192Bytes   ((uint32_t)0x000A0000)"

.PP
Definition at line 570 of file stm32f10x_fsmc\&.h\&.
.SS "#define IS_FSMC_ECCPAGE_SIZE(SIZE)"
\fBValue:\fP
.PP
.nf
(((SIZE) == FSMC_ECCPageSize_256Bytes) || \
                                    ((SIZE) == FSMC_ECCPageSize_512Bytes) || \
                                    ((SIZE) == FSMC_ECCPageSize_1024Bytes) || \
                                    ((SIZE) == FSMC_ECCPageSize_2048Bytes) || \
                                    ((SIZE) == FSMC_ECCPageSize_4096Bytes) || \
                                    ((SIZE) == FSMC_ECCPageSize_8192Bytes))
.fi
.PP
Definition at line 571 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
