.TH "FSMC_Exported_Types" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFSMC_NORSRAMTimingInitTypeDef\fP"
.br
.RI "Timing parameters For NOR/SRAM Banks\&. "
.ti -1c
.RI "struct \fBFSMC_NORSRAMInitTypeDef\fP"
.br
.RI "FSMC NOR/SRAM Init structure definition\&. "
.ti -1c
.RI "struct \fBFSMC_NAND_PCCARDTimingInitTypeDef\fP"
.br
.RI "Timing parameters For FSMC NAND and PCCARD Banks\&. "
.ti -1c
.RI "struct \fBFSMC_NANDInitTypeDef\fP"
.br
.RI "FSMC NAND Init structure definition\&. "
.ti -1c
.RI "struct \fBFSMC_PCCARDInitTypeDef\fP"
.br
.RI "FSMC PCCARD Init structure definition\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
