.TH "FSMC_Access_Mode" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Access_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_AccessMode_A\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBFSMC_AccessMode_B\fP   ((uint32_t)0x10000000)"
.br
.ti -1c
.RI "#define \fBFSMC_AccessMode_C\fP   ((uint32_t)0x20000000)"
.br
.ti -1c
.RI "#define \fBFSMC_AccessMode_D\fP   ((uint32_t)0x30000000)"
.br
.ti -1c
.RI "#define \fBIS_FSMC_ACCESS_MODE\fP(MODE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_AccessMode_A   ((uint32_t)0x00000000)"

.PP
Definition at line 513 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_AccessMode_B   ((uint32_t)0x10000000)"

.PP
Definition at line 514 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_AccessMode_C   ((uint32_t)0x20000000)"

.PP
Definition at line 515 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_AccessMode_D   ((uint32_t)0x30000000)"

.PP
Definition at line 516 of file stm32f10x_fsmc\&.h\&.
.SS "#define IS_FSMC_ACCESS_MODE(MODE)"
\fBValue:\fP
.PP
.nf
(((MODE) == FSMC_AccessMode_A) || \
                                   ((MODE) == FSMC_AccessMode_B) || \
                                   ((MODE) == FSMC_AccessMode_C) || \
                                   ((MODE) == FSMC_AccessMode_D))
.fi
.PP
Definition at line 517 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
