.TH "FSMC_Bank4_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Bank4_TypeDef \- Flexible Static Memory Controller Bank4\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPCR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPMEM4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPATT4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPIO4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Flexible Static Memory Controller Bank4\&. 
.PP
Definition at line 988 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t FSMC_Bank4_TypeDef::PATT4"

.PP
Definition at line 993 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FSMC_Bank4_TypeDef::PCR4"

.PP
Definition at line 990 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FSMC_Bank4_TypeDef::PIO4"

.PP
Definition at line 994 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FSMC_Bank4_TypeDef::PMEM4"

.PP
Definition at line 992 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t FSMC_Bank4_TypeDef::SR4"

.PP
Definition at line 991 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
