.TH "FSMC_Burst_Access_Mode" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Burst_Access_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFSMC_BurstAccessMode_Disable\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBFSMC_BurstAccessMode_Enable\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBIS_FSMC_BURSTMODE\fP(STATE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSMC_BurstAccessMode_Disable   ((uint32_t)0x00000000)"

.PP
Definition at line 339 of file stm32f10x_fsmc\&.h\&.
.SS "#define FSMC_BurstAccessMode_Enable   ((uint32_t)0x00000100)"

.PP
Definition at line 340 of file stm32f10x_fsmc\&.h\&.
.SS "#define IS_FSMC_BURSTMODE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == FSMC_BurstAccessMode_Disable) || \
                                  ((STATE) == FSMC_BurstAccessMode_Enable))
.fi
.PP
Definition at line 341 of file stm32f10x_fsmc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
