.TH "FSMC_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSMC_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBCR_MBKEN_Set\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBBCR_MBKEN_Reset\fP   ((uint32_t)0x000FFFFE)"
.br
.ti -1c
.RI "#define \fBBCR_FACCEN_Set\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBPCR_PBKEN_Set\fP   ((uint32_t)0x00000004)"
.br
.ti -1c
.RI "#define \fBPCR_PBKEN_Reset\fP   ((uint32_t)0x000FFFFB)"
.br
.ti -1c
.RI "#define \fBPCR_ECCEN_Set\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBPCR_ECCEN_Reset\fP   ((uint32_t)0x000FFFBF)"
.br
.ti -1c
.RI "#define \fBPCR_MemoryType_NAND\fP   ((uint32_t)0x00000008)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define BCR_FACCEN_Set   ((uint32_t)0x00000040)"

.PP
Definition at line 51 of file stm32f10x_fsmc\&.c\&.
.SS "#define BCR_MBKEN_Reset   ((uint32_t)0x000FFFFE)"

.PP
Definition at line 50 of file stm32f10x_fsmc\&.c\&.
.SS "#define BCR_MBKEN_Set   ((uint32_t)0x00000001)"

.PP
Definition at line 49 of file stm32f10x_fsmc\&.c\&.
.SS "#define PCR_ECCEN_Reset   ((uint32_t)0x000FFFBF)"

.PP
Definition at line 57 of file stm32f10x_fsmc\&.c\&.
.SS "#define PCR_ECCEN_Set   ((uint32_t)0x00000040)"

.PP
Definition at line 56 of file stm32f10x_fsmc\&.c\&.
.SS "#define PCR_MemoryType_NAND   ((uint32_t)0x00000008)"

.PP
Definition at line 58 of file stm32f10x_fsmc\&.c\&.
.SS "#define PCR_PBKEN_Reset   ((uint32_t)0x000FFFFB)"

.PP
Definition at line 55 of file stm32f10x_fsmc\&.c\&.
.SS "#define PCR_PBKEN_Set   ((uint32_t)0x00000004)"

.PP
Definition at line 54 of file stm32f10x_fsmc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
