.TH "GPIO_InitTypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_InitTypeDef \- GPIO Init structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x_gpio\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBGPIO_Pin\fP"
.br
.ti -1c
.RI "\fBGPIOSpeed_TypeDef\fP \fBGPIO_Speed\fP"
.br
.ti -1c
.RI "\fBGPIOMode_TypeDef\fP \fBGPIO_Mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPIO Init structure definition\&. 
.PP
Definition at line 91 of file stm32f10x_gpio\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGPIOMode_TypeDef\fP GPIO_InitTypeDef::GPIO_Mode"
Specifies the operating mode for the selected pins\&. This parameter can be a value of \fBGPIOMode_TypeDef\fP 
.PP
Definition at line 99 of file stm32f10x_gpio\&.h\&.
.SS "uint16_t GPIO_InitTypeDef::GPIO_Pin"
Specifies the GPIO pins to be configured\&. This parameter can be any value of \fBGPIO_pins_define\fP 
.PP
Definition at line 93 of file stm32f10x_gpio\&.h\&.
.SS "\fBGPIOSpeed_TypeDef\fP GPIO_InitTypeDef::GPIO_Speed"
Specifies the speed for the selected pins\&. This parameter can be a value of \fBGPIOSpeed_TypeDef\fP 
.PP
Definition at line 96 of file stm32f10x_gpio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
