.TH "GPIO_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_TypeDef \- General Purpose I/O\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRL\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCRH\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBIDR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBODR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBSRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBRR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBLCKR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General Purpose I/O\&. 
.PP
Definition at line 1001 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::BRR"

.PP
Definition at line 1008 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::BSRR"

.PP
Definition at line 1007 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::CRH"

.PP
Definition at line 1004 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::CRL"

.PP
Definition at line 1003 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::IDR"

.PP
Definition at line 1005 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::LCKR"

.PP
Definition at line 1009 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t GPIO_TypeDef::ODR"

.PP
Definition at line 1006 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
