.TH "GPIO_Port_Sources" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GPIO_Port_Sources
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOA\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOB\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOC\fP   ((uint8_t)0x02)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOD\fP   ((uint8_t)0x03)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOE\fP   ((uint8_t)0x04)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOF\fP   ((uint8_t)0x05)"
.br
.ti -1c
.RI "#define \fBGPIO_PortSourceGPIOG\fP   ((uint8_t)0x06)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_EVENTOUT_PORT_SOURCE\fP(PORTSOURCE)"
.br
.ti -1c
.RI "#define \fBIS_GPIO_EXTI_PORT_SOURCE\fP(PORTSOURCE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define GPIO_PortSourceGPIOA   ((uint8_t)0x00)"

.PP
Definition at line 257 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOB   ((uint8_t)0x01)"

.PP
Definition at line 258 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOC   ((uint8_t)0x02)"

.PP
Definition at line 259 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOD   ((uint8_t)0x03)"

.PP
Definition at line 260 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOE   ((uint8_t)0x04)"

.PP
Definition at line 261 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOF   ((uint8_t)0x05)"

.PP
Definition at line 262 of file stm32f10x_gpio\&.h\&.
.SS "#define GPIO_PortSourceGPIOG   ((uint8_t)0x06)"

.PP
Definition at line 263 of file stm32f10x_gpio\&.h\&.
.SS "#define IS_GPIO_EVENTOUT_PORT_SOURCE(PORTSOURCE)"
\fBValue:\fP
.PP
.nf
(((PORTSOURCE) == GPIO_PortSourceGPIOA) || \
                                                  ((PORTSOURCE) == GPIO_PortSourceGPIOB) || \
                                                  ((PORTSOURCE) == GPIO_PortSourceGPIOC) || \
                                                  ((PORTSOURCE) == GPIO_PortSourceGPIOD) || \
                                                  ((PORTSOURCE) == GPIO_PortSourceGPIOE))
.fi
.PP
Definition at line 264 of file stm32f10x_gpio\&.h\&.
.SS "#define IS_GPIO_EXTI_PORT_SOURCE(PORTSOURCE)"
\fBValue:\fP
.PP
.nf
(((PORTSOURCE) == GPIO_PortSourceGPIOA) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOB) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOC) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOD) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOE) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOF) || \
                                              ((PORTSOURCE) == GPIO_PortSourceGPIOG))
.fi
.PP
Definition at line 270 of file stm32f10x_gpio\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
