.TH "groupCmplxMath" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupCmplxMath
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This set of functions operates on complex data vectors\&. The data in the complex arrays is stored in an interleaved fashion (real, imag, real, imag, \&.\&.\&.)\&. In the API functions, the number of samples in a complex array refers to the number of complex values; the array contains twice this number of real values\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
