.TH "groupFastMath" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
groupFastMath
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBSquare Root\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This set of functions provides a fast approximation to sine, cosine, and square root\&. As compared to most of the other functions in the CMSIS math library, the fast math functions operate on individual values and not arrays\&. There are separate functions for Q15, Q31, and floating-point data\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
