.TH "I2C_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_TypeDef \- Inter Integrated Circuit Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBOAR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBOAR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTRISE\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inter Integrated Circuit Interface\&. 
.PP
Definition at line 1028 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint16_t I2C_TypeDef::CCR"

.PP
Definition at line 1044 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::CR1"

.PP
Definition at line 1030 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::CR2"

.PP
Definition at line 1032 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::DR"

.PP
Definition at line 1038 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::OAR1"

.PP
Definition at line 1034 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::OAR2"

.PP
Definition at line 1036 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED0"

.PP
Definition at line 1031 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED1"

.PP
Definition at line 1033 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED2"

.PP
Definition at line 1035 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED3"

.PP
Definition at line 1037 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED4"

.PP
Definition at line 1039 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED5"

.PP
Definition at line 1041 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED6"

.PP
Definition at line 1043 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED7"

.PP
Definition at line 1045 of file stm32f10x\&.h\&.
.SS "uint16_t I2C_TypeDef::RESERVED8"

.PP
Definition at line 1047 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::SR1"

.PP
Definition at line 1040 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::SR2"

.PP
Definition at line 1042 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t I2C_TypeDef::TRISE"

.PP
Definition at line 1046 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
