.TH "I2C_transfer_direction" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_transfer_direction
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBI2C_Direction_Transmitter\fP   ((uint8_t)0x00)"
.br
.ti -1c
.RI "#define \fBI2C_Direction_Receiver\fP   ((uint8_t)0x01)"
.br
.ti -1c
.RI "#define \fBIS_I2C_DIRECTION\fP(DIRECTION)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define I2C_Direction_Receiver   ((uint8_t)0x01)"

.PP
Definition at line 131 of file stm32f10x_i2c\&.h\&.
.SS "#define I2C_Direction_Transmitter   ((uint8_t)0x00)"

.PP
Definition at line 130 of file stm32f10x_i2c\&.h\&.
.SS "#define IS_I2C_DIRECTION(DIRECTION)"
\fBValue:\fP
.PP
.nf
(((DIRECTION) == I2C_Direction_Transmitter) || \
                                     ((DIRECTION) == I2C_Direction_Receiver))
.fi
.PP
Definition at line 132 of file stm32f10x_i2c\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
