.TH "I2C_clock_speed" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2C_clock_speed
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_I2C_CLOCK_SPEED\fP(SPEED)   (((SPEED) >= 0x1) && ((SPEED) <= 400000))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_I2C_CLOCK_SPEED(SPEED)   (((SPEED) >= 0x1) && ((SPEED) <= 400000))"

.PP
Definition at line 519 of file stm32f10x_i2c\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
