.TH "I2S_InitTypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
I2S_InitTypeDef \- I2S Init structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x_spi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBI2S_Mode\fP"
.br
.ti -1c
.RI "uint16_t \fBI2S_Standard\fP"
.br
.ti -1c
.RI "uint16_t \fBI2S_DataFormat\fP"
.br
.ti -1c
.RI "uint16_t \fBI2S_MCLKOutput\fP"
.br
.ti -1c
.RI "uint32_t \fBI2S_AudioFreq\fP"
.br
.ti -1c
.RI "uint16_t \fBI2S_CPOL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
I2S Init structure definition\&. 
.PP
Definition at line 93 of file stm32f10x_spi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t I2S_InitTypeDef::I2S_AudioFreq"
Specifies the frequency selected for the I2S communication\&. This parameter can be a value of \fBI2S_Audio_Frequency\fP 
.PP
Definition at line 108 of file stm32f10x_spi\&.h\&.
.SS "uint16_t I2S_InitTypeDef::I2S_CPOL"
Specifies the idle state of the I2S clock\&. This parameter can be a value of \fBI2S_Clock_Polarity\fP 
.PP
Definition at line 111 of file stm32f10x_spi\&.h\&.
.SS "uint16_t I2S_InitTypeDef::I2S_DataFormat"
Specifies the data format for the I2S communication\&. This parameter can be a value of \fBI2S_Data_Format\fP 
.PP
Definition at line 102 of file stm32f10x_spi\&.h\&.
.SS "uint16_t I2S_InitTypeDef::I2S_MCLKOutput"
Specifies whether the I2S MCLK output is enabled or not\&. This parameter can be a value of \fBI2S_MCLK_Output\fP 
.PP
Definition at line 105 of file stm32f10x_spi\&.h\&.
.SS "uint16_t I2S_InitTypeDef::I2S_Mode"
Specifies the I2S operating mode\&. This parameter can be a value of \fBI2S_Mode\fP 
.PP
Definition at line 96 of file stm32f10x_spi\&.h\&.
.SS "uint16_t I2S_InitTypeDef::I2S_Standard"
Specifies the standard used for the I2S communication\&. This parameter can be a value of \fBI2S_Standard\fP 
.PP
Definition at line 99 of file stm32f10x_spi\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
