.TH "IPSR_Type" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPSR_Type \- Union type to access the Interrupt Program Status Register (IPSR)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <core_cm0\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "uint32_t \fBw\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint32_t \fBISR\fP:9"
.br
.ti -1c
.RI "   uint32_t \fB_reserved0\fP:23"
.br
.ti -1c
.RI "} \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Union type to access the Interrupt Program Status Register (IPSR)\&. 
.PP
Definition at line 285 of file core_cm0\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t IPSR_Type::_reserved0"
bit: 9\&.\&.31 Reserved 
.PP
Definition at line 290 of file core_cm0\&.h\&.
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "struct { \&.\&.\&. }   IPSR_Type::b"
Structure used for bit access 
.SS "uint32_t IPSR_Type::ISR"
bit: 0\&.\&. 8 Exception number 
.PP
Definition at line 289 of file core_cm0\&.h\&.
.SS "uint32_t IPSR_Type::w"
Type used for word access 
.PP
Definition at line 292 of file core_cm0\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
