.TH "IWDG_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_TypeDef \- Independent WATCHDOG\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBKR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBPR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBRLR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Independent WATCHDOG\&. 
.PP
Definition at line 1054 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::KR"

.PP
Definition at line 1056 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::PR"

.PP
Definition at line 1057 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::RLR"

.PP
Definition at line 1058 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t IWDG_TypeDef::SR"

.PP
Definition at line 1059 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
