.TH "IWDG_Private_Functions" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IWDG_Private_Functions
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBIWDG_WriteAccessCmd\fP (uint16_t IWDG_WriteAccess)"
.br
.RI "Enables or disables write access to IWDG_PR and IWDG_RLR registers\&. "
.ti -1c
.RI "void \fBIWDG_SetPrescaler\fP (uint8_t IWDG_Prescaler)"
.br
.RI "Sets IWDG Prescaler value\&. "
.ti -1c
.RI "void \fBIWDG_SetReload\fP (uint16_t Reload)"
.br
.RI "Sets IWDG Reload value\&. "
.ti -1c
.RI "void \fBIWDG_ReloadCounter\fP (void)"
.br
.RI "Reloads IWDG counter with value defined in the reload register (write access to IWDG_PR and IWDG_RLR registers disabled)\&. "
.ti -1c
.RI "void \fBIWDG_Enable\fP (void)"
.br
.RI "Enables IWDG (write access to IWDG_PR and IWDG_RLR registers disabled)\&. "
.ti -1c
.RI "\fBFlagStatus\fP \fBIWDG_GetFlagStatus\fP (uint16_t IWDG_FLAG)"
.br
.RI "Checks whether the specified IWDG flag is set or not\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "void IWDG_Enable (void)"

.PP
Enables IWDG (write access to IWDG_PR and IWDG_RLR registers disabled)\&. 
.PP
\fBParameters:\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 148 of file stm32f10x_iwdg\&.c\&.
.SS "\fBFlagStatus\fP IWDG_GetFlagStatus (uint16_t IWDG_FLAG)"

.PP
Checks whether the specified IWDG flag is set or not\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIWDG_FLAG\fP specifies the flag to check\&. This parameter can be one of the following values: 
.PD 0

.IP "\(bu" 2
IWDG_FLAG_PVU: Prescaler Value Update on going 
.IP "\(bu" 2
IWDG_FLAG_RVU: Reload Value Update on going 
.PP
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIThe\fP new state of IWDG_FLAG (SET or RESET)\&. 
.RE
.PP

.PP
Definition at line 161 of file stm32f10x_iwdg\&.c\&.
.SS "void IWDG_ReloadCounter (void)"

.PP
Reloads IWDG counter with value defined in the reload register (write access to IWDG_PR and IWDG_RLR registers disabled)\&. 
.PP
\fBParameters:\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 138 of file stm32f10x_iwdg\&.c\&.
.SS "void IWDG_SetPrescaler (uint8_t IWDG_Prescaler)"

.PP
Sets IWDG Prescaler value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIWDG_Prescaler\fP specifies the IWDG Prescaler value\&. This parameter can be one of the following values: 
.PD 0

.IP "\(bu" 2
IWDG_Prescaler_4: IWDG prescaler set to 4 
.IP "\(bu" 2
IWDG_Prescaler_8: IWDG prescaler set to 8 
.IP "\(bu" 2
IWDG_Prescaler_16: IWDG prescaler set to 16 
.IP "\(bu" 2
IWDG_Prescaler_32: IWDG prescaler set to 32 
.IP "\(bu" 2
IWDG_Prescaler_64: IWDG prescaler set to 64 
.IP "\(bu" 2
IWDG_Prescaler_128: IWDG prescaler set to 128 
.IP "\(bu" 2
IWDG_Prescaler_256: IWDG prescaler set to 256 
.PP
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 112 of file stm32f10x_iwdg\&.c\&.
.SS "void IWDG_SetReload (uint16_t Reload)"

.PP
Sets IWDG Reload value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIReload\fP specifies the IWDG Reload value\&. This parameter must be a number between 0 and 0x0FFF\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 125 of file stm32f10x_iwdg\&.c\&.
.SS "void IWDG_WriteAccessCmd (uint16_t IWDG_WriteAccess)"

.PP
Enables or disables write access to IWDG_PR and IWDG_RLR registers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIIWDG_WriteAccess\fP new state of write access to IWDG_PR and IWDG_RLR registers\&. This parameter can be one of the following values: 
.PD 0

.IP "\(bu" 2
IWDG_WriteAccess_Enable: Enable write access to IWDG_PR and IWDG_RLR registers 
.IP "\(bu" 2
IWDG_WriteAccess_Disable: Disable write access to IWDG_PR and IWDG_RLR registers 
.PP
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.PP
Definition at line 92 of file stm32f10x_iwdg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
