.TH "LinearInterpolate" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearInterpolate
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Linear interpolation is a method of curve fitting using linear polynomials\&. Linear interpolation works by effectively drawing a straight line between two neighboring samples and returning the appropriate point along that line
.PP
\fB\fP
.RS 4
Linear interpolation 
.RE
.PP
\fB\fP
.RS 4
A Linear Interpolate function calculates an output value(y), for the input(x) using linear interpolation of the input values x0, x1( nearest input values) and the output values y0 and y1(nearest output values)
.RE
.PP
\fBAlgorithm:\fP
.RS 4

.PP
.nf

      y = y0 + (x - x0) * ((y1 - y0)/(x1-x0))
      where x0, x1 are nearest values of input x
            y0, y1 are nearest values to output y
.fi
.PP
.RE
.PP
\fB\fP
.RS 4
This set of functions implements Linear interpolation process for Q7, Q15, Q31, and floating-point data types\&. The functions operate on a single sample of data and each call to the function returns a single processed value\&. \fCS\fP points to an instance of the Linear Interpolate function data structure\&. \fCx\fP is the input sample value\&. The functions returns the output value\&.
.RE
.PP
\fB\fP
.RS 4
if x is outside of the table boundary, Linear interpolation returns first value of the table if x is below input range and returns last value of table if x is above range\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
