.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/misc.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/misc.c \- This file provides all the miscellaneous firmware functions (add-on to CMSIS functions)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'misc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAIRCR_VECTKEY_MASK\fP   ((uint32_t)0x05FA0000)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBNVIC_PriorityGroupConfig\fP (uint32_t NVIC_PriorityGroup)"
.br
.RI "Configures the priority grouping: pre-emption priority and subpriority\&. "
.ti -1c
.RI "void \fBNVIC_Init\fP (\fBNVIC_InitTypeDef\fP *NVIC_InitStruct)"
.br
.RI "Initializes the NVIC peripheral according to the specified parameters in the NVIC_InitStruct\&. "
.ti -1c
.RI "void \fBNVIC_SetVectorTable\fP (uint32_t NVIC_VectTab, uint32_t Offset)"
.br
.RI "Sets the vector table location and Offset\&. "
.ti -1c
.RI "void \fBNVIC_SystemLPConfig\fP (uint8_t LowPowerMode, \fBFunctionalState\fP NewState)"
.br
.RI "Selects the condition for the system to enter low power mode\&. "
.ti -1c
.RI "void \fBSysTick_CLKSourceConfig\fP (uint32_t SysTick_CLKSource)"
.br
.RI "Configures the SysTick clock source\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file provides all the miscellaneous firmware functions (add-on to CMSIS functions)\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBmisc\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
