.TH "NOR_SRAM_Controller" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NOR_SRAM_Controller
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBFSMC_Data_Address_Bus_Multiplexing\fP"
.br
.ti -1c
.RI "\fBFSMC_Memory_Type\fP"
.br
.ti -1c
.RI "\fBFSMC_Data_Width\fP"
.br
.ti -1c
.RI "\fBFSMC_Burst_Access_Mode\fP"
.br
.ti -1c
.RI "\fBFSMC_AsynchronousWait\fP"
.br
.ti -1c
.RI "\fBFSMC_Wait_Signal_Polarity\fP"
.br
.ti -1c
.RI "\fBFSMC_Wrap_Mode\fP"
.br
.ti -1c
.RI "\fBFSMC_Wait_Timing\fP"
.br
.ti -1c
.RI "\fBFSMC_Write_Operation\fP"
.br
.ti -1c
.RI "\fBFSMC_Wait_Signal\fP"
.br
.ti -1c
.RI "\fBFSMC_Extended_Mode\fP"
.br
.ti -1c
.RI "\fBFSMC_Write_Burst\fP"
.br
.ti -1c
.RI "\fBFSMC_Address_Setup_Time\fP"
.br
.ti -1c
.RI "\fBFSMC_Address_Hold_Time\fP"
.br
.ti -1c
.RI "\fBFSMC_Data_Setup_Time\fP"
.br
.ti -1c
.RI "\fBFSMC_Bus_Turn_around_Duration\fP"
.br
.ti -1c
.RI "\fBFSMC_CLK_Division\fP"
.br
.ti -1c
.RI "\fBFSMC_Data_Latency\fP"
.br
.ti -1c
.RI "\fBFSMC_Access_Mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
