.TH "OB_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OB_TypeDef \- Option Bytes Registers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRDP\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBUSER\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBData1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBWRP3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Option Bytes Registers\&. 
.PP
Definition at line 926 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint16_t OB_TypeDef::Data0"

.PP
Definition at line 930 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::Data1"

.PP
Definition at line 931 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::RDP"

.PP
Definition at line 928 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::USER"

.PP
Definition at line 929 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP0"

.PP
Definition at line 932 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP1"

.PP
Definition at line 933 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP2"

.PP
Definition at line 934 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t OB_TypeDef::WRP3"

.PP
Definition at line 935 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
