.TH "OSSI_Off_State_Selection_for_Idle_mode_state" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSSI_Off_State_Selection_for_Idle_mode_state
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OSSIState_Enable\fP   ((uint16_t)0x0400)"
.br
.ti -1c
.RI "#define \fBTIM_OSSIState_Disable\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OSSI_STATE\fP(STATE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_OSSI_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == TIM_OSSIState_Enable) || \
                                  ((STATE) == TIM_OSSIState_Disable))
.fi
.PP
Definition at line 513 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OSSIState_Disable   ((uint16_t)0x0000)"

.PP
Definition at line 512 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OSSIState_Enable   ((uint16_t)0x0400)"

.PP
Definition at line 511 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
