.TH "OSSR_Off_State_Selection_for_Run_mode_state" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSSR_Off_State_Selection_for_Run_mode_state
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OSSRState_Enable\fP   ((uint16_t)0x0800)"
.br
.ti -1c
.RI "#define \fBTIM_OSSRState_Disable\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OSSR_STATE\fP(STATE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_OSSR_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == TIM_OSSRState_Enable) || \
                                  ((STATE) == TIM_OSSRState_Disable))
.fi
.PP
Definition at line 525 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OSSRState_Disable   ((uint16_t)0x0000)"

.PP
Definition at line 524 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OSSRState_Enable   ((uint16_t)0x0800)"

.PP
Definition at line 523 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
