.TH "Peripheral_registers_structures" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Peripheral_registers_structures
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBADC_TypeDef\fP"
.br
.RI "Analog to Digital Converter\&. "
.ti -1c
.RI "struct \fBBKP_TypeDef\fP"
.br
.RI "Backup Registers\&. "
.ti -1c
.RI "struct \fBCAN_TxMailBox_TypeDef\fP"
.br
.RI "Controller Area Network TxMailBox\&. "
.ti -1c
.RI "struct \fBCAN_FIFOMailBox_TypeDef\fP"
.br
.RI "Controller Area Network FIFOMailBox\&. "
.ti -1c
.RI "struct \fBCAN_FilterRegister_TypeDef\fP"
.br
.RI "Controller Area Network FilterRegister\&. "
.ti -1c
.RI "struct \fBCAN_TypeDef\fP"
.br
.RI "Controller Area Network\&. "
.ti -1c
.RI "struct \fBCEC_TypeDef\fP"
.br
.RI "Consumer Electronics Control (CEC) "
.ti -1c
.RI "struct \fBCRC_TypeDef\fP"
.br
.RI "CRC calculation unit\&. "
.ti -1c
.RI "struct \fBDAC_TypeDef\fP"
.br
.RI "Digital to Analog Converter\&. "
.ti -1c
.RI "struct \fBDBGMCU_TypeDef\fP"
.br
.RI "Debug MCU\&. "
.ti -1c
.RI "struct \fBDMA_Channel_TypeDef\fP"
.br
.RI "DMA Controller\&. "
.ti -1c
.RI "struct \fBDMA_TypeDef\fP"
.br
.ti -1c
.RI "struct \fBETH_TypeDef\fP"
.br
.RI "Ethernet MAC\&. "
.ti -1c
.RI "struct \fBEXTI_TypeDef\fP"
.br
.RI "External Interrupt/Event Controller\&. "
.ti -1c
.RI "struct \fBFLASH_TypeDef\fP"
.br
.RI "FLASH Registers\&. "
.ti -1c
.RI "struct \fBOB_TypeDef\fP"
.br
.RI "Option Bytes Registers\&. "
.ti -1c
.RI "struct \fBFSMC_Bank1_TypeDef\fP"
.br
.RI "Flexible Static Memory Controller\&. "
.ti -1c
.RI "struct \fBFSMC_Bank1E_TypeDef\fP"
.br
.RI "Flexible Static Memory Controller Bank1E\&. "
.ti -1c
.RI "struct \fBFSMC_Bank2_TypeDef\fP"
.br
.RI "Flexible Static Memory Controller Bank2\&. "
.ti -1c
.RI "struct \fBFSMC_Bank3_TypeDef\fP"
.br
.RI "Flexible Static Memory Controller Bank3\&. "
.ti -1c
.RI "struct \fBFSMC_Bank4_TypeDef\fP"
.br
.RI "Flexible Static Memory Controller Bank4\&. "
.ti -1c
.RI "struct \fBGPIO_TypeDef\fP"
.br
.RI "General Purpose I/O\&. "
.ti -1c
.RI "struct \fBAFIO_TypeDef\fP"
.br
.RI "Alternate Function I/O\&. "
.ti -1c
.RI "struct \fBI2C_TypeDef\fP"
.br
.RI "Inter Integrated Circuit Interface\&. "
.ti -1c
.RI "struct \fBIWDG_TypeDef\fP"
.br
.RI "Independent WATCHDOG\&. "
.ti -1c
.RI "struct \fBPWR_TypeDef\fP"
.br
.RI "Power Control\&. "
.ti -1c
.RI "struct \fBRCC_TypeDef\fP"
.br
.RI "Reset and Clock Control\&. "
.ti -1c
.RI "struct \fBRTC_TypeDef\fP"
.br
.RI "Real-Time Clock\&. "
.ti -1c
.RI "struct \fBSDIO_TypeDef\fP"
.br
.RI "SD host Interface\&. "
.ti -1c
.RI "struct \fBSPI_TypeDef\fP"
.br
.RI "Serial Peripheral Interface\&. "
.ti -1c
.RI "struct \fBTIM_TypeDef\fP"
.br
.RI "TIM\&. "
.ti -1c
.RI "struct \fBUSART_TypeDef\fP"
.br
.RI "Universal Synchronous Asynchronous Receiver Transmitter\&. "
.ti -1c
.RI "struct \fBWWDG_TypeDef\fP"
.br
.RI "Window WATCHDOG\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
