.TH "PLL_multiplication_factor" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PLL_multiplication_factor
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRCC_PLLMul_2\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_3\fP   ((uint32_t)0x00040000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_4\fP   ((uint32_t)0x00080000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_5\fP   ((uint32_t)0x000C0000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_6\fP   ((uint32_t)0x00100000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_7\fP   ((uint32_t)0x00140000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_8\fP   ((uint32_t)0x00180000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_9\fP   ((uint32_t)0x001C0000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_10\fP   ((uint32_t)0x00200000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_11\fP   ((uint32_t)0x00240000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_12\fP   ((uint32_t)0x00280000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_13\fP   ((uint32_t)0x002C0000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_14\fP   ((uint32_t)0x00300000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_15\fP   ((uint32_t)0x00340000)"
.br
.ti -1c
.RI "#define \fBRCC_PLLMul_16\fP   ((uint32_t)0x00380000)"
.br
.ti -1c
.RI "#define \fBIS_RCC_PLL_MUL\fP(MUL)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_RCC_PLL_MUL(MUL)"
\fBValue:\fP
.PP
.nf
(((MUL) == RCC_PLLMul_2) || ((MUL) == RCC_PLLMul_3)   || \
                              ((MUL) == RCC_PLLMul_4) || ((MUL) == RCC_PLLMul_5)   || \
                              ((MUL) == RCC_PLLMul_6) || ((MUL) == RCC_PLLMul_7)   || \
                              ((MUL) == RCC_PLLMul_8) || ((MUL) == RCC_PLLMul_9)   || \
                              ((MUL) == RCC_PLLMul_10) || ((MUL) == RCC_PLLMul_11) || \
                              ((MUL) == RCC_PLLMul_12) || ((MUL) == RCC_PLLMul_13) || \
                              ((MUL) == RCC_PLLMul_14) || ((MUL) == RCC_PLLMul_15) || \
                              ((MUL) == RCC_PLLMul_16))
.fi
.PP
Definition at line 118 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_10   ((uint32_t)0x00200000)"

.PP
Definition at line 111 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_11   ((uint32_t)0x00240000)"

.PP
Definition at line 112 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_12   ((uint32_t)0x00280000)"

.PP
Definition at line 113 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_13   ((uint32_t)0x002C0000)"

.PP
Definition at line 114 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_14   ((uint32_t)0x00300000)"

.PP
Definition at line 115 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_15   ((uint32_t)0x00340000)"

.PP
Definition at line 116 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_16   ((uint32_t)0x00380000)"

.PP
Definition at line 117 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_2   ((uint32_t)0x00000000)"

.PP
Definition at line 103 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_3   ((uint32_t)0x00040000)"

.PP
Definition at line 104 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_4   ((uint32_t)0x00080000)"

.PP
Definition at line 105 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_5   ((uint32_t)0x000C0000)"

.PP
Definition at line 106 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_6   ((uint32_t)0x00100000)"

.PP
Definition at line 107 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_7   ((uint32_t)0x00140000)"

.PP
Definition at line 108 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_8   ((uint32_t)0x00180000)"

.PP
Definition at line 109 of file stm32f10x_rcc\&.h\&.
.SS "#define RCC_PLLMul_9   ((uint32_t)0x001C0000)"

.PP
Definition at line 110 of file stm32f10x_rcc\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
