.TH "PVD_detection_level" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PVD_detection_level
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V2\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V3\fP   ((uint32_t)0x00000020)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V4\fP   ((uint32_t)0x00000040)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V5\fP   ((uint32_t)0x00000060)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V6\fP   ((uint32_t)0x00000080)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V7\fP   ((uint32_t)0x000000A0)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V8\fP   ((uint32_t)0x000000C0)"
.br
.ti -1c
.RI "#define \fBPWR_PVDLevel_2V9\fP   ((uint32_t)0x000000E0)"
.br
.ti -1c
.RI "#define \fBIS_PWR_PVD_LEVEL\fP(LEVEL)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_PWR_PVD_LEVEL(LEVEL)"
\fBValue:\fP
.PP
.nf
(((LEVEL) == PWR_PVDLevel_2V2) || ((LEVEL) == PWR_PVDLevel_2V3)|| \
                                 ((LEVEL) == PWR_PVDLevel_2V4) || ((LEVEL) == PWR_PVDLevel_2V5)|| \
                                 ((LEVEL) == PWR_PVDLevel_2V6) || ((LEVEL) == PWR_PVDLevel_2V7)|| \
                                 ((LEVEL) == PWR_PVDLevel_2V8) || ((LEVEL) == PWR_PVDLevel_2V9))
.fi
.PP
Definition at line 66 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V2   ((uint32_t)0x00000000)"

.PP
Definition at line 58 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V3   ((uint32_t)0x00000020)"

.PP
Definition at line 59 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V4   ((uint32_t)0x00000040)"

.PP
Definition at line 60 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V5   ((uint32_t)0x00000060)"

.PP
Definition at line 61 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V6   ((uint32_t)0x00000080)"

.PP
Definition at line 62 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V7   ((uint32_t)0x000000A0)"

.PP
Definition at line 63 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V8   ((uint32_t)0x000000C0)"

.PP
Definition at line 64 of file stm32f10x_pwr\&.h\&.
.SS "#define PWR_PVDLevel_2V9   ((uint32_t)0x000000E0)"

.PP
Definition at line 65 of file stm32f10x_pwr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
