.TH "PWR_Exported_Constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PWR_Exported_Constants
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBPVD_detection_level\fP"
.br
.ti -1c
.RI "\fBRegulator_state_is_STOP_mode\fP"
.br
.ti -1c
.RI "\fBSTOP_mode_entry\fP"
.br
.ti -1c
.RI "\fBPWR_Flag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
