.TH "RCC_ClocksTypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_ClocksTypeDef
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x_rcc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBSYSCLK_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBHCLK_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBPCLK1_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBPCLK2_Frequency\fP"
.br
.ti -1c
.RI "uint32_t \fBADCCLK_Frequency\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file stm32f10x_rcc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t RCC_ClocksTypeDef::ADCCLK_Frequency"
returns ADCCLK clock frequency expressed in Hz 
.PP
Definition at line 52 of file stm32f10x_rcc\&.h\&.
.SS "uint32_t RCC_ClocksTypeDef::HCLK_Frequency"
returns HCLK clock frequency expressed in Hz 
.PP
Definition at line 49 of file stm32f10x_rcc\&.h\&.
.SS "uint32_t RCC_ClocksTypeDef::PCLK1_Frequency"
returns PCLK1 clock frequency expressed in Hz 
.PP
Definition at line 50 of file stm32f10x_rcc\&.h\&.
.SS "uint32_t RCC_ClocksTypeDef::PCLK2_Frequency"
returns PCLK2 clock frequency expressed in Hz 
.PP
Definition at line 51 of file stm32f10x_rcc\&.h\&.
.SS "uint32_t RCC_ClocksTypeDef::SYSCLK_Frequency"
returns SYSCLK clock frequency expressed in Hz 
.PP
Definition at line 48 of file stm32f10x_rcc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
