.TH "RCC_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RCC_TypeDef \- Reset and Clock Control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCFGR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCIR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1RSTR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAHBENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB2ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBAPB1ENR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBBDCR\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint32_t \fBCSR\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Reset and Clock Control\&. 
.PP
Definition at line 1076 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint32_t RCC_TypeDef::AHBENR"

.PP
Definition at line 1083 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB1ENR"

.PP
Definition at line 1085 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB1RSTR"

.PP
Definition at line 1082 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB2ENR"

.PP
Definition at line 1084 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::APB2RSTR"

.PP
Definition at line 1081 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::BDCR"

.PP
Definition at line 1086 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::CFGR"

.PP
Definition at line 1079 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::CIR"

.PP
Definition at line 1080 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::CR"

.PP
Definition at line 1078 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint32_t RCC_TypeDef::CSR"

.PP
Definition at line 1087 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
