.TH "RTC_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RTC_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRTC_LSB_MASK\fP   ((uint32_t)0x0000FFFF)"
.br
.ti -1c
.RI "#define \fBPRLH_MSB_MASK\fP   ((uint32_t)0x000F0000)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define PRLH_MSB_MASK   ((uint32_t)0x000F0000)"
RTC Prescaler MSB Mask 
.PP
Definition at line 45 of file stm32f10x_rtc\&.c\&.
.SS "#define RTC_LSB_MASK   ((uint32_t)0x0000FFFF)"
RTC LSB Mask 
.PP
Definition at line 44 of file stm32f10x_rtc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
