.TH "SDIO_Wait_Interrupt_State" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDIO_Wait_Interrupt_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDIO_Wait_No\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBSDIO_Wait_IT\fP   ((uint32_t)0x00000100)"
.br
.ti -1c
.RI "#define \fBSDIO_Wait_Pend\fP   ((uint32_t)0x00000200)"
.br
.ti -1c
.RI "#define \fBIS_SDIO_WAIT\fP(WAIT)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_SDIO_WAIT(WAIT)"
\fBValue:\fP
.PP
.nf
(((WAIT) == SDIO_Wait_No) || ((WAIT) == SDIO_Wait_IT) || \
                            ((WAIT) == SDIO_Wait_Pend))
.fi
.PP
Definition at line 262 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_Wait_IT   ((uint32_t)0x00000100)"
SDIO Wait Interrupt Request 
.PP
Definition at line 260 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_Wait_No   ((uint32_t)0x00000000)"
SDIO No Wait, TimeOut is enabled 
.PP
Definition at line 259 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_Wait_Pend   ((uint32_t)0x00000200)"
SDIO Wait End of transfer 
.PP
Definition at line 261 of file stm32f10x_sdio\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
