.TH "SDIO_DPSM_State" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDIO_DPSM_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDIO_DPSM_Disable\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBSDIO_DPSM_Enable\fP   ((uint32_t)0x00000001)"
.br
.ti -1c
.RI "#define \fBIS_SDIO_DPSM\fP(DPSM)   (((DPSM) == \fBSDIO_DPSM_Enable\fP) || ((DPSM) == \fBSDIO_DPSM_Disable\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_SDIO_DPSM(DPSM)   (((DPSM) == \fBSDIO_DPSM_Enable\fP) || ((DPSM) == \fBSDIO_DPSM_Disable\fP))"

.PP
Definition at line 370 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_DPSM_Disable   ((uint32_t)0x00000000)"

.PP
Definition at line 368 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_DPSM_Enable   ((uint32_t)0x00000001)"

.PP
Definition at line 369 of file stm32f10x_sdio\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
