.TH "SDIO_Power_State" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDIO_Power_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDIO_PowerState_OFF\fP   ((uint32_t)0x00000000)"
.br
.ti -1c
.RI "#define \fBSDIO_PowerState_ON\fP   ((uint32_t)0x00000003)"
.br
.ti -1c
.RI "#define \fBIS_SDIO_POWER_STATE\fP(STATE)   (((STATE) == \fBSDIO_PowerState_OFF\fP) || ((STATE) == \fBSDIO_PowerState_ON\fP))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_SDIO_POWER_STATE(STATE)   (((STATE) == \fBSDIO_PowerState_OFF\fP) || ((STATE) == \fBSDIO_PowerState_ON\fP))"

.PP
Definition at line 193 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_PowerState_OFF   ((uint32_t)0x00000000)"

.PP
Definition at line 191 of file stm32f10x_sdio\&.h\&.
.SS "#define SDIO_PowerState_ON   ((uint32_t)0x00000003)"

.PP
Definition at line 192 of file stm32f10x_sdio\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
