.TH "SPI_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_TypeDef \- Serial Peripheral Interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCRCPR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRXCRCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBTXCRCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBI2SCFGR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBI2SPR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED8\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Serial Peripheral Interface\&. 
.PP
Definition at line 1160 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint16_t SPI_TypeDef::CR1"

.PP
Definition at line 1162 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::CR2"

.PP
Definition at line 1164 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::CRCPR"

.PP
Definition at line 1170 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::DR"

.PP
Definition at line 1168 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::I2SCFGR"

.PP
Definition at line 1176 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::I2SPR"

.PP
Definition at line 1178 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED0"

.PP
Definition at line 1163 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED1"

.PP
Definition at line 1165 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED2"

.PP
Definition at line 1167 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED3"

.PP
Definition at line 1169 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED4"

.PP
Definition at line 1171 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED5"

.PP
Definition at line 1173 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED6"

.PP
Definition at line 1175 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED7"

.PP
Definition at line 1177 of file stm32f10x\&.h\&.
.SS "uint16_t SPI_TypeDef::RESERVED8"

.PP
Definition at line 1179 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::RXCRCR"

.PP
Definition at line 1172 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::SR"

.PP
Definition at line 1166 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t SPI_TypeDef::TXCRCR"

.PP
Definition at line 1174 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
