.TH "SPI_Clock_Phase" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SPI_Clock_Phase
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSPI_CPHA_1Edge\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBSPI_CPHA_2Edge\fP   ((uint16_t)0x0001)"
.br
.ti -1c
.RI "#define \fBIS_SPI_CPHA\fP(CPHA)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_SPI_CPHA(CPHA)"
\fBValue:\fP
.PP
.nf
(((CPHA) == SPI_CPHA_1Edge) || \
                           ((CPHA) == SPI_CPHA_2Edge))
.fi
.PP
Definition at line 188 of file stm32f10x_spi\&.h\&.
.SS "#define SPI_CPHA_1Edge   ((uint16_t)0x0000)"

.PP
Definition at line 186 of file stm32f10x_spi\&.h\&.
.SS "#define SPI_CPHA_2Edge   ((uint16_t)0x0001)"

.PP
Definition at line 187 of file stm32f10x_spi\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
