.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_cec.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_cec.c \- This file provides all the CEC firmware functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x_cec\&.h'\fP
.br
\fC#include 'stm32f10x_rcc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCEC_OFFSET\fP   (\fBCEC_BASE\fP \- \fBPERIPH_BASE\fP)"
.br
.ti -1c
.RI "#define \fBCFGR_OFFSET\fP   (\fBCEC_OFFSET\fP + 0x00)"
.br
.ti -1c
.RI "#define \fBPE_BitNumber\fP   0x00"
.br
.ti -1c
.RI "#define \fBCFGR_PE_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCFGR_OFFSET\fP * 32) + (\fBPE_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBIE_BitNumber\fP   0x01"
.br
.ti -1c
.RI "#define \fBCFGR_IE_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCFGR_OFFSET\fP * 32) + (\fBIE_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBCSR_OFFSET\fP   (\fBCEC_OFFSET\fP + 0x10)"
.br
.ti -1c
.RI "#define \fBTSOM_BitNumber\fP   0x00"
.br
.ti -1c
.RI "#define \fBCSR_TSOM_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCSR_OFFSET\fP * 32) + (\fBTSOM_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBTEOM_BitNumber\fP   0x01"
.br
.ti -1c
.RI "#define \fBCSR_TEOM_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCSR_OFFSET\fP * 32) + (\fBTEOM_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBCFGR_CLEAR_Mask\fP   (uint8_t)(0xF3)        /* CFGR register Mask */"
.br
.ti -1c
.RI "#define \fBFLAG_Mask\fP   ((uint32_t)0x00FFFFFF) /* CEC FLAG mask */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCEC_DeInit\fP (void)"
.br
.RI "Deinitializes the CEC peripheral registers to their default reset values\&. "
.ti -1c
.RI "void \fBCEC_Init\fP (\fBCEC_InitTypeDef\fP *CEC_InitStruct)"
.br
.RI "Initializes the CEC peripheral according to the specified parameters in the CEC_InitStruct\&. "
.ti -1c
.RI "void \fBCEC_Cmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the specified CEC peripheral\&. "
.ti -1c
.RI "void \fBCEC_ITConfig\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the CEC interrupt\&. "
.ti -1c
.RI "void \fBCEC_OwnAddressConfig\fP (uint8_t CEC_OwnAddress)"
.br
.RI "Defines the Own Address of the CEC device\&. "
.ti -1c
.RI "void \fBCEC_SetPrescaler\fP (uint16_t CEC_Prescaler)"
.br
.RI "Sets the CEC prescaler value\&. "
.ti -1c
.RI "void \fBCEC_SendDataByte\fP (uint8_t Data)"
.br
.RI "Transmits single data through the CEC peripheral\&. "
.ti -1c
.RI "uint8_t \fBCEC_ReceiveDataByte\fP (void)"
.br
.RI "Returns the most recent received data by the CEC peripheral\&. "
.ti -1c
.RI "void \fBCEC_StartOfMessage\fP (void)"
.br
.RI "Starts a new message\&. "
.ti -1c
.RI "void \fBCEC_EndOfMessageCmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Transmits message with or without an EOM bit\&. "
.ti -1c
.RI "\fBFlagStatus\fP \fBCEC_GetFlagStatus\fP (uint32_t CEC_FLAG)"
.br
.RI "Gets the CEC flag status\&. "
.ti -1c
.RI "void \fBCEC_ClearFlag\fP (uint32_t CEC_FLAG)"
.br
.RI "Clears the CEC's pending flags\&. "
.ti -1c
.RI "\fBITStatus\fP \fBCEC_GetITStatus\fP (uint8_t CEC_IT)"
.br
.RI "Checks whether the specified CEC interrupt has occurred or not\&. "
.ti -1c
.RI "void \fBCEC_ClearITPendingBit\fP (uint16_t CEC_IT)"
.br
.RI "Clears the CEC's interrupt pending bits\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file provides all the CEC firmware functions\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBstm32f10x_cec\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
