.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_dac.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_dac.c \- This file provides all the DAC firmware functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x_dac\&.h'\fP
.br
\fC#include 'stm32f10x_rcc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCR_CLEAR_MASK\fP   ((uint32_t)0x00000FFE)"
.br
.ti -1c
.RI "#define \fBDUAL_SWTRIG_SET\fP   ((uint32_t)0x00000003)"
.br
.ti -1c
.RI "#define \fBDUAL_SWTRIG_RESET\fP   ((uint32_t)0xFFFFFFFC)"
.br
.ti -1c
.RI "#define \fBDHR12R1_OFFSET\fP   ((uint32_t)0x00000008)"
.br
.ti -1c
.RI "#define \fBDHR12R2_OFFSET\fP   ((uint32_t)0x00000014)"
.br
.ti -1c
.RI "#define \fBDHR12RD_OFFSET\fP   ((uint32_t)0x00000020)"
.br
.ti -1c
.RI "#define \fBDOR_OFFSET\fP   ((uint32_t)0x0000002C)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDAC_DeInit\fP (void)"
.br
.RI "Deinitializes the DAC peripheral registers to their default reset values\&. "
.ti -1c
.RI "void \fBDAC_Init\fP (uint32_t DAC_Channel, \fBDAC_InitTypeDef\fP *DAC_InitStruct)"
.br
.RI "Initializes the DAC peripheral according to the specified parameters in the DAC_InitStruct\&. "
.ti -1c
.RI "void \fBDAC_StructInit\fP (\fBDAC_InitTypeDef\fP *DAC_InitStruct)"
.br
.RI "Fills each DAC_InitStruct member with its default value\&. "
.ti -1c
.RI "void \fBDAC_Cmd\fP (uint32_t DAC_Channel, \fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the specified DAC channel\&. "
.ti -1c
.RI "void \fBDAC_DMACmd\fP (uint32_t DAC_Channel, \fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the specified DAC channel DMA request\&. "
.ti -1c
.RI "void \fBDAC_SoftwareTriggerCmd\fP (uint32_t DAC_Channel, \fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the selected DAC channel software trigger\&. "
.ti -1c
.RI "void \fBDAC_DualSoftwareTriggerCmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables simultaneously the two DAC channels software triggers\&. "
.ti -1c
.RI "void \fBDAC_WaveGenerationCmd\fP (uint32_t DAC_Channel, uint32_t DAC_Wave, \fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the selected DAC channel wave generation\&. "
.ti -1c
.RI "void \fBDAC_SetChannel1Data\fP (uint32_t DAC_Align, uint16_t Data)"
.br
.RI "Set the specified data holding register value for DAC channel1\&. "
.ti -1c
.RI "void \fBDAC_SetChannel2Data\fP (uint32_t DAC_Align, uint16_t Data)"
.br
.RI "Set the specified data holding register value for DAC channel2\&. "
.ti -1c
.RI "void \fBDAC_SetDualChannelData\fP (uint32_t DAC_Align, uint16_t Data2, uint16_t Data1)"
.br
.RI "Set the specified data holding register value for dual channel DAC\&. "
.ti -1c
.RI "uint16_t \fBDAC_GetDataOutputValue\fP (uint32_t DAC_Channel)"
.br
.RI "Returns the last data output value of the selected DAC channel\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file provides all the DAC firmware functions\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBstm32f10x_dac\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
