.TH "STM32F10x_System_Private_Variables" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STM32F10x_System_Private_Variables
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "uint32_t \fBSystemCoreClock\fP = \fBSYSCLK_FREQ_72MHz\fP"
.br
.ti -1c
.RI "\fB__I\fP uint8_t \fBAHBPrescTable\fP [16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Variable Documentation"
.PP 
.SS "\fB__I\fP uint8_t AHBPrescTable[16] = {0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}"

.PP
Definition at line 168 of file system_stm32f10x\&.c\&.
.SS "uint32_t SystemCoreClock = \fBSYSCLK_FREQ_72MHz\fP"
System Clock Frequency (Core Clock) 
.PP
Definition at line 163 of file system_stm32f10x\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
