.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph/stm32f10x_crc.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph/stm32f10x_crc.h \- This file contains all the functions prototypes for the CRC firmware library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBCRC_ResetDR\fP (void)"
.br
.RI "Resets the CRC Data register (DR)\&. "
.ti -1c
.RI "uint32_t \fBCRC_CalcCRC\fP (uint32_t Data)"
.br
.RI "Computes the 32-bit CRC of a given data word(32-bit)\&. "
.ti -1c
.RI "uint32_t \fBCRC_CalcBlockCRC\fP (uint32_t pBuffer[], uint32_t BufferLength)"
.br
.RI "Computes the 32-bit CRC of a given buffer of data word(32-bit)\&. "
.ti -1c
.RI "uint32_t \fBCRC_GetCRC\fP (void)"
.br
.RI "Returns the current CRC value\&. "
.ti -1c
.RI "void \fBCRC_SetIDRegister\fP (uint8_t IDValue)"
.br
.RI "Stores a 8-bit data in the Independent Data(ID) register\&. "
.ti -1c
.RI "uint8_t \fBCRC_GetIDRegister\fP (void)"
.br
.RI "Returns the 8-bit data stored in the Independent Data(ID) register\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the functions prototypes for the CRC firmware library\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBstm32f10x_crc\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
