.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph/stm32f10x_exti.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/include/stm32f1-stdperiph/stm32f10x_exti.h \- This file contains all the functions prototypes for the EXTI firmware library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBEXTI_InitTypeDef\fP"
.br
.RI "EXTI Init Structure definition\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_EXTI_MODE\fP(MODE)   (((MODE) == \fBEXTI_Mode_Interrupt\fP) || ((MODE) == \fBEXTI_Mode_Event\fP))"
.br
.ti -1c
.RI "#define \fBIS_EXTI_TRIGGER\fP(TRIGGER)"
.br
.ti -1c
.RI "#define \fBEXTI_Line0\fP   ((uint32_t)0x00001)"
.br
.ti -1c
.RI "#define \fBEXTI_Line1\fP   ((uint32_t)0x00002)"
.br
.ti -1c
.RI "#define \fBEXTI_Line2\fP   ((uint32_t)0x00004)"
.br
.ti -1c
.RI "#define \fBEXTI_Line3\fP   ((uint32_t)0x00008)"
.br
.ti -1c
.RI "#define \fBEXTI_Line4\fP   ((uint32_t)0x00010)"
.br
.ti -1c
.RI "#define \fBEXTI_Line5\fP   ((uint32_t)0x00020)"
.br
.ti -1c
.RI "#define \fBEXTI_Line6\fP   ((uint32_t)0x00040)"
.br
.ti -1c
.RI "#define \fBEXTI_Line7\fP   ((uint32_t)0x00080)"
.br
.ti -1c
.RI "#define \fBEXTI_Line8\fP   ((uint32_t)0x00100)"
.br
.ti -1c
.RI "#define \fBEXTI_Line9\fP   ((uint32_t)0x00200)"
.br
.ti -1c
.RI "#define \fBEXTI_Line10\fP   ((uint32_t)0x00400)"
.br
.ti -1c
.RI "#define \fBEXTI_Line11\fP   ((uint32_t)0x00800)"
.br
.ti -1c
.RI "#define \fBEXTI_Line12\fP   ((uint32_t)0x01000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line13\fP   ((uint32_t)0x02000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line14\fP   ((uint32_t)0x04000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line15\fP   ((uint32_t)0x08000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line16\fP   ((uint32_t)0x10000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line17\fP   ((uint32_t)0x20000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line18\fP   ((uint32_t)0x40000)"
.br
.ti -1c
.RI "#define \fBEXTI_Line19\fP   ((uint32_t)0x80000)"
.br
.ti -1c
.RI "#define \fBIS_EXTI_LINE\fP(LINE)   ((((LINE) & (uint32_t)0xFFF00000) == 0x00) && ((LINE) != (uint16_t)0x00))"
.br
.ti -1c
.RI "#define \fBIS_GET_EXTI_LINE\fP(LINE)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEXTIMode_TypeDef\fP { \fBEXTI_Mode_Interrupt\fP = 0x00, \fBEXTI_Mode_Event\fP = 0x04 }
.RI "EXTI mode enumeration\&. ""
.br
.ti -1c
.RI "enum \fBEXTITrigger_TypeDef\fP { \fBEXTI_Trigger_Rising\fP = 0x08, \fBEXTI_Trigger_Falling\fP = 0x0C, \fBEXTI_Trigger_Rising_Falling\fP = 0x10 }
.RI "EXTI Trigger enumeration\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBEXTI_DeInit\fP (void)"
.br
.RI "Deinitializes the EXTI peripheral registers to their default reset values\&. "
.ti -1c
.RI "void \fBEXTI_Init\fP (\fBEXTI_InitTypeDef\fP *EXTI_InitStruct)"
.br
.RI "Initializes the EXTI peripheral according to the specified parameters in the EXTI_InitStruct\&. "
.ti -1c
.RI "void \fBEXTI_StructInit\fP (\fBEXTI_InitTypeDef\fP *EXTI_InitStruct)"
.br
.RI "Fills each EXTI_InitStruct member with its reset value\&. "
.ti -1c
.RI "void \fBEXTI_GenerateSWInterrupt\fP (uint32_t EXTI_Line)"
.br
.RI "Generates a Software interrupt\&. "
.ti -1c
.RI "\fBFlagStatus\fP \fBEXTI_GetFlagStatus\fP (uint32_t EXTI_Line)"
.br
.RI "Checks whether the specified EXTI line flag is set or not\&. "
.ti -1c
.RI "void \fBEXTI_ClearFlag\fP (uint32_t EXTI_Line)"
.br
.RI "Clears the EXTI's line pending flags\&. "
.ti -1c
.RI "\fBITStatus\fP \fBEXTI_GetITStatus\fP (uint32_t EXTI_Line)"
.br
.RI "Checks whether the specified EXTI line is asserted or not\&. "
.ti -1c
.RI "void \fBEXTI_ClearITPendingBit\fP (uint32_t EXTI_Line)"
.br
.RI "Clears the EXTI's line pending bits\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file contains all the functions prototypes for the EXTI firmware library\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBstm32f10x_exti\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
