.TH "C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_pwr.c" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/system/src/stm32f1-stdperiph/stm32f10x_pwr.c \- This file provides all the PWR firmware functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f10x_pwr\&.h'\fP
.br
\fC#include 'stm32f10x_rcc\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPWR_OFFSET\fP   (\fBPWR_BASE\fP \- \fBPERIPH_BASE\fP)"
.br
.ti -1c
.RI "#define \fBCR_OFFSET\fP   (\fBPWR_OFFSET\fP + 0x00)"
.br
.ti -1c
.RI "#define \fBDBP_BitNumber\fP   0x08"
.br
.ti -1c
.RI "#define \fBCR_DBP_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCR_OFFSET\fP * 32) + (\fBDBP_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBPVDE_BitNumber\fP   0x04"
.br
.ti -1c
.RI "#define \fBCR_PVDE_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCR_OFFSET\fP * 32) + (\fBPVDE_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBCSR_OFFSET\fP   (\fBPWR_OFFSET\fP + 0x04)"
.br
.ti -1c
.RI "#define \fBEWUP_BitNumber\fP   0x08"
.br
.ti -1c
.RI "#define \fBCSR_EWUP_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCSR_OFFSET\fP * 32) + (\fBEWUP_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBCR_DS_MASK\fP   ((uint32_t)0xFFFFFFFC)"
.br
.ti -1c
.RI "#define \fBCR_PLS_MASK\fP   ((uint32_t)0xFFFFFF1F)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPWR_DeInit\fP (void)"
.br
.RI "Deinitializes the PWR peripheral registers to their default reset values\&. "
.ti -1c
.RI "void \fBPWR_BackupAccessCmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables access to the RTC and backup registers\&. "
.ti -1c
.RI "void \fBPWR_PVDCmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the Power Voltage Detector(PVD)\&. "
.ti -1c
.RI "void \fBPWR_PVDLevelConfig\fP (uint32_t PWR_PVDLevel)"
.br
.RI "Configures the voltage threshold detected by the Power Voltage Detector(PVD)\&. "
.ti -1c
.RI "void \fBPWR_WakeUpPinCmd\fP (\fBFunctionalState\fP NewState)"
.br
.RI "Enables or disables the WakeUp Pin functionality\&. "
.ti -1c
.RI "void \fBPWR_EnterSTOPMode\fP (uint32_t PWR_Regulator, uint8_t PWR_STOPEntry)"
.br
.RI "Enters STOP mode\&. "
.ti -1c
.RI "void \fBPWR_EnterSTANDBYMode\fP (void)"
.br
.RI "Enters STANDBY mode\&. "
.ti -1c
.RI "\fBFlagStatus\fP \fBPWR_GetFlagStatus\fP (uint32_t PWR_FLAG)"
.br
.RI "Checks whether the specified PWR flag is set or not\&. "
.ti -1c
.RI "void \fBPWR_ClearFlag\fP (uint32_t PWR_FLAG)"
.br
.RI "Clears the PWR's pending flags\&. "
.in -1c
.SH "Detailed Description"
.PP 
This file provides all the PWR firmware functions\&. 


.PP
\fBAuthor:\fP
.RS 4
MCD Application Team 
.RE
.PP
\fBVersion:\fP
.RS 4
V3\&.5\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
11-March-2011 
.RE
.PP
\fBAttention:\fP
.RS 4
.RE
.PP
THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE TIME\&. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS\&.
.PP
.SS "(C) COPYRIGHT 2011 STMicroelectronics"

.PP
Definition in file \fBstm32f10x_pwr\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
