.TH "TIM_DMA_Base_address" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_Base_address
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMABase_CR1\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CR2\fP   ((uint16_t)0x0001)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SMCR\fP   ((uint16_t)0x0002)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DIER\fP   ((uint16_t)0x0003)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_SR\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_EGR\fP   ((uint16_t)0x0005)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR1\fP   ((uint16_t)0x0006)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCMR2\fP   ((uint16_t)0x0007)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCER\fP   ((uint16_t)0x0008)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CNT\fP   ((uint16_t)0x0009)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_PSC\fP   ((uint16_t)0x000A)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_ARR\fP   ((uint16_t)0x000B)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_RCR\fP   ((uint16_t)0x000C)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR1\fP   ((uint16_t)0x000D)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR2\fP   ((uint16_t)0x000E)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR3\fP   ((uint16_t)0x000F)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_CCR4\fP   ((uint16_t)0x0010)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_BDTR\fP   ((uint16_t)0x0011)"
.br
.ti -1c
.RI "#define \fBTIM_DMABase_DCR\fP   ((uint16_t)0x0012)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_BASE\fP(BASE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_DMA_BASE(BASE)"
\fBValue:\fP
.PP
.nf
(((BASE) == TIM_DMABase_CR1) || \
                               ((BASE) == TIM_DMABase_CR2) || \
                               ((BASE) == TIM_DMABase_SMCR) || \
                               ((BASE) == TIM_DMABase_DIER) || \
                               ((BASE) == TIM_DMABase_SR) || \
                               ((BASE) == TIM_DMABase_EGR) || \
                               ((BASE) == TIM_DMABase_CCMR1) || \
                               ((BASE) == TIM_DMABase_CCMR2) || \
                               ((BASE) == TIM_DMABase_CCER) || \
                               ((BASE) == TIM_DMABase_CNT) || \
                               ((BASE) == TIM_DMABase_PSC) || \
                               ((BASE) == TIM_DMABase_ARR) || \
                               ((BASE) == TIM_DMABase_RCR) || \
                               ((BASE) == TIM_DMABase_CCR1) || \
                               ((BASE) == TIM_DMABase_CCR2) || \
                               ((BASE) == TIM_DMABase_CCR3) || \
                               ((BASE) == TIM_DMABase_CCR4) || \
                               ((BASE) == TIM_DMABase_BDTR) || \
                               ((BASE) == TIM_DMABase_DCR))
.fi
.PP
Definition at line 654 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_ARR   ((uint16_t)0x000B)"

.PP
Definition at line 646 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_BDTR   ((uint16_t)0x0011)"

.PP
Definition at line 652 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCER   ((uint16_t)0x0008)"

.PP
Definition at line 643 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCMR1   ((uint16_t)0x0006)"

.PP
Definition at line 641 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCMR2   ((uint16_t)0x0007)"

.PP
Definition at line 642 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCR1   ((uint16_t)0x000D)"

.PP
Definition at line 648 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCR2   ((uint16_t)0x000E)"

.PP
Definition at line 649 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCR3   ((uint16_t)0x000F)"

.PP
Definition at line 650 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CCR4   ((uint16_t)0x0010)"

.PP
Definition at line 651 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CNT   ((uint16_t)0x0009)"

.PP
Definition at line 644 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CR1   ((uint16_t)0x0000)"

.PP
Definition at line 635 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_CR2   ((uint16_t)0x0001)"

.PP
Definition at line 636 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_DCR   ((uint16_t)0x0012)"

.PP
Definition at line 653 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_DIER   ((uint16_t)0x0003)"

.PP
Definition at line 638 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_EGR   ((uint16_t)0x0005)"

.PP
Definition at line 640 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_PSC   ((uint16_t)0x000A)"

.PP
Definition at line 645 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_RCR   ((uint16_t)0x000C)"

.PP
Definition at line 647 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_SMCR   ((uint16_t)0x0002)"

.PP
Definition at line 637 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABase_SR   ((uint16_t)0x0004)"

.PP
Definition at line 639 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
