.TH "TIM_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_TypeDef \- TIM\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSMCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDIER\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBEGR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCMR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED6\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCMR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED7\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCER\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED8\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCNT\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED9\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBPSC\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED10\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBARR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED11\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBRCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED12\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED13\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED14\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCR3\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED15\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCCR4\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED16\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBBDTR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED17\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDCR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED18\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDMAR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED19\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM\&. 
.PP
Definition at line 1186 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint16_t TIM_TypeDef::ARR"

.PP
Definition at line 1210 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::BDTR"

.PP
Definition at line 1222 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCER"

.PP
Definition at line 1204 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCMR1"

.PP
Definition at line 1200 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCMR2"

.PP
Definition at line 1202 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCR1"

.PP
Definition at line 1214 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCR2"

.PP
Definition at line 1216 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCR3"

.PP
Definition at line 1218 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CCR4"

.PP
Definition at line 1220 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CNT"

.PP
Definition at line 1206 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CR1"

.PP
Definition at line 1188 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::CR2"

.PP
Definition at line 1190 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::DCR"

.PP
Definition at line 1224 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::DIER"

.PP
Definition at line 1194 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::DMAR"

.PP
Definition at line 1226 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::EGR"

.PP
Definition at line 1198 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::PSC"

.PP
Definition at line 1208 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::RCR"

.PP
Definition at line 1212 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED0"

.PP
Definition at line 1189 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED1"

.PP
Definition at line 1191 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED10"

.PP
Definition at line 1209 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED11"

.PP
Definition at line 1211 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED12"

.PP
Definition at line 1213 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED13"

.PP
Definition at line 1215 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED14"

.PP
Definition at line 1217 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED15"

.PP
Definition at line 1219 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED16"

.PP
Definition at line 1221 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED17"

.PP
Definition at line 1223 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED18"

.PP
Definition at line 1225 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED19"

.PP
Definition at line 1227 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED2"

.PP
Definition at line 1193 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED3"

.PP
Definition at line 1195 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED4"

.PP
Definition at line 1197 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED5"

.PP
Definition at line 1199 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED6"

.PP
Definition at line 1201 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED7"

.PP
Definition at line 1203 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED8"

.PP
Definition at line 1205 of file stm32f10x\&.h\&.
.SS "uint16_t TIM_TypeDef::RESERVED9"

.PP
Definition at line 1207 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::SMCR"

.PP
Definition at line 1192 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t TIM_TypeDef::SR"

.PP
Definition at line 1196 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
