.TH "TIM_Clock_Division_CKD" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Clock_Division_CKD
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CKD_DIV1\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_CKD_DIV2\fP   ((uint16_t)0x0100)"
.br
.ti -1c
.RI "#define \fBTIM_CKD_DIV4\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CKD_DIV\fP(DIV)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_CKD_DIV(DIV)"
\fBValue:\fP
.PP
.nf
(((DIV) == TIM_CKD_DIV1) || \
                             ((DIV) == TIM_CKD_DIV2) || \
                             ((DIV) == TIM_CKD_DIV4))
.fi
.PP
Definition at line 358 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_CKD_DIV1   ((uint16_t)0x0000)"

.PP
Definition at line 355 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_CKD_DIV2   ((uint16_t)0x0100)"

.PP
Definition at line 356 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_CKD_DIV4   ((uint16_t)0x0200)"

.PP
Definition at line 357 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
