.TH "TIM_Capture_Compare_N_state" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Capture_Compare_N_state
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_CCxN_Enable\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_CCxN_Disable\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CCXN\fP(CCXN)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_CCXN(CCXN)"
\fBValue:\fP
.PP
.nf
(((CCXN) == TIM_CCxN_Enable) || \
                           ((CCXN) == TIM_CCxN_Disable))
.fi
.PP
Definition at line 449 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_CCxN_Disable   ((uint16_t)0x0000)"

.PP
Definition at line 448 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_CCxN_Enable   ((uint16_t)0x0004)"

.PP
Definition at line 447 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
