.TH "TIM_Output_Compare_N_Idle_State" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_N_Idle_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCNIdleState_Set\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBTIM_OCNIdleState_Reset\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCNIDLE_STATE\fP(STATE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_OCNIDLE_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == TIM_OCNIdleState_Set) || \
                                     ((STATE) == TIM_OCNIdleState_Reset))
.fi
.PP
Definition at line 549 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCNIdleState_Reset   ((uint16_t)0x0000)"

.PP
Definition at line 548 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCNIdleState_Set   ((uint16_t)0x0200)"

.PP
Definition at line 547 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
