.TH "TIM_Output_Compare_Fast_State" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_Fast_State
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCFast_Enable\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_OCFast_Disable\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCFAST_STATE\fP(STATE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_OCFAST_STATE(STATE)"
\fBValue:\fP
.PP
.nf
(((STATE) == TIM_OCFast_Enable) || \
                                    ((STATE) == TIM_OCFast_Disable))
.fi
.PP
Definition at line 898 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCFast_Disable   ((uint16_t)0x0000)"

.PP
Definition at line 897 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCFast_Enable   ((uint16_t)0x0004)"

.PP
Definition at line 896 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
