.TH "TIM_Exported_Types" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_Types
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTIM_Exported_constants\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_and_PWM_modes\fP"
.br
.ti -1c
.RI "\fBTIM_One_Pulse_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Channel\fP"
.br
.ti -1c
.RI "\fBTIM_Clock_Division_CKD\fP"
.br
.ti -1c
.RI "\fBTIM_Counter_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_Polarity\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_N_Polarity\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_state\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_N_state\fP"
.br
.ti -1c
.RI "\fBTIM_Capture_Compare_state\fP"
.br
.ti -1c
.RI "\fBTIM_Capture_Compare_N_state\fP"
.br
.ti -1c
.RI "\fBBreak_Input_enable_disable\fP"
.br
.ti -1c
.RI "\fBBreak_Polarity\fP"
.br
.ti -1c
.RI "\fBTIM_AOE_Bit_Set_Reset\fP"
.br
.ti -1c
.RI "\fBLock_level\fP"
.br
.ti -1c
.RI "\fBOSSI_Off_State_Selection_for_Idle_mode_state\fP"
.br
.ti -1c
.RI "\fBOSSR_Off_State_Selection_for_Run_mode_state\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_Idle_State\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_N_Idle_State\fP"
.br
.ti -1c
.RI "\fBTIM_Input_Capture_Polarity\fP"
.br
.ti -1c
.RI "\fBTIM_Input_Capture_Selection\fP"
.br
.ti -1c
.RI "\fBTIM_Input_Capture_Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM_interrupt_sources\fP"
.br
.ti -1c
.RI "\fBTIM_DMA_Base_address\fP"
.br
.ti -1c
.RI "\fBTIM_DMA_Burst_Length\fP"
.br
.ti -1c
.RI "\fBTIM_DMA_sources\fP"
.br
.ti -1c
.RI "\fBTIM_External_Trigger_Prescaler\fP"
.br
.ti -1c
.RI "\fBTIM_Internal_Trigger_Selection\fP"
.br
.ti -1c
.RI "\fBTIM_TIx_External_Clock_Source\fP"
.br
.ti -1c
.RI "\fBTIM_External_Trigger_Polarity\fP"
.br
.ti -1c
.RI "\fBTIM_Prescaler_Reload_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Forced_Action\fP"
.br
.ti -1c
.RI "\fBTIM_Encoder_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Event_Source\fP"
.br
.ti -1c
.RI "\fBTIM_Update_Source\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_Preload_State\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_Fast_State\fP"
.br
.ti -1c
.RI "\fBTIM_Output_Compare_Clear_State\fP"
.br
.ti -1c
.RI "\fBTIM_Trigger_Output_Source\fP"
.br
.ti -1c
.RI "\fBTIM_Slave_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Master_Slave_Mode\fP"
.br
.ti -1c
.RI "\fBTIM_Flags\fP"
.br
.ti -1c
.RI "\fBTIM_Input_Capture_Filer_Value\fP"
.br
.ti -1c
.RI "\fBTIM_External_Trigger_Filter\fP"
.br
.ti -1c
.RI "\fBTIM_Legacy\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTIM_TimeBaseInitTypeDef\fP"
.br
.RI "TIM Time Base Init structure definition\&. "
.ti -1c
.RI "struct \fBTIM_OCInitTypeDef\fP"
.br
.RI "TIM Output Compare Init structure definition\&. "
.ti -1c
.RI "struct \fBTIM_ICInitTypeDef\fP"
.br
.RI "TIM Input Capture Init structure definition\&. "
.ti -1c
.RI "struct \fBTIM_BDTRInitTypeDef\fP"
.br
.RI "BDTR structure definition\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
