.TH "TIM_Trigger_Output_Source" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Trigger_Output_Source
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_TRGOSource_Reset\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_Enable\fP   ((uint16_t)0x0010)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_Update\fP   ((uint16_t)0x0020)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_OC1\fP   ((uint16_t)0x0030)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_OC1Ref\fP   ((uint16_t)0x0040)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_OC2Ref\fP   ((uint16_t)0x0050)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_OC3Ref\fP   ((uint16_t)0x0060)"
.br
.ti -1c
.RI "#define \fBTIM_TRGOSource_OC4Ref\fP   ((uint16_t)0x0070)"
.br
.ti -1c
.RI "#define \fBIS_TIM_TRGO_SOURCE\fP(SOURCE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_TRGO_SOURCE(SOURCE)"
\fBValue:\fP
.PP
.nf
(((SOURCE) == TIM_TRGOSource_Reset) || \
                                    ((SOURCE) == TIM_TRGOSource_Enable) || \
                                    ((SOURCE) == TIM_TRGOSource_Update) || \
                                    ((SOURCE) == TIM_TRGOSource_OC1) || \
                                    ((SOURCE) == TIM_TRGOSource_OC1Ref) || \
                                    ((SOURCE) == TIM_TRGOSource_OC2Ref) || \
                                    ((SOURCE) == TIM_TRGOSource_OC3Ref) || \
                                    ((SOURCE) == TIM_TRGOSource_OC4Ref))
.fi
.PP
Definition at line 929 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_Enable   ((uint16_t)0x0010)"

.PP
Definition at line 922 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_OC1   ((uint16_t)0x0030)"

.PP
Definition at line 924 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_OC1Ref   ((uint16_t)0x0040)"

.PP
Definition at line 925 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_OC2Ref   ((uint16_t)0x0050)"

.PP
Definition at line 926 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_OC3Ref   ((uint16_t)0x0060)"

.PP
Definition at line 927 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_OC4Ref   ((uint16_t)0x0070)"

.PP
Definition at line 928 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_Reset   ((uint16_t)0x0000)"

.PP
Definition at line 921 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_TRGOSource_Update   ((uint16_t)0x0020)"

.PP
Definition at line 923 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
