.TH "TIM_Slave_Mode" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Slave_Mode
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_SlaveMode_Reset\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_SlaveMode_Gated\fP   ((uint16_t)0x0005)"
.br
.ti -1c
.RI "#define \fBTIM_SlaveMode_Trigger\fP   ((uint16_t)0x0006)"
.br
.ti -1c
.RI "#define \fBTIM_SlaveMode_External1\fP   ((uint16_t)0x0007)"
.br
.ti -1c
.RI "#define \fBIS_TIM_SLAVE_MODE\fP(MODE)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_SLAVE_MODE(MODE)"
\fBValue:\fP
.PP
.nf
(((MODE) == TIM_SlaveMode_Reset) || \
                                 ((MODE) == TIM_SlaveMode_Gated) || \
                                 ((MODE) == TIM_SlaveMode_Trigger) || \
                                 ((MODE) == TIM_SlaveMode_External1))
.fi
.PP
Definition at line 949 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_SlaveMode_External1   ((uint16_t)0x0007)"

.PP
Definition at line 948 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_SlaveMode_Gated   ((uint16_t)0x0005)"

.PP
Definition at line 946 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_SlaveMode_Reset   ((uint16_t)0x0004)"

.PP
Definition at line 945 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_SlaveMode_Trigger   ((uint16_t)0x0006)"

.PP
Definition at line 947 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
