.TH "TIM_DMA_sources" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_DMA_sources
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMA_Update\fP   ((uint16_t)0x0100)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC1\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC2\fP   ((uint16_t)0x0400)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC3\fP   ((uint16_t)0x0800)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_CC4\fP   ((uint16_t)0x1000)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_COM\fP   ((uint16_t)0x2000)"
.br
.ti -1c
.RI "#define \fBTIM_DMA_Trigger\fP   ((uint16_t)0x4000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_DMA_SOURCE\fP(SOURCE)   ((((SOURCE) & (uint16_t)0x80FF) == 0x0000) && ((SOURCE) != 0x0000))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_DMA_SOURCE(SOURCE)   ((((SOURCE) & (uint16_t)0x80FF) == 0x0000) && ((SOURCE) != 0x0000))"

.PP
Definition at line 732 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_CC1   ((uint16_t)0x0200)"

.PP
Definition at line 726 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_CC2   ((uint16_t)0x0400)"

.PP
Definition at line 727 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_CC3   ((uint16_t)0x0800)"

.PP
Definition at line 728 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_CC4   ((uint16_t)0x1000)"

.PP
Definition at line 729 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_COM   ((uint16_t)0x2000)"

.PP
Definition at line 730 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_Trigger   ((uint16_t)0x4000)"

.PP
Definition at line 731 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMA_Update   ((uint16_t)0x0100)"

.PP
Definition at line 725 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
