.TH "TIM_Legacy" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Legacy
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_DMABurstLength_1Byte\fP   \fBTIM_DMABurstLength_1Transfer\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_2Bytes\fP   \fBTIM_DMABurstLength_2Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_3Bytes\fP   \fBTIM_DMABurstLength_3Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_4Bytes\fP   \fBTIM_DMABurstLength_4Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_5Bytes\fP   \fBTIM_DMABurstLength_5Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_6Bytes\fP   \fBTIM_DMABurstLength_6Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_7Bytes\fP   \fBTIM_DMABurstLength_7Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_8Bytes\fP   \fBTIM_DMABurstLength_8Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_9Bytes\fP   \fBTIM_DMABurstLength_9Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_10Bytes\fP   \fBTIM_DMABurstLength_10Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_11Bytes\fP   \fBTIM_DMABurstLength_11Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_12Bytes\fP   \fBTIM_DMABurstLength_12Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_13Bytes\fP   \fBTIM_DMABurstLength_13Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_14Bytes\fP   \fBTIM_DMABurstLength_14Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_15Bytes\fP   \fBTIM_DMABurstLength_15Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_16Bytes\fP   \fBTIM_DMABurstLength_16Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_17Bytes\fP   \fBTIM_DMABurstLength_17Transfers\fP"
.br
.ti -1c
.RI "#define \fBTIM_DMABurstLength_18Bytes\fP   \fBTIM_DMABurstLength_18Transfers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define TIM_DMABurstLength_10Bytes   \fBTIM_DMABurstLength_10Transfers\fP"

.PP
Definition at line 1035 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_11Bytes   \fBTIM_DMABurstLength_11Transfers\fP"

.PP
Definition at line 1036 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_12Bytes   \fBTIM_DMABurstLength_12Transfers\fP"

.PP
Definition at line 1037 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_13Bytes   \fBTIM_DMABurstLength_13Transfers\fP"

.PP
Definition at line 1038 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_14Bytes   \fBTIM_DMABurstLength_14Transfers\fP"

.PP
Definition at line 1039 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_15Bytes   \fBTIM_DMABurstLength_15Transfers\fP"

.PP
Definition at line 1040 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_16Bytes   \fBTIM_DMABurstLength_16Transfers\fP"

.PP
Definition at line 1041 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_17Bytes   \fBTIM_DMABurstLength_17Transfers\fP"

.PP
Definition at line 1042 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_18Bytes   \fBTIM_DMABurstLength_18Transfers\fP"

.PP
Definition at line 1043 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_1Byte   \fBTIM_DMABurstLength_1Transfer\fP"

.PP
Definition at line 1026 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_2Bytes   \fBTIM_DMABurstLength_2Transfers\fP"

.PP
Definition at line 1027 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_3Bytes   \fBTIM_DMABurstLength_3Transfers\fP"

.PP
Definition at line 1028 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_4Bytes   \fBTIM_DMABurstLength_4Transfers\fP"

.PP
Definition at line 1029 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_5Bytes   \fBTIM_DMABurstLength_5Transfers\fP"

.PP
Definition at line 1030 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_6Bytes   \fBTIM_DMABurstLength_6Transfers\fP"

.PP
Definition at line 1031 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_7Bytes   \fBTIM_DMABurstLength_7Transfers\fP"

.PP
Definition at line 1032 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_8Bytes   \fBTIM_DMABurstLength_8Transfers\fP"

.PP
Definition at line 1033 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_DMABurstLength_9Bytes   \fBTIM_DMABurstLength_9Transfers\fP"

.PP
Definition at line 1034 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
