.TH "TIM_Flags" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Flags
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_FLAG_Update\fP   ((uint16_t)0x0001)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1\fP   ((uint16_t)0x0002)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3\fP   ((uint16_t)0x0008)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4\fP   ((uint16_t)0x0010)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_COM\fP   ((uint16_t)0x0020)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_Trigger\fP   ((uint16_t)0x0040)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_Break\fP   ((uint16_t)0x0080)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC1OF\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC2OF\fP   ((uint16_t)0x0400)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC3OF\fP   ((uint16_t)0x0800)"
.br
.ti -1c
.RI "#define \fBTIM_FLAG_CC4OF\fP   ((uint16_t)0x1000)"
.br
.ti -1c
.RI "#define \fBIS_TIM_GET_FLAG\fP(FLAG)"
.br
.ti -1c
.RI "#define \fBIS_TIM_CLEAR_FLAG\fP(TIM_FLAG)   ((((TIM_FLAG) & (uint16_t)0xE100) == 0x0000) && ((TIM_FLAG) != 0x0000))"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_CLEAR_FLAG(TIM_FLAG)   ((((TIM_FLAG) & (uint16_t)0xE100) == 0x0000) && ((TIM_FLAG) != 0x0000))"

.PP
Definition at line 999 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_GET_FLAG(FLAG)"
\fBValue:\fP
.PP
.nf
(((FLAG) == TIM_FLAG_Update) || \
                               ((FLAG) == TIM_FLAG_CC1) || \
                               ((FLAG) == TIM_FLAG_CC2) || \
                               ((FLAG) == TIM_FLAG_CC3) || \
                               ((FLAG) == TIM_FLAG_CC4) || \
                               ((FLAG) == TIM_FLAG_COM) || \
                               ((FLAG) == TIM_FLAG_Trigger) || \
                               ((FLAG) == TIM_FLAG_Break) || \
                               ((FLAG) == TIM_FLAG_CC1OF) || \
                               ((FLAG) == TIM_FLAG_CC2OF) || \
                               ((FLAG) == TIM_FLAG_CC3OF) || \
                               ((FLAG) == TIM_FLAG_CC4OF))
.fi
.PP
Definition at line 985 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_Break   ((uint16_t)0x0080)"

.PP
Definition at line 980 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC1   ((uint16_t)0x0002)"

.PP
Definition at line 974 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC1OF   ((uint16_t)0x0200)"

.PP
Definition at line 981 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC2   ((uint16_t)0x0004)"

.PP
Definition at line 975 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC2OF   ((uint16_t)0x0400)"

.PP
Definition at line 982 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC3   ((uint16_t)0x0008)"

.PP
Definition at line 976 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC3OF   ((uint16_t)0x0800)"

.PP
Definition at line 983 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC4   ((uint16_t)0x0010)"

.PP
Definition at line 977 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_CC4OF   ((uint16_t)0x1000)"

.PP
Definition at line 984 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_COM   ((uint16_t)0x0020)"

.PP
Definition at line 978 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_Trigger   ((uint16_t)0x0040)"

.PP
Definition at line 979 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_FLAG_Update   ((uint16_t)0x0001)"

.PP
Definition at line 973 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
