.TH "TIM_Exported_constants" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Exported_constants
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIS_TIM_ALL_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST1_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST2_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST3_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST4_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST5_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST6_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST7_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST8_PERIPH\fP(PERIPH)"
.br
.ti -1c
.RI "#define \fBIS_TIM_LIST9_PERIPH\fP(PERIPH)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_ALL_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                   ((PERIPH) == TIM2) || \
                                   ((PERIPH) == TIM3) || \
                                   ((PERIPH) == TIM4) || \
                                   ((PERIPH) == TIM5) || \
                                   ((PERIPH) == TIM6) || \
                                   ((PERIPH) == TIM7) || \
                                   ((PERIPH) == TIM8) || \
                                   ((PERIPH) == TIM9) || \
                                   ((PERIPH) == TIM10)|| \
                                   ((PERIPH) == TIM11)|| \
                                   ((PERIPH) == TIM12)|| \
                                   ((PERIPH) == TIM13)|| \
                                   ((PERIPH) == TIM14)|| \
                                   ((PERIPH) == TIM15)|| \
                                   ((PERIPH) == TIM16)|| \
                                   ((PERIPH) == TIM17))
.fi
.PP
Definition at line 175 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST1_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                      ((PERIPH) == TIM8))
.fi
.PP
Definition at line 194 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST2_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                     ((PERIPH) == TIM8) || \
                                     ((PERIPH) == TIM15)|| \
                                     ((PERIPH) == TIM16)|| \
                                     ((PERIPH) == TIM17))
.fi
.PP
Definition at line 198 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST3_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                     ((PERIPH) == TIM2) || \
                                     ((PERIPH) == TIM3) || \
                                     ((PERIPH) == TIM4) || \
                                     ((PERIPH) == TIM5) || \
                                     ((PERIPH) == TIM8))
.fi
.PP
Definition at line 205 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST4_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                     ((PERIPH) == TIM2) || \
                                     ((PERIPH) == TIM3) || \
                                     ((PERIPH) == TIM4) || \
                                     ((PERIPH) == TIM5) || \
                                     ((PERIPH) == TIM8) || \
                                     ((PERIPH) == TIM15)|| \
                                     ((PERIPH) == TIM16)|| \
                                     ((PERIPH) == TIM17))
.fi
.PP
Definition at line 213 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST5_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                     ((PERIPH) == TIM2) || \
                                     ((PERIPH) == TIM3) || \
                                     ((PERIPH) == TIM4) || \
                                     ((PERIPH) == TIM5) || \
                                     ((PERIPH) == TIM8) || \
                                     ((PERIPH) == TIM15))
.fi
.PP
Definition at line 224 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST6_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                      ((PERIPH) == TIM2) || \
                                      ((PERIPH) == TIM3) || \
                                      ((PERIPH) == TIM4) || \
                                      ((PERIPH) == TIM5) || \
                                      ((PERIPH) == TIM8) || \
                                      ((PERIPH) == TIM9) || \
                                      ((PERIPH) == TIM12)|| \
                                      ((PERIPH) == TIM15))
.fi
.PP
Definition at line 233 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST7_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                      ((PERIPH) == TIM2) || \
                                      ((PERIPH) == TIM3) || \
                                      ((PERIPH) == TIM4) || \
                                      ((PERIPH) == TIM5) || \
                                      ((PERIPH) == TIM6) || \
                                      ((PERIPH) == TIM7) || \
                                      ((PERIPH) == TIM8) || \
                                      ((PERIPH) == TIM9) || \
                                      ((PERIPH) == TIM12)|| \
                                      ((PERIPH) == TIM15))
.fi
.PP
Definition at line 244 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST8_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                      ((PERIPH) == TIM2) || \
                                      ((PERIPH) == TIM3) || \
                                      ((PERIPH) == TIM4) || \
                                      ((PERIPH) == TIM5) || \
                                      ((PERIPH) == TIM8) || \
                                      ((PERIPH) == TIM9) || \
                                      ((PERIPH) == TIM10)|| \
                                      ((PERIPH) == TIM11)|| \
                                      ((PERIPH) == TIM12)|| \
                                      ((PERIPH) == TIM13)|| \
                                      ((PERIPH) == TIM14)|| \
                                      ((PERIPH) == TIM15)|| \
                                      ((PERIPH) == TIM16)|| \
                                      ((PERIPH) == TIM17))
.fi
.PP
Definition at line 257 of file stm32f10x_tim\&.h\&.
.SS "#define IS_TIM_LIST9_PERIPH(PERIPH)"
\fBValue:\fP
.PP
.nf
(((PERIPH) == TIM1) || \
                                      ((PERIPH) == TIM2) || \
                                      ((PERIPH) == TIM3) || \
                                      ((PERIPH) == TIM4) || \
                                      ((PERIPH) == TIM5) || \
                                      ((PERIPH) == TIM6) || \
                                      ((PERIPH) == TIM7) || \
                                      ((PERIPH) == TIM8) || \
                                      ((PERIPH) == TIM15)|| \
                                      ((PERIPH) == TIM16)|| \
                                      ((PERIPH) == TIM17))
.fi
.PP
Definition at line 274 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
