.TH "TIM_Output_Compare_N_Polarity" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Output_Compare_N_Polarity
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIM_OCNPolarity_High\fP   ((uint16_t)0x0000)"
.br
.ti -1c
.RI "#define \fBTIM_OCNPolarity_Low\fP   ((uint16_t)0x0008)"
.br
.ti -1c
.RI "#define \fBIS_TIM_OCN_POLARITY\fP(POLARITY)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define IS_TIM_OCN_POLARITY(POLARITY)"
\fBValue:\fP
.PP
.nf
(((POLARITY) == TIM_OCNPolarity_High) || \
                                       ((POLARITY) == TIM_OCNPolarity_Low))
.fi
.PP
Definition at line 401 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCNPolarity_High   ((uint16_t)0x0000)"

.PP
Definition at line 399 of file stm32f10x_tim\&.h\&.
.SS "#define TIM_OCNPolarity_Low   ((uint16_t)0x0008)"

.PP
Definition at line 400 of file stm32f10x_tim\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
