.TH "TIM_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSMCR_ETR_Mask\fP   ((uint16_t)0x00FF)"
.br
.ti -1c
.RI "#define \fBCCMR_Offset\fP   ((uint16_t)0x0018)"
.br
.ti -1c
.RI "#define \fBCCER_CCE_Set\fP   ((uint16_t)0x0001)"
.br
.ti -1c
.RI "#define \fBCCER_CCNE_Set\fP   ((uint16_t)0x0004)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define CCER_CCE_Set   ((uint16_t)0x0001)"

.PP
Definition at line 50 of file stm32f10x_tim\&.c\&.
.SS "#define CCER_CCNE_Set   ((uint16_t)0x0004)"

.PP
Definition at line 51 of file stm32f10x_tim\&.c\&.
.SS "#define CCMR_Offset   ((uint16_t)0x0018)"

.PP
Definition at line 49 of file stm32f10x_tim\&.c\&.
.SS "#define SMCR_ETR_Mask   ((uint16_t)0x00FF)"

.PP
Definition at line 48 of file stm32f10x_tim\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
