.TH "TIM_ICInitTypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TIM_ICInitTypeDef \- TIM Input Capture Init structure definition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x_tim\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBTIM_Channel\fP"
.br
.ti -1c
.RI "uint16_t \fBTIM_ICPolarity\fP"
.br
.ti -1c
.RI "uint16_t \fBTIM_ICSelection\fP"
.br
.ti -1c
.RI "uint16_t \fBTIM_ICPrescaler\fP"
.br
.ti -1c
.RI "uint16_t \fBTIM_ICFilter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TIM Input Capture Init structure definition\&. 
.PP
Definition at line 121 of file stm32f10x_tim\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t TIM_ICInitTypeDef::TIM_Channel"
Specifies the TIM channel\&. This parameter can be a value of \fBTIM_Channel\fP 
.PP
Definition at line 124 of file stm32f10x_tim\&.h\&.
.SS "uint16_t TIM_ICInitTypeDef::TIM_ICFilter"
Specifies the input capture filter\&. This parameter can be a number between 0x0 and 0xF 
.PP
Definition at line 136 of file stm32f10x_tim\&.h\&.
.SS "uint16_t TIM_ICInitTypeDef::TIM_ICPolarity"
Specifies the active edge of the input signal\&. This parameter can be a value of \fBTIM_Input_Capture_Polarity\fP 
.PP
Definition at line 127 of file stm32f10x_tim\&.h\&.
.SS "uint16_t TIM_ICInitTypeDef::TIM_ICPrescaler"
Specifies the Input Capture Prescaler\&. This parameter can be a value of \fBTIM_Input_Capture_Prescaler\fP 
.PP
Definition at line 133 of file stm32f10x_tim\&.h\&.
.SS "uint16_t TIM_ICInitTypeDef::TIM_ICSelection"
Specifies the input\&. This parameter can be a value of \fBTIM_Input_Capture_Selection\fP 
.PP
Definition at line 130 of file stm32f10x_tim\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
