.TH "C:/Users/anilj/Desktop/cmsis/sorc/include/Timer.h" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/anilj/Desktop/cmsis/sorc/include/Timer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'cmsis_device\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTimer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
