.TH "USART_TypeDef" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
USART_TypeDef \- Universal Synchronous Asynchronous Receiver Transmitter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stm32f10x\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fB__IO\fP uint16_t \fBSR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED0\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBDR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED1\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBBRR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED2\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR1\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED3\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR2\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED4\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBCR3\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED5\fP"
.br
.ti -1c
.RI "\fB__IO\fP uint16_t \fBGTPR\fP"
.br
.ti -1c
.RI "uint16_t \fBRESERVED6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Universal Synchronous Asynchronous Receiver Transmitter\&. 
.PP
Definition at line 1234 of file stm32f10x\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fB__IO\fP uint16_t USART_TypeDef::BRR"

.PP
Definition at line 1240 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::CR1"

.PP
Definition at line 1242 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::CR2"

.PP
Definition at line 1244 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::CR3"

.PP
Definition at line 1246 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::DR"

.PP
Definition at line 1238 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::GTPR"

.PP
Definition at line 1248 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED0"

.PP
Definition at line 1237 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED1"

.PP
Definition at line 1239 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED2"

.PP
Definition at line 1241 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED3"

.PP
Definition at line 1243 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED4"

.PP
Definition at line 1245 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED5"

.PP
Definition at line 1247 of file stm32f10x\&.h\&.
.SS "uint16_t USART_TypeDef::RESERVED6"

.PP
Definition at line 1249 of file stm32f10x\&.h\&.
.SS "\fB__IO\fP uint16_t USART_TypeDef::SR"

.PP
Definition at line 1236 of file stm32f10x\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
