.TH "WWDG_Private_Defines" 3 "Sun Apr 16 2017" "STM32_CMSIS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WWDG_Private_Defines
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWWDG_OFFSET\fP   (\fBWWDG_BASE\fP \- \fBPERIPH_BASE\fP)"
.br
.ti -1c
.RI "#define \fBCFR_OFFSET\fP   (\fBWWDG_OFFSET\fP + 0x04)"
.br
.ti -1c
.RI "#define \fBEWI_BitNumber\fP   0x09"
.br
.ti -1c
.RI "#define \fBCFR_EWI_BB\fP   (\fBPERIPH_BB_BASE\fP + (\fBCFR_OFFSET\fP * 32) + (\fBEWI_BitNumber\fP * 4))"
.br
.ti -1c
.RI "#define \fBCR_WDGA_Set\fP   ((uint32_t)0x00000080)"
.br
.ti -1c
.RI "#define \fBCFR_WDGTB_Mask\fP   ((uint32_t)0xFFFFFE7F)"
.br
.ti -1c
.RI "#define \fBCFR_W_Mask\fP   ((uint32_t)0xFFFFFF80)"
.br
.ti -1c
.RI "#define \fBBIT_Mask\fP   ((uint8_t)0x7F)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define BIT_Mask   ((uint8_t)0x7F)"

.PP
Definition at line 63 of file stm32f10x_wwdg\&.c\&.
.SS "#define CFR_EWI_BB   (\fBPERIPH_BB_BASE\fP + (\fBCFR_OFFSET\fP * 32) + (\fBEWI_BitNumber\fP * 4))"

.PP
Definition at line 53 of file stm32f10x_wwdg\&.c\&.
.SS "#define CFR_OFFSET   (\fBWWDG_OFFSET\fP + 0x04)"

.PP
Definition at line 51 of file stm32f10x_wwdg\&.c\&.
.SS "#define CFR_W_Mask   ((uint32_t)0xFFFFFF80)"

.PP
Definition at line 62 of file stm32f10x_wwdg\&.c\&.
.SS "#define CFR_WDGTB_Mask   ((uint32_t)0xFFFFFE7F)"

.PP
Definition at line 61 of file stm32f10x_wwdg\&.c\&.
.SS "#define CR_WDGA_Set   ((uint32_t)0x00000080)"

.PP
Definition at line 58 of file stm32f10x_wwdg\&.c\&.
.SS "#define EWI_BitNumber   0x09"

.PP
Definition at line 52 of file stm32f10x_wwdg\&.c\&.
.SS "#define WWDG_OFFSET   (\fBWWDG_BASE\fP \- \fBPERIPH_BASE\fP)"

.PP
Definition at line 48 of file stm32f10x_wwdg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for STM32_CMSIS from the source code\&.
